### PR TITLE
Fixing hash collision issue when adding filter value to the variant context

### LINKED ISSUE #3291: FilterByOrientationBias gives random failures
Out of 11 runs on exactly the same data, FilterByOrientationBias fails 6 times and succeeds 5 times. Assigning @LeeTL1220, given prior interaction with user.

- User reports this error in: https://gatkforums.broadinstitute.org/gatk/discussion/comment/40412#Comment_40412
- My recapitulation is in: https://github.com/broadinstitute/dsde-docs/issues/2294

Data is at `/humgen/gsa-scr1/pub/incoming/byoo_FilterByOrientationBias.zip`.

Command is:
```
gatk-launch FilterByOrientationBias \
    -A 'G/T' -A 'C/T' \
    -V test2.vcf \
    -P test2.pre_adapter_detail_metrics \
    --output ob_filtered2.vcf
```

Error message changes between:
```
java.lang.IllegalStateException: Allele in genotype C* not in the variant context [G*, T]
	at htsjdk.variant.variantcontext.VariantContext.validateGenotypes(VariantContext.java:1360)
	at htsjdk.variant.variantcontext.VariantContext.validate(VariantContext.java:1298)
	at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:401)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:494)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:488)
	at org.broadinstitute.hellbender.tools.exome.orientationbiasvariantfilter.OrientationBiasFilterer.annotateVariantContextsWithFilterResults(OrientationBiasFilterer.java:216)
	at org.broadinstitute.hellbender.tools.exome.FilterByOrientationBias.onTraversalSuccess(FilterByOrientationBias.java:168)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:781)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:115)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:122)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:143)
	at org.broadinstitute.hellbender.Main.main(Main.java:221)
```
and
```
java.lang.IllegalStateException: Allele in genotype G* not in the variant context [C*, T]
	at htsjdk.variant.variantcontext.VariantContext.validateGenotypes(VariantContext.java:1360)
	at htsjdk.variant.variantcontext.VariantContext.validate(VariantContext.java:1298)
	at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:401)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:494)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:488)
	at org.broadinstitute.hellbender.tools.exome.orientationbiasvariantfilter.OrientationBiasFilterer.annotateVariantContextsWithFilterResults(OrientationBiasFilterer.java:216)
	at org.broadinstitute.hellbender.tools.exome.FilterByOrientationBias.onTraversalSuccess(FilterByOrientationBias.java:211)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:840)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:115)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:131)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:152)
	at org.broadinstitute.hellbender.Main.main(Main.java:230)
```

I tested using `gatk-package-4.beta.1-local.jar` and pre-release alpha version `gatk-4.alpha.2-1134-ga9d9d91-SNAPSHOT/gatk-package-4.alpha.2-1134-ga9d9d91-SNAPSHOT-local.jar`.

### PR DESCRIPTION
**Pull request by LeeTL1220**
Closes #3291 

- Detects the issue earlier and fails with a better error message that is local (in code) to the problem.
- Removes the spew of warnings that are not useful except in debug.
- Fixes an issue where filter values were being replaced instead of appended.
- Implemented a wrapper to always guarantee sorting never collides.

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java [hunk 1]
```diff
@@ -58,7 +58,7 @@ public static VariantContext annotateVariantContextWithPreprocessingValues(final
 
             final List<Allele> alleles = genotype.getAlleles();
             if (genotype.getPloidy() != 2) {
-                logger.warn("No action required:  This tool will skip non-diploid sites.  Saw GT: " + genotype.getGenotypeString() + " at " + vc.toStringWithoutGenotypes());
+                logger.debug("No action required:  This tool will skip non-diploid sites.  Saw GT: " + genotype.getGenotypeString() + " at " + vc.toStringWithoutGenotypes());
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: Do we output this at every non-diploid site?  Should we change that?

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java [hunk 2]
```diff
@@ -210,8 +210,11 @@ private static double calculateFob(final Genotype genotype, final boolean isRele
                 final List<Genotype> newGenotypesForThisVariantContext = newGenotypes.get(vc);
                 newGenotypesForThisVariantContext.forEach(gcc::replace);
                 final VariantContextBuilder variantContextBuilder = new VariantContextBuilder(vc).genotypes(gcc);
+
+                // Add the orientation bias filter to the variant context.
                 if (newGenotypesForThisVariantContext.stream().anyMatch(g -> (g != null) && (g.getFilters() != null) && (g.getFilters().contains(OrientationBiasFilterConstants.IS_ORIENTATION_BIAS_CUT)))) {
-                    variantContextBuilder.filter(OrientationBiasFilterConstants.IS_ORIENTATION_BIAS_CUT);
+                    final List<String> result = GATKVariantContextUtils.createFilterListWithAppend(vc, OrientationBiasFilterConstants.IS_ORIENTATION_BIAS_CUT);
+                    variantContextBuilder.filters(result.toArray(new String[0]));
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: Might as well use the size of the list here.

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 1 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: I set it to debug.  Most of those are M2 making bad calls anyway.

No action.

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 2 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: Why does it matter?

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 1 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: (This tool is not run on germline data)

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 2 above)
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: save an array allocation?  it doesn't really matter much

File: src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java [hunk 3]
```diff
@@ -70,7 +70,7 @@ private VariantContext makeVC(String source, List<Allele> alleles, Genotype... g
     }
 
     private VariantContext makeVC(String source, List<Allele> alleles, String filter) {
-        return makeVC(source, alleles, filter.equals(".") ? null : new LinkedHashSet<>(Collections.singletonList(filter)));
+        return makeVC(source, alleles, filter.equals(".") ? null : new LinkedHashSet<String>(Collections.singletonList(filter)));
```
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java]: why did you add a type here? Wasn't it inferred?

File: src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java [hunk 4]
```diff
@@ -1469,4 +1469,21 @@ public static int calculateGQFromPLs(final int[] plValues) {
...
         return second - first;
     }
+
+    /**
+     *  Create a string with existing filters plus the one to append
+     * @param vc VariantContext to base initial filter values.  Not {@code null}
+     * @param filterToAppend the filter value to append to the strings Not {@code null}
+     * @return String of filter values.  Sorted alphabetically.
+     */
+    public static List<String> createFilterListWithAppend(VariantContext vc, String filterToAppend) {
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java]: This seems clunky and pretty specific to this one use case.  Why not have a method `addToFilterList(List<String>, String)` which adds and sorts the values instead?

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java [hunk 5]
```diff
@@ -294,11 +297,12 @@ static int calculateTotalNumToCut(final double fdrThreshold, final long unfilter
...
 
         // Sorts in reverse order (highest p_artifact goes first and will not allow anything to be equal
-        //  unless they share the same reference)
+        //  unless they share the same reference).  Unfortunately, we cannot check the actual reference, so we rely on
+        //  hashCode and the genotype rendered as a string to be universally unique.
         // Note the negative sign is to sort in reverse error.
         final Comparator<Genotype> genotypePArtifactComparator = Comparator
                 .comparingDouble((Genotype g) -> -OrientationBiasUtils.getGenotypeDouble(g, OrientationBiasFilterConstants.P_ARTIFACT_FIELD_NAME, 0.0))
-                .thenComparingInt(g -> g.hashCode());
+                .thenComparingInt(g -> g.hashCode()).thenComparing(Genotype::toString);
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: This still seems like a gross hack to me.  It seems like it would be better to solve this problem properly rather than just kicking it out to less and less probable territory.

Why not create a private subclass of Genotype that includes a static atomic counter that's incremented each time one is created, and then use that in the comparator?

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 1 above)
Comment (magicDGS) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: Maybe use the `{}` syntax of the logger to avoid the construction of the genotype/variant strings:

```java
logger.debug("No action required:  This tool will skip non-diploid sites.  Saw GT: {} at {}",
    genotype::getGenotypeString, vc::toStringWithoutGenotypes);
```

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 5 above)
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: Alternatively you could use a stateful comparator that tracks collision resolutions to convert the partial ordering by score into a TreeMap compatible total ordering.  http://gafter.blogspot.com/2007/03/compact-object-comparator.html

Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: :+1: to this idea

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 1 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: Done

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 2 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: Done

File: src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java (hunk 3 above)
Comment (LeeTL1220) [inline src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java]: Not according to IntelliJ.

No action.

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 5 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: Doing UniqueIdWrapper.  Makes the code a bit messy, but looks like it works.  Also, slows down the tool a bit, but not drastically.

Done

**Comment by LeeTL1220** [comment]
@lbergelson Please review again...  Thanks

File: src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java (hunk 4 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java]: Then it can just be appending to a list and sorting.  And this is in GATKVariantContextUtils, after all.

I liked the convenience of just being able to get an updated filter set in one call.

No action, unless you strongly disagree.  

No action.

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java [hunk 6]
```diff
@@ -322,6 +329,21 @@ static int calculateTotalNumToCut(final double fdrThreshold, final long unfilter
...
+     *
+     * @param genotypesToConsiderForFiltering SortedMap, changed in place
+     * @param genotype key to insert into the sorted map
+     * @param vc value to insert into the sorted map
+     */
+    private static void putDisallowingKeyOverwrite(SortedMap<UniqueIDWrapper<Genotype>, VariantContext> genotypesToConsiderForFiltering, Genotype genotype, VariantContext vc) {
+
+        final VariantContext vcTemp = genotypesToConsiderForFiltering.putIfAbsent(new UniqueIDWrapper<>(genotype), vc);
+        if (vcTemp != null) {
+            throw new GATKException.ShouldNeverReachHereException("This error may disappear on a subsequent run of this tool, so please try running this tool again.  Otherwise, this can only be fixed by a GATK developer.  Attempting to overwrite a key in the genotypes for filtering map.  This means that genotypePArtifactComparator is (still) not generating unique keys.  See https://github.com/broadinstitute/gatk/issues/3291");
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: This comment is out of date now, but it's not a bad idea to keep the check in place.

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java [hunk 7]
```diff
@@ -362,4 +384,23 @@ public static VCFHeader createVCFHeader(final VCFHeader inputVCFHeader, final St
         final Set<String> sampleNameSet = samples.asSetOfSamples();
         return new VCFHeader(headerLines, sampleNameSet);
     }
+
+    static class UniqueIDWrapper<A>{
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: If it would make the code cleaner you could drop the type parameter and just hardcode it as a genotype.  Probably want to add a comment explaining why we have this class.

File: src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java (hunk 4 above)
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java]: If you're going to leave it as is do you want to bake the conversion to array into it as well?

File: src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java (hunk 3 above)
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java]: Interesting, your intellij and my intellij don't agree for some reason.

**Comment by lbergelson** [comment]
@LeeTL1220 A few minor remaining comments.  Do what you will.  How much of a performance impact does the change have?  You said it slows it down, is it significant?  It might be faster if you make it a long instead of an atomic long which should be safe it it's single threaded and you don't use parallel streams anywhere.

File: src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java (hunk 4 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java]: Leave as is

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 6 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: Thanks

No action

**Comment by LeeTL1220** [comment]
@lbergelson Performance hit is not enough to worry about.

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java (hunk 7 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasFilterer.java]: Moving to a separate class.

File: src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java (hunk 3 above)
Comment (pshapiro4broad) [inline src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java]: @LeeTL1220 maybe your intellij isn't set up to use JDK7+ features? You should be able to fix this on the Project Settings page.

**Comment by lbergelson** [comment]
@LeeTL1220 👍 Good to merge.

**Comment by sooheelee** [comment]
I have notified the user who reported this error of the fix.
