### PR TITLE
fixed incoherent unit test cases in allele subsetting utils

### LINKED ISSUE #3672: investigate potential bug in AlleleSubsettingUtilsUnitTest
Yossi noticed that the result alleles in some of the `AlleleSubsettingUtilsUnitTest.makeUpdatePLsSACsAndADData` tests seem to be incorrect given the PLs and names

https://github.com/broadinstitute/gatk/blob/e919f85b1b9c34a1239c4a3e87db4e1678e58aaf/src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java#L151-L156

After further inspection it looks like the input alleles for the genotypes may also be incorrect.  The named pls in the input describe a het-C, but the genotype is given as AA.  The output is AA when it seems like it should be AC.  

We should figure out if there's something wrong here, or if I'm just misunderstanding something.

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #3672.

@ldgauthier The ADs, GTs, and PLs were inconsistent.

### CODE REVIEW

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java [hunk 1]
```diff
@@ -105,19 +107,20 @@ public void testUpdatePLsAndADData(final VariantContext originalVC,
         // for P=3 and N=2, the ordering is 000, 001, 011, 111, 002, 012, 112, 022, 122, 222
         final double[] triploidRef3AllelesPL = new double[]{0, -10, -20, -30, -40, -50, -60, -70, -80, -90};
         final double[] tripoidAltC3AllelesPL = new double[]{-10, 0, -20, -30, -40, -50, -60, -70, -80, -90};
+        final double[] tripoidAltG3AllelesPL = new double[]{-10, -40, -70, -90, 0, -50, -80, -20, -60, -30};
```
Comment (ldgauthier) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: It would be great to fix these typos for searchability -- tripoid > triploid

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java [hunk 2]
```diff
@@ -56,7 +56,9 @@ public void testUpdatePLsAndADData(final VariantContext originalVC,
         final List<Allele> AA = Arrays.asList(Aref, Aref);
         final List<Allele> AC = Arrays.asList(Aref,C);
         final List<Allele> CC = Arrays.asList(C,C);
+        final List<Allele> CG = Arrays.asList(C,G);
         final List<Allele> AG = Arrays.asList(Aref,G);
+        final List<Allele> GG = Arrays.asList(G,G);
```
Comment (ldgauthier) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: The genotypes around line 74 have bad ADs too -- `Genotype acGT` and `Genotype ccGT`

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java [hunk 3]
```diff
@@ -130,9 +133,9 @@ public void testUpdatePLsAndADData(final VariantContext originalVC,
                 Collections.singletonList(new GenotypeBuilder(base).alleles(Arrays.asList(Aref, Aref, C)).PL(new double[]{-10, 0, -20, -30}).AD(new int[]{10, 10}).GQ(100).make())});
 
         tests.add(new Object[]{
-                new VariantContextBuilder(vcBase).alleles(ACG).genotypes(new GenotypeBuilder(base).alleles(Arrays.asList(Aref, Aref, G)).AD(homRef3AllelesAD).PL(triploidRef3AllelesPL).make()).make(),
+                new VariantContextBuilder(vcBase).alleles(ACG).genotypes(new GenotypeBuilder(base).alleles(Arrays.asList(Aref, Aref, G)).AD(hetRefG3AllelesAD).PL(tripoidAltG3AllelesPL).make()).make(),
                 new VariantContextBuilder(vcBase).alleles(AG).make(),
-                Collections.singletonList(new GenotypeBuilder(base).alleles(Arrays.asList(Aref, Aref, G)).PL(new double[]{0, -40, -70, -90}).AD(new int[]{20, 1}).GQ(400).make())});
+                Collections.singletonList(new GenotypeBuilder(base).alleles(Arrays.asList(Aref, Aref, G)).PL(new double[]{-10, 0, -20, -30}).AD(new int[]{10, 11}).GQ(100).make())});
```
Comment (ldgauthier) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: The allele balance on this AD isn't great -- can we do like {14,7} so the genotype is more obvious?

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java [hunk 4]
```diff
@@ -130,9 +133,9 @@ public void testUpdatePLsAndADData(final VariantContext originalVC,
                 Collections.singletonList(new GenotypeBuilder(base).alleles(Arrays.asList(Aref, Aref, C)).PL(new double[]{-10, 0, -20, -30}).AD(new int[]{10, 10}).GQ(100).make())});
```
Comment (ldgauthier) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: Same here -- I'd rather a 2:1 ratio on AD.  And the PLs don't look big enough.

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java [hunk 5]
```diff
@@ -149,38 +152,31 @@ public void testUpdatePLsAndADData(final VariantContext originalVC,
...
-                new VariantContextBuilder(vcBase).alleles(ACG).genotypes(new GenotypeBuilder(base).alleles(AA).AD(hetRefG3AllelesAD).PL(hetRefG3AllelesPL).
+                new VariantContextBuilder(vcBase).alleles(ACG).genotypes(new GenotypeBuilder(base).alleles(AG).AD(hetRefG3AllelesAD).PL(hetRefG3AllelesPL).
                         attribute(GATKVCFConstants.STRAND_COUNT_BY_SAMPLE_KEY, hetRefG3AllelesSAC).make()).make(),
                 new VariantContextBuilder(vcBase).alleles(AG).make(),
-                Collections.singletonList(new GenotypeBuilder(base).alleles(AA).PL(new double[]{-20, 0, -50}).AD(new int[]{10, 11}).
+                Collections.singletonList(new GenotypeBuilder(base).alleles(AG).PL(new double[]{-20, 0, -50}).AD(new int[]{10, 11}).
                         attribute(GATKVCFConstants.STRAND_COUNT_BY_SAMPLE_KEY, new int[]{10, 10, 11, 11}).GQ(200).make())});
 
         tests.add(new Object[]{
-                new VariantContextBuilder(vcBase).alleles(ACG).genotypes(new GenotypeBuilder(base).alleles(AA).AD(hetCG3AllelesAD).PL(hetCG3AllelesPL).
```
Comment (ldgauthier) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: What was wrong with this test case?

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java (hunk 1 above)
Comment (davidbenjamin) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: done

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java (hunk 2 above)
Comment (davidbenjamin) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: done

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java (hunk 3 above)
Comment (davidbenjamin) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: done

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java (hunk 5 above)
Comment (davidbenjamin) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: Based on the ADs and PLs this case was supposed to be: triallelic (A,C,G) variant with het alt (C/G) genotype, subset to just the ref and one alt allele.  But that throws an error since the genotype has both alt alleles.  Previously no error was thrown because the genotype was accidentally set as hom ref, contradicting the ADs and PLs.  The test as intended was inherently impossible.

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java (hunk 4 above)
Comment (davidbenjamin) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: done and made the PLs more realistic

**Comment by davidbenjamin** [comment]
Ready for round 2 of review.

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java (hunk 5 above)
Comment (ldgauthier) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: Got it.  You can take it out entirely then.

Comment (davidbenjamin) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtilsUnitTest.java]: It's gone; the diff mixed-and-matched similar lines to give the appearance that part of this case remained.
