### PR TITLE
Fix CreateSequenceDictionary (issue #2093)

### LINKED ISSUE #2093: CreateSequenceDictionary generates a compress dict file that can't be used in other GATK tools
If I generate a sequence dictionary with the `CreateSequenceDictionary` tool with GATK4 command line (`./gatk-launch CreateSequenceDictionary -R reference.fasta -O reference.dict`), the generated dictionary is compressed (`cat` points out that is a binary file), and while using it in tools that calls `getReferenceDictionary()` with a provided reference the dictionary is null.

### PR DESCRIPTION
**Pull request by magicDGS**
Fix #2093: `CreateSequenceDictionary` now generates a plain-text dictionary as expected by tools that use it.

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionary.java [hunk 1]
```diff
@@ -83,7 +80,8 @@ protected Object doWork() {
         SAMFileWriter samWriter = null;
         //This writes the header with sequenceDictionary
         try {
-            samWriter = createSAMWriter(OUTPUT, REFERENCE_SEQUENCE, samHeader, false);
+            // do not use createSAMWriter because it does not create a plain text file without a .sam extension
+            samWriter = new SAMFileWriterFactory().makeSAMWriter(samHeader, false, OUTPUT);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionary.java]: Can you add a test proving that the original issue is fixed?

Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionary.java]: There's an existing test called `CreateSequenceDictionaryIntegrationTest.testBasic()` but it's grossly deficient and doesn't actually assert anything other than that it doesn't crash.  If you could update that to check that it produced the expected sequence dictionary that would be great.

Comment (magicDGS) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/sam/CreateSequenceDictionary.java]: It's what I'm doing! Commit in one minute!

**Comment by magicDGS** [comment]
Back to you with the added test, @droazen and/or @lbergelson! Thanks for having a look to this!

**Comment by lbergelson** [comment]
👍 Thanks for finding this issue and fixing it.
