### PR TITLE
fixing GATKReportUnitTest.testSortingByColumn

### LINKED ISSUE #1465: fix useless test in GATKReportUnitTest
The test `testSortingByColumn` doesn't actually test anything and likely never has. 

It throws and silently swallows an exception, which masks the fact that it's creating an empty table to test, and doesn't work when the table isn't empty.

This has been inherited unchanged from Gatk3.

### PR DESCRIPTION
**Pull request by lbergelson**
fixing a bogus test that never worked (fixes #1465)
changing functions that generate simple GATKReports to require a sort order
renaming GATKReportTable.TableSortingWay -> Sorting

not directly to master this time...

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/utils/report/GATKReportTable.java [hunk 1]
```diff
@@ -151,17 +151,6 @@ public GATKReportTable(BufferedReader reader, GATKReportVersion version) {
...
-     * @param tableName        the name of the table
-     * @param tableDescription the description of the table
-     * @param numColumns       the number of columns in this table
-     */
-    public GATKReportTable(final String tableName, final String tableDescription, final int numColumns) {
-        this(tableName, tableDescription, numColumns, TableSortingWay.SORT_BY_ROW);
-    }
-
-    /**
      * Construct a new GATK report table with the specified name and description and whether to sort rows by the row ID.
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/report/GATKReportTable.java]: Recommend restoring this constructor so that `GATKReportTable` has a default sorting method.

File: src/test/java/org/broadinstitute/hellbender/utils/report/GATKReportUnitTest.java [hunk 2]
```diff
@@ -153,47 +134,43 @@ public void testSimpleGATKReport() {
...
-        } catch (IOException x) {
-            System.err.format("IOException: %s%n", x);
+        File file = createTempFile("GATKReportGatherer-UnitTest", ".tbl");
+        //System.out.format("The temporary file" + " has been created: %s%n", file);
+        try (PrintStream ps = new PrintStream(file)) {
+            report.print(ps);
+            //System.out.println("File successfully outputted!");
+            GATKReport inputRead = new GATKReport(file);
+            //System.out.println("File successfully read!");
+            //inputRead.print(System.out);
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/report/GATKReportUnitTest.java]: Remove commented-out code

File: src/test/java/org/broadinstitute/hellbender/utils/report/GATKReportUnitTest.java [hunk 3]
```diff
@@ -227,20 +204,18 @@ public void testGATKReportGatherer() {
...
-            System.err.format("IOException: %s%n", x);
+
+        File file = createTempFile("GATKReportGatherer-UnitTest", ".tbl");
+        //System.out.format("The temporary file" + " has been created: %s%n", file);
+        try (final PrintStream ps = new PrintStream(file)) {
+            report1.print(ps);
+            //System.out.println("File successfully outputted!");
+            GATKReport inputRead = new GATKReport(file);
+            //System.out.println("File successfully read!");
+            //inputRead.print(System.out);
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/report/GATKReportUnitTest.java]: Remove commented-out code

**Comment by droazen** [comment]
:+1: merge after addressing comments
