### PR TITLE
Don't output VCs with no ALT if * gets dropped

### LINKED ISSUE #5650: HaplotypeCaller outputting variants with an ALT of .
### Affected tool(s) or class(es)
GATK Haplotype caller

### Affected version(s)
- [x] Latest public release version [4.1.0.0]
- [ ] Latest master branch as of [date of test?]

The Genome Analysis Toolkit (GATK) v4.1.0.0
HTSJDK Version: 2.18.2
Picard Version: 2.18.25

### Description 
HaplotypeCaller is outputting variants which have a no-call as the ALT, which breaks a bunch of downstream tools, this is new behavior in 4.1, AFAICT.

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	s1564	s1741	s1851	s1852	s1862	s1901	s1912	s1971	s2017	s2021	s2026	s2056	s2100	s2102	s2104	s2122	s2124	s2151	s2157
1	937796	.	T	.	179.65	.	AN=38;DP=31;MMQ=60;MQ=60.00	GT:AD:DP	0/0:0:0	0/0:0:0	0/0:4:4	0/0:0:0	0/0:1:1	0/0:1:1	0/0:0:0	0/0:0:0	0/0:2:2	0/0:0:0	0/0:1:1	0/0:3:3	0/0:1:1	0/0:8:8	0/0:1:1	0/0:0:0	0/0:2:2	0/0:7:7	0/0:0:0
```

#### Steps to reproduce
I'm not doing anything special, so I suspect these variants should exist in other projects as well. I'm doing batch calling on several samples simultaneously; an example:

```
unset JAVA_HOME && export PATH=/home/rdk4/local/share/bcbio/anaconda/bin:$PATH && gatk --java-options '-Xms4g -Xmx5000m -XX:+UseSerialGC -Djava.io.tmpdir=/n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/bcbiotx/tmpTSg0hJ' HaplotypeCaller -R /n/app/bcbio/dev/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2017/s2017-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2056/s2056-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2122/s2122-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1741/s1741-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2124/s2124-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1862/s1862-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1971/s1971-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1851/s1851-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1564/s1564-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2104/s2104-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1852/s1852-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1912/s1912-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2100/s2100-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2157/s2157-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2151/s2151-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s1901/s1901-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2026/s2026-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2102/s2102-sort.bam -I /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/align/s2021/s2021-sort.bam -L /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/gatk-haplotype/Y/tau-Y_0_58820452-regions.bed --interval-set-rule INTERSECTION --disable-read-filter NotDuplicateReadFilter --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 -ploidy 1 --output /n/data1/cores/bcbio/PIs/rudy_tanzi/tau-exome/tau-variants/work/bcbiotx/tmpTSg0hJ/tau-Y_0_58820452.vcf.gz
```

#### Expected behavior
These no-call of an ALT allele variants to be dropped.

#### Actual behavior
They are still included.

If this is expected behavior going forward, though, that would be good to know and we can remove these after calling. Thanks!

### PR DESCRIPTION
**Pull request by ldgauthier**
With the new qual model as the default for HC as of 4.1, occasionally sites get output with a . ALT when the * allele gets dropped.  Expected behavior is no output at that site in the VC.

Also limit logging for DepthPerSampleHC annotation.

Note that the expected behavior in one of the existing tests was also wrong and had to be fixed.

Fixes #5650

### CODE REVIEW

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java [hunk 1]
```diff
@@ -660,6 +661,11 @@ public void testFilterMitochondria() throws Exception {
         }
     }
 
+    @Test
+    public void testFilterMitochondriaGVCFs() throws Exception {
+
```
Comment (davidbenjamin) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java]: This test is empty.

Comment (ldgauthier) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java]: Ugh, I am the worst at stashing commits.  That should be on a different branch.

Comment (davidbenjamin) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java]: In that case, :thumbsup:.

Comment (ldgauthier) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java]: Now three changed files!  I will merge when tests pass.

**Comment by droazen** [comment]
As discussed in person with @ldgauthier and @davidbenjamin, the final merged version of this PR didn't contain the actual bug fix (just the test).
