### PR TITLE
Fix several issues with M2 and HC force-calling mode

### LINKED ISSUE #5857: Improve force-calling / GGA mode
In Mutect2 and HaplotypeCaller, we force-call alleles by injecting them into the ref haplotype, then threading these constructed haplotypes into the assembly graph with a large edge weight.  There are several drawbacks to this approach:

* The strange edge weights interfere with the `AdaptiveChainPruner`.
* The large edge weights may not be large enough to avoid pruning when depth is extremely high.
* The alleles may be lost if assembly fails.
* If the alleles actually exist but are in phase with another variant we end up putting an enormous amount of weight on a false haplotype.

We can get around these issue with the following method:

* assemble haplotypes without regard to the force-called alleles.
* if an allele is present in these haplotypes, do nothing further.
* otherwise, add a haplotype in which the allele is injected into the reference haplotype.

@LeeTL1220 I prototyped this and it seems to resolve the missed forced alleles that Ziao found.

@ldgauthier Can you think of any objections to making this change in HaplotypeCaller?

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #5857.

@ldgauthier Here it is, with the 5-haplotype compromise

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java [hunk 1]
```diff
@@ -305,6 +307,57 @@ public static AssemblyResultSet assembleReads(final AssemblyRegion region,
...
+            // choose the highest-scoring haplotypes along with the reference for building force-calling haplotypes
+            final List<Haplotype> baseHaplotypes = unassembledGivenAlleles.isEmpty() ? Collections.emptyList() : assembledHaplotypes.stream()
+                    .sorted(Comparator.comparingInt((Haplotype hap) -> hap.isReference() ? 1 : 0).thenComparingDouble(hap -> hap.getScore()).reversed())
+                    .limit(NUM_HAPLOTYPES_TO_INJECT_FORCE_CALLING_ALLELES_INTO)
+                    .collect(Collectors.toList());
+
+            for (final Allele givenAllele : unassembledGivenAlleles) {
+                for (final Haplotype baseHaplotype : baseHaplotypes) {
+                    // make sure this allele doesn't collide with a variant on the haplotype
+                    if (baseHaplotype.getEventMap()!= null && baseHaplotype.getEventMap().getVariantContexts().stream().anyMatch(vc -> vc.overlaps(givenVC))) {
```
Comment (ldgauthier) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java]: So if the GGA allele is a SNP that is spanned by a deletion in the discovered variants the it's only added to the reference haplotype, right?  And it will still get output in the vcf?

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyResultSet.java [hunk 2]
```diff
@@ -510,14 +512,24 @@ private void updateReferenceHaplotype(final Haplotype newHaplotype) {
      */
     public SortedSet<VariantContext> getVariationEvents(final int maxMnpDistance) {
         ParamUtils.isPositiveOrZero(maxMnpDistance, "maxMnpDistance may not be negative.");
-        if (variationEvents == null) {
-            final List<Haplotype> haplotypeList = getHaplotypeList();
-            EventMap.buildEventMapsForHaplotypes(haplotypeList, fullReferenceWithPadding, paddedReferenceLoc, debug, maxMnpDistance);
-            variationEvents = EventMap.getAllVariantContexts(haplotypeList);
+
+        final boolean sameMnpDistance = lastMaxMnpDistanceUsed.isPresent() && maxMnpDistance == lastMaxMnpDistanceUsed.getAsInt();
```
Comment (ldgauthier) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyResultSet.java]: How would the MNP distance change within the same tool execution?

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java [hunk 3]
```diff
@@ -542,9 +542,6 @@ public ActivityProfileState isActive( final AlignmentContext context, final Refe
         final AssemblyResultSet untrimmedAssemblyResult =  AssemblyBasedCallerUtils.assembleReads(region, givenAlleles, hcArgs, readsHeader, samplesList, logger, referenceReader, assemblyEngine, aligner, !hcArgs.doNotCorrectOverlappingBaseQualities);
         
         final SortedSet<VariantContext> allVariationEvents = untrimmedAssemblyResult.getVariationEvents(hcArgs.maxMnpDistance);
-        // TODO - line bellow might be unnecessary : it might be that assemblyResult will always have those alleles anyway
-        // TODO - so check and remove if that is the case:
```
Comment (ldgauthier) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java]: It feels so good to finally take care of that TODO that's been around for longer than I have.

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java [hunk 4]
```diff
@@ -94,20 +93,18 @@ public ReadThreadingAssembler(final int maxAllowedPathsForReadThreadingAssembler
...
     /**
      * Main entry point into the assembly engine. Build a set of deBruijn graphs out of the provided reference sequence and list of reads
-     * @param aligner
      * @param assemblyRegion              AssemblyRegion object holding the reads which are to be used during assembly
      * @param refHaplotype              reference haplotype object
      * @param fullReferenceWithPadding  byte array holding the reference sequence with padding
      * @param refLoc                    GenomeLoc object corresponding to the reference sequence with padding
-     * @param givenAlleles   the alleles to inject into the haplotypes during GGA mode
      * @param readErrorCorrector        a ReadErrorCorrector object, if read are to be corrected before assembly. Can be null if no error corrector is to be used.
+     * @param aligner
```
Comment (ldgauthier) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java]: If you're going to modify the java doc anyway, can you add a blurb for the aligner?

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java [hunk 5]
```diff
@@ -371,18 +334,18 @@ private static void addResult(final Collection<AssemblyResult> results, final As
      * Given reads and a reference haplotype give us graphs to use for constructing
      * non-reference haplotypes.
      *
-     * @param aligner
      * @param reads the reads we're going to assemble
      * @param refHaplotype the reference haplotype
+     * @param aligner
```
Comment (ldgauthier) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java]: java doc update please

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java [hunk 6]
```diff
@@ -408,19 +371,17 @@ private static int arrayMaxInt(final List<Integer> array) {
...
      * Creates the sequence graph for the given kmerSize
      *
-     * @param aligner
      * @param reads            reads to use
      * @param refHaplotype     reference haplotype
      * @param kmerSize         kmer size
-     * @param activeAlleleHaplotypes the GGA haplotypes to inject into the graph
      * @param allowLowComplexityGraphs if true, do not check for low-complexity graphs
      * @param allowNonUniqueKmersInRef if true, do not fail if the reference has non-unique kmers
+     * @param aligner
```
Comment (ldgauthier) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java]: ditto

File: src/main/java/org/broadinstitute/hellbender/utils/haplotype/EventMap.java [hunk 7]
```diff
@@ -61,7 +61,7 @@ public EventMap(final Collection<VariantContext> stateForTesting) {
     /**
      *
      * @param maxMnpDistance Phased substitutions separated by this distance or less are merged into MNPs.  More than
-     *                       two substitutions occuring in the same alignment block (ie the same M/X/EQ CIGAR element)
+     *                       two substitutions occurring in the same alignment block (ie the same M/X/EQ CIGAR element)
```
Comment (ldgauthier) [inline src/main/java/org/broadinstitute/hellbender/utils/haplotype/EventMap.java]: Thanks!

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java [hunk 8]
```diff
@@ -464,6 +464,33 @@ public void testGivenAllelesMode() throws Exception {
         }
     }
 
+    /**
+     * Here we give Mutect2 ridiculous kmer settings in order to force assembly to fail.
```
Comment (ldgauthier) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java]: This was where the previous behavior was an infinite loop?

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtilsUnitTest.java [hunk 9]
```diff
@@ -967,4 +968,81 @@ public void testCreateHaplotypeMapping(final VariantContext vc, final Set<Haplot
...
+        // add another SNP
+        final VariantContext givenVC2 = new VariantContextBuilder("test", "chr", 5, 5,
+                Arrays.asList(Allele.create((byte) 'C', true), Allele.create((byte) 'G', false))).make();
+        AssemblyBasedCallerUtils.addGivenHaplotypes(assemblyRegionStart, Collections.singletonList(givenVC2), maxMnpDistance,
+                aligner, refHaplotype, assemblyResultSet);
+        // SNP is not found in existing variation, so it's added to the ref and the first SNP
+        Assert.assertEquals(assemblyResultSet.getHaplotypeCount(), 4);
+        Assert.assertEquals(assemblyResultSet.getHaplotypeList().get(2).getBaseString(), "AAAAGCCCGGGGTTTT");
+        Assert.assertEquals(assemblyResultSet.getHaplotypeList().get(3).getBaseString(), "ACAAGCCCGGGGTTTT");
+
```
Comment (ldgauthier) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtilsUnitTest.java]: It looks like your code should handle multi-allelic input alleles, but can you add a test please?

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java (hunk 1 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtils.java]: Yes and yes.

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyResultSet.java (hunk 2 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyResultSet.java]: It shouldn't ever change, but I lean toward keeping the logic self-consistent without assuming anything about the tools that invoke it.  Of course, some of these classes are so entwined with HC and M2 that it's safe to assume things, but in this case the price of caution is small.

Also, the code for exactly when event maps are cached was quite brittle in that you could write reasonable code and encounter gotchas, so I felt like making it all more explicit as to what had and had not been computed previously.

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java (hunk 4 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java]: done

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java (hunk 5 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java]: done

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java (hunk 6 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java]: done

File: src/main/java/org/broadinstitute/hellbender/utils/haplotype/EventMap.java (hunk 7 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/haplotype/EventMap.java]: Boy Scout Rule

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java (hunk 8 above)
Comment (davidbenjamin) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java]: Previous behavior was: assembly fails, therefore GGA alleles are injected in vain and don't get genotyped.  Assembly still fails now, but we then inject the GGA alleles into the reference without using a graph.

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtilsUnitTest.java (hunk 9 above)
Comment (davidbenjamin) [reply src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtilsUnitTest.java]: done
