### PR TITLE
Added in regression tests and fixes for correctness of many annotations

### LINKED ISSUE #4344: Funcotator - Add regression test against known output (truth set)
Funcotator needs more complete integration tests.  These tests should better verify that the produced results are correct.

### LINKED ISSUE #5295: Funcotator needs test coverage for "all transcripts" mode
There's currently no test coverage for "all transcripts" mode in Funcotator, as far as I can discover, and the GTF files used for MUC16/PIK3CA tests don't even have multiple transcripts.

### PR DESCRIPTION
**Pull request by jonn-smith**
MASSIVE bug fixes and test updates. (Rebased 61 commits).

- Fixed a bug when variants overlap the end of transcripts.

- Updated logging in FuncotatorUtils::getAlignedRefAllele.

- Fixed a bug in identifying splice sites for intronic regions.

- Fixed a bug in FuncotatorUtils::isIndelBetweenCodons that caused issues
on reverse stranded variants.

- Added in regression test data input files and expected files.
- Updated regression test sets to include only unique variants.
- Added in a 5' flank and a Start Codon insertion to regression test set.

- Fixed a bug in FuncotatorUtils::isIndelBetweenCodons

- Finally fixed a bug with indels and start codons:
Now indels in start codons will not have protein renderings, nor will
they have codon change strings.  This brings Funcotator closer to
Oncotator functionality (in Oncotator, start codon insertions/deletions
    do not have protein change strings or codon change strings).

- Fixed a bug in ordering transcripts by appris ranking.

- Fixed a minor bug in how other transcripts are generated:.
With RNA/LINCRNA transcripts, the protein change would be null and was
append ed to the end of each `other transcript`.  Now the null is no
longer appended.

- Fixed a bug in insertions on the - strand:
All insertions on - strand had incorrectly rendered genome changes,
    coding sequence changes, and protein changes.
    This is due to how these fields are generated from the reference
    sequence.

- Fixed a bug (insertions on - strand):
Insertions on the - strand would have incorrect reference
sequences/alleles.
Now they are handled as a special case when computing the aligned
reference allele.

- Fixed a bug in transcript selection for GencodeFuncotationFactory:
The LocusLevel / Curation Level was being incorrectly pulled from the
GENE features, rather than the TRANSCRIPT features that contain each
variant.  As a result, the order in which representative transcripts
were chosen was wrong.  The TRANSCRIPT feature is now being used to
determine the Locus/Curation Level.

- `TranscriptType` now determined by transcript annotation, not gene annotation
- Start/stop codon overlapping now corrected for preceding indel bases (is now correct for more cases).
- Changed algorithm for how 5'UTRs are determined.

- Refactored how frameshift indels have codon change strings created.

- Added in helper some scripts for testing funcotator.

- Fixed how codon change strings are rendered to be consistent and more
correct.

- Fixed Protein Change strings to be consistent and more
correct.

- Implemented tests for CreateProteinChangeInfo
- Implemented tests for RenderProteinChangeString
- Implemented tests for IsIndelBetweenCodons
- Implemented tests for GetCodonChangeString

- Added a unit test for
testCreateGencodeFuncotationBuilderWithTrivialFieldsPopulated.

- Fixed a bug when variant ref allele doesn't match reference genome.

- Fixed test cases for - strand indel cdna strings:
There is a bug in oncotator that was fixed in Funcotator involving cdna
strings for - strand indels.  In Oncotator the positions reported are off by 1 (they
    should be one less) and the base reported is also wrong.
This is now fixed.

- Removed some old code that had been taken out of the main codepath.

- Fixed a bug in how the gencode reference contexts are created.
- Fixed a bug in how the end points for the gencode annotations are
created.

- Ref context field is now consistent for indels.
The reference context will give WINDOW bases before and after the
logical reference allele for a variant.  This is NOT the allele in the
input VCF, but rather the allele that actually has changed.  For
insertions, the logical allele is the SPACE BETWEEN TWO BASES (and
    therefore the resulting string will always be 2xWINDOW bases long).
For deletions, the logical allele is the given ref allele without the
required preceding base.  For MNPs the logical allele is the given ref
allele.
Updated some tests and test data to reflect this change.

- Added a small HG38 regression test set.

- Fixed a boundary bug with codon strings.
Now codon change strings have an alternate (correct) form for insertions
that involve the start codon on the - strand, and the stop codon on the
+ strand.  This form eliminates any overrun/out of bounds exceptions.

- Fixed an issue involving variants that overrun the end of the coding sequence.

- Added in additional required files for regression test gencode data source.

- Added a helpful script and modified test data set to be correct.

- Updated part of Gencode to prepare for fixing the exon boundary issue.

- Updated FuncotatorIntegrationTests to use environment-variable paths
more safely.

- Updated `FuncotatorUtils::getCodingSequenceChangeString` to use
base data types rather than those in `SequenceComparison`.

- Refactored
`GencodeFuncotationFactory::createCodingRegionFuncotationForNonProteinCodingFeature`
to remove the use of `SequenceComparison` objects.

- Updated test suite to use full, checked-in references.

- Updated many tests to use regression test data sources rather than small data
sources specifically for PIK3CA and MUC16.

- Removed some now unused data files (primarily old data sources).

- Updated regression tests to work on local data sources and references.

- Now `FuncotatorIntegrationTest::regressionTest` works on local, checked-out copies of the data sources so that
they can be run from any checkout.

- Fixes #4344 
- Fixes #5295

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 1]
```diff
@@ -1591,21 +1594,44 @@ static SequenceComparison createSequenceComparison(final VariantContext variant,
...
+                        transcriptTailPaddingBaseString
+                );
+
+                // Now that we have our transcript sequence, we must make sure that our reference allele is in it
+                // correctly.
+                // This is because if the user specifies a ref allele that is NOT the same as what is in the reference,
+                // their specified allele takes precedence and overrides the allele from the reference genome.
+                final String correctedCodingSequence;
 
+                // We can't yet handle sequences that overrun the end of the coding sequence (Issue #):
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Issue #?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 2]
```diff
@@ -1619,33 +1645,30 @@ static SequenceComparison createSequenceComparison(final VariantContext variant,
...
-                // Set our alternate amino acid sequence:
-                // We only need to do this if we don't have a frame-shift:
-                sequenceComparison.setAlternateAminoAcidSequence(
-                        FuncotatorUtils.createAminoAcidSequence(
-                                sequenceComparison.getAlignedCodingSequenceAlternateAllele(),
-                                GATKVariantContextUtils.isFrameshift(refAllele, altAllele)
-                        )
-                );
+                // ########################################################################################
+                // FIX THE PROTEIN STUFF HERE:
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Fix -> Render?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 3]
```diff
@@ -1657,6 +1680,48 @@ static SequenceComparison createSequenceComparison(final VariantContext variant,
         return sequenceComparison;
     }
 
+    private static String getTranscriptEndPaddingBases(final VariantContext variant,
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Might want unit tests for this method

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/vcfOutput/VcfOutputRenderer.java [hunk 4]
```diff
@@ -258,9 +258,8 @@ else if ( refAlleleLength > altAlleleLength ) {
                 //    Increment the End_Position by M-1 where M = length(ref_allele) (end position should be inclusive of the last base deleted)
                 outFuncotation.setRefAllele(gencodeFuncotation.getRefAllele().substring(altAlleleLength));
                 outFuncotation.setTumorSeqAllele2("-");
-//                outputMap.put(MafOutputRendererConstants.FieldName_Tumor_Seq_Allele2, MafOutputRendererConstants.EmptyAllele);
                 outFuncotation.setStart(gencodeFuncotation.getStart() + 1);
-                outFuncotation.setEnd(gencodeFuncotation.getEnd() + refAlleleLength - 1);
+                outFuncotation.setEnd(gencodeFuncotation.getStart() + refAlleleLength - 1);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/vcfOutput/VcfOutputRenderer.java]: Here's another example of using the ref allele length for the extend of a funcotation, which suggests to me that use of the alt allele length above is possibly a mistake.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotationMapUnitTest.java [hunk 5]
```diff
@@ -46,14 +43,7 @@
 
 public class FuncotationMapUnitTest extends BaseTest{
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotationMapUnitTest.java]: `GATKBaseTest`

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotationMapUnitTest.java [hunk 6]
```diff
@@ -46,14 +43,7 @@
...
-    private static final String DS_PIK3CA_HG19_GENCODE_GTF = DS_PIK3CA_DIR + "gencode_pik3ca/hg19/gencode.v19.PIK3CA.gtf";
-    private static final String DS_MUC16_DIR = GATKBaseTest.largeFileTestDir + "funcotator/small_ds_muc16/";
-    private static final String DS_MUC16_HG19_GENCODE_FASTA = DS_MUC16_DIR + "gencode_muc16/hg19/gencode.v19.MUC16_transcript.fasta";
-    private static final String DS_MUC16_HG19_GENCODE_GTF = DS_MUC16_DIR + "gencode_muc16/hg19/gencode.v19.MUC16.gtf";
-    private static final FeatureReader<GencodeGtfFeature> pik3caFeatureReader = AbstractFeatureReader.getFeatureReader( FuncotatorTestConstants.PIK3CA_GENCODE_ANNOTATIONS_FILE_NAME, new GencodeGtfCodec() );
-    private static final FeatureReader<GencodeGtfFeature> muc16FeatureReader = AbstractFeatureReader.getFeatureReader(FuncotatorTestConstants.MUC16_GENCODE_ANNOTATIONS_FILE_NAME, new GencodeGtfCodec() );
+    private static final FeatureReader<GencodeGtfFeature> gencodeFeatureReader = AbstractFeatureReader.getFeatureReader( FuncotatorTestConstants.GENCODE_DATA_SOURCE_GTF_PATH_HG19, new GencodeGtfCodec() );
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotationMapUnitTest.java]: Do you ever close your readers? Could use TestNG `@AfterClass`

Also, it's better to create readers within test methods themselves and avoid global state in tests, but you don't have to address that in this PR.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 7]
```diff
@@ -69,8 +70,9 @@
     private static final String MUC16_VCF_HG19           = toolsTestDir + "funcotator" + File.separator + "MUC16_MNP.vcf";
     private static final String PIK3CA_VCF_HG19_ALTS     = toolsTestDir + "funcotator" + File.separator + "PIK3CA_3_miss_clinvar_alt_only.vcf";
     private static final String SPANNING_DEL_VCF         = toolsTestDir + "funcotator" + File.separator + "spanning_del.vcf";
+
+    // TODO: Get rid of this variable and use the general data sources path:
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Is there a github issue for this TODO?

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 8]
```diff
@@ -91,7 +93,7 @@
     private static String hg19Chr19Ref;
 
     static {
-        if (!doDebugTests) {
+        if (!enableFullScaleTests ) {
             tmpOutDir = createTempDir("funcotatorTmpFolder");
         } else {
             tmpOutDir = new File("funcotatorTmpFolder" + File.separator);
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: If you intentionally don't want this deleted, add a comment to that effect.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 9]
```diff
@@ -117,44 +119,63 @@ private static File getOutputFile(final FuncotatorArgumentDefinitions.OutputForm
...
-        if (!doDebugTests) {
+        if (!enableFullScaleTests ) {
             outputFile = createTempFile(tmpOutDir + File.separator + outfileBaseName, "." + outFileExtension);
         } else {
             outputFile = new File(tmpOutDir, outfileBaseName + "." + outFileExtension);
         }
         return outputFile;
     }
 
+    private static List<String> getManualAnnotations() {
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Comment explaining what this List is

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 10]
```diff
@@ -204,6 +225,34 @@ private ArgumentsBuilder createBaselineArgumentsForFuncotator(final String varia
 
     //==================================================================================================================
 
+    @DataProvider
+    private Object[][] provideForNonTrivialLargeDataTest() {
+
+        return new Object[][] {
+                {
+                        FuncotatorTestConstants.REGRESSION_TEST_HG19_DATA_SET_1,
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Rename constants to match test case name

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 11]
```diff
@@ -376,7 +419,7 @@ private void validateFuncotationsOnVcf(final Iterable<VariantContext> vcfIterabl
         }
     }
 
-    @Test(enabled = doDebugTests,
+    @Test(enabled = enableFullScaleTests,
           groups = {"funcotatorValidation"},
           dataProvider = "provideForLargeDataValidationTest")
     public void largeDataValidationTest(final String inputVcfName,
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Rename to `fullScaleValidationTest`

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 12]
```diff
@@ -441,6 +484,52 @@ public void largeDataValidationTest(final String inputVcfName,
         System.out.println("Total Elapsed Time: " + (endTime - overallStartTime) / 1e9 + "s");
     }
 
+    @Test(dataProvider = "provideForNonTrivialLargeDataTest")
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Add a comment explaining how large the test is

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 13]
```diff
@@ -441,6 +484,52 @@ public void largeDataValidationTest(final String inputVcfName,
...
+                FuncotatorArgumentDefinitions.OutputFormatType.VCF,
+                true);
+
+        // Run the tool with our args:
+        long startTime = 0, endTime = 0;
+        startTime = System.nanoTime();
+        runCommandLine(arguments);
+        endTime = System.nanoTime();
+
+        System.out.println("  Elapsed Time: " + (endTime - startTime) / 1e9 + "s");
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Can you use the logger here?

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 14]
```diff
@@ -441,6 +484,52 @@ public void largeDataValidationTest(final String inputVcfName,
...
+
+        final File outputFile = createTempFile(tmpOutDir + File.separator + inputVcfName + ".funcotator", ".vcf");
+
+        final ArgumentsBuilder arguments = createBaselineArgumentsForFuncotator(
+                inputVcfName,
+                outputFile,
+                referencePath,
+                dataSourcesPath,
+                referenceVersion,
+                FuncotatorArgumentDefinitions.OutputFormatType.VCF,
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Might want to mirror each VCF test case here with a MAF output test, since this is the "main" integration test for Funcotator, and will likely be expanded over time.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 15]
```diff
@@ -530,6 +619,86 @@ public void testCanAnnotateMixedContigHg19Clinvar() {
                 .count(), NUM_CLINVAR_HITS, "Found unexpected number of ClinVar hits!");
     }
 
+    @Test
+    public void testManualAnnotationsCorrectness() {
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Add comment describing what this is testing.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 16]
```diff
@@ -817,14 +989,29 @@ else if ( annotationsToCheckMaf.get(i).equals(MafOutputRendererConstants.FieldNa
...
             }
-            Assert.assertEquals(mafFieldValues, vcfFieldValues, "Failed matching (VCF: " + annotationToCheckVcf + " , MAF: " + annotationToCheckMaf + ")");
+
+            // "Fuzzy" matching between VCF and MAF by allowing blank VCF fields to be Unknown in the MAF.
+            // This is a temporary hold-over until we can do full aliased comparisons of fields.
+            // TODO: Update with better comparison using aliases when they are fully implemented.
+            if ( !Objects.equals(mafFieldValues, vcfFieldValues) ) {
+                Assert.assertEquals(mafFieldValues.size(), vcfFieldValues.size());
+                mafFieldValues.stream().map( v -> {Assert.assertEquals(v, "Unknown"); return true;} );
+                vcfFieldValues.stream().map( v -> {Assert.assertEquals(v, ""); return true;} );
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Isn't this asserting that ALL of the vcf/maf field values must be Unknown/"", in the case where you don't have an exact match across all of the field values? This doesn't seem right...is this code actually getting run?

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java [hunk 17]
```diff
@@ -68,9 +70,24 @@
...
     public static final String PIK3CA_SNP_FILE_BASE_NAME   = FUNCOTATOR_TEST_DIR + "PIK3CA_SNPS";
     public static final String PIK3CA_INDEL_FILE_BASE_NAME = FUNCOTATOR_TEST_DIR + "PIK3CA_INDELS";
+
+    // ----------------------------------------------------------------------
+    // Regression Test Variables:
+
+    public static final String REGRESSION_TEST_HG19_DATA_SET_1 = FUNCOTATOR_LARGE_FILES_DIR + "regressionTestVariantSet1.vcf";
+    public static final String REGRESSION_TEST_HG19_DATA_SET_1_EXPECTED_OUTPUT = FUNCOTATOR_LARGE_FILES_DIR + "regressionTestVariantSet1_expected.vcf";
+
+    public static final String REGRESSION_TEST_HG19_DATA_SET_2 = FUNCOTATOR_LARGE_FILES_DIR + "regressionTestVariantSet2.vcf";
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java]: Can you document the provenance of "set1" vs. "set2", and mention any notable differences between them?

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java [hunk 18]
```diff
@@ -705,20 +785,389 @@ private void printReferenceBases(final Path refFile, final String contig, final
...
-                {"NY",  1,  2, "GN", "AATTAT", "GGTAAT", "p.1_2NY>GN"},
-                {"YY",  1,  2, "NY", "TATTAT", "AATTAT", "p.Y1N"},
-                {"NY",  1,  2, "NG", "AATTAT", "AATGGT", "p.Y2G"},
-
-                {"N",  71, 71,  "G", "AAT",    "GGT",    "p.N71G"},
-                {"NY", 71, 72, "GN", "AATTAT", "GGTAAT", "p.71_72NY>GN"},
-                {"YY", 71, 72, "NY", "TATTAT", "AATTAT", "p.Y71N"},
-                {"NY", 71, 72, "NG", "AATTAT", "AATGGT", "p.Y72G"},
+                // + Strand:
+                { 4,  4, "A",   Strand.POSITIVE, false },
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java]: Might want to document the meaning of the values in a comment here

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java [hunk 19]
```diff
@@ -789,63 +1238,67 @@ private void printReferenceBases(final Path refFile, final String contig, final
 //        final Allele refAllele,
 //        final int codingSequenceRefAlleleStart,
 //        final int alignedRefAlleleStart
+//        final Strand strand
 //        expected
 
+        // TODO: Make tests with Strand.NEGATIVE!!!!
+        // TODO: Make tests with alt allele longer/shorter than ref allele!
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java]: Are there github tickets for these TODOs?

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java [hunk 20]
```diff
@@ -63,16 +59,15 @@
 
     // Initialization of static variables:
     static {
-        muc16NonBasicFeatureReader = AbstractFeatureReader.getFeatureReader(FuncotatorTestConstants.MUC16_GENCODE_NON_BASIC_ANNOTATIONS_FILE_NAME, new GencodeGtfCodec() );
-        muc16FeatureReader = AbstractFeatureReader.getFeatureReader(FuncotatorTestConstants.MUC16_GENCODE_ANNOTATIONS_FILE_NAME, new GencodeGtfCodec() );
-        pik3caFeatureReader = AbstractFeatureReader.getFeatureReader( FuncotatorTestConstants.PIK3CA_GENCODE_ANNOTATIONS_FILE_NAME, new GencodeGtfCodec() );
-        refDataSourceHg19Ch19 = ReferenceDataSource.of( IOUtils.getPath(FuncotatorReferenceTestUtils.retrieveHg19Chr19Ref()) );
+        muc16NonBasicFeatureReader = AbstractFeatureReader.getFeatureReader(FuncotatorTestConstants.MUC16_GENCODE_NON_BASIC_ANNOTATIONS_FILE_NAME, new GencodeGtfCodec());
+        gencodeFeatureReader = AbstractFeatureReader.getFeatureReader(FuncotatorTestConstants.GENCODE_DATA_SOURCE_GTF_PATH_HG19, new GencodeGtfCodec());
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java]: Close these readers in `@AfterClass`

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java [hunk 21]
```diff
@@ -1396,6 +1380,43 @@ void testCreateFuncotations(final String expectedGeneName,
...
+                                                                       final Allele altAllele,
+                                                                       final GencodeGtfGeneFeature gtfFeature,
+                                                                       final GencodeGtfTranscriptFeature transcript ) {
+
+        final GencodeFuncotationBuilder builder =
+                GencodeFuncotationFactory.createGencodeFuncotationBuilderWithTrivialFieldsPopulated(variant, altAllele,
+                        gtfFeature, transcript);
+        final GencodeFuncotation gf = builder.gencodeFuncotation;
+
+        // Ultra-trivial checks:
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java]: Add assert that end of the funcotation is consistent with end of the VariantContext

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java [hunk 22]
```diff
@@ -11,54 +11,56 @@
...
     public static final String VARIANT_FILE_HG19_CHR19 = FUNCOTATOR_TEST_DIR + "snpTest_chr19_hg19.vcf";
 
     // ----------------------------------------------------------------------
     // Data source variables:
 
+    public static final String DUMMY_DATA_SOURCES_TAR_GZ             = FUNCOTATOR_LARGE_FILES_DIR + "dummyDataSources.tar.gz";
+    public static final String DUMMY_DATA_SOURCES_TAR_GZ_SHA256_FILE = FUNCOTATOR_LARGE_FILES_DIR + "dummyDataSources.sha256";
+    public static final String DUMMY_DATA_SOURCES_FOLDER             = FUNCOTATOR_LARGE_FILES_DIR + "dummyDataSources";
+
+    public static final String FUNCOTATOR_DATA_SOURCES_MAIN_FOLDER = FUNCOTATOR_LARGE_FILES_DIR + "funcotator_dataSources" + File.separator;
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java]: Should this (and related declarations below) be moved to the top of the class, with a comment explaining what it contains (since we should be using this for most of our future tests, right?)

File: scripts/funcotator/testing/compareTwoReferenceDictionaries.sh [hunk 23]
```diff
@@ -0,0 +1,145 @@
+#!/bin/bash
+
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply scripts/funcotator/testing/compareTwoReferenceDictionaries.sh]: Fixed!

File: scripts/funcotator/testing/compareTwoReferenceDictionaries.sh [hunk 24]
```diff
@@ -0,0 +1,145 @@
+#!/bin/bash
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply scripts/funcotator/testing/compareTwoReferenceDictionaries.sh]: Created issue #5345

File: scripts/funcotator/testing/compareTwoReferenceDictionaries.sh [hunk 25]
```diff
@@ -0,0 +1,145 @@
...
+
+#Setup variables for the script:
+SCRIPTDIR="$( cd -P "$( dirname "$0" )" && pwd )"
+SCRIPTNAME=$( echo $0 | sed 's#.*/##g' )
+MINARGS=0
+MAXARGS=0
+
+################################################################################
+
+D="/Users/jonn/Development/references"
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply scripts/funcotator/testing/compareTwoReferenceDictionaries.sh]: Yes.  My primary goal in checking in scripts was to ensure they do not get lost when my computer inevitably self-destructs.

I have commented them and if others wish to use them, they can modify them to have paths to their references.  In the future we can update the scripts to be more user-friendly / configurable.

I have opened ticket #5346

File: scripts/funcotator/testing/makeComparisonForOncotator.sh [hunk 26]
```diff
@@ -0,0 +1,100 @@
+#!/usr/bin/env bash
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply scripts/funcotator/testing/makeComparisonForOncotator.sh]: Yes.  Checked in!

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 27]
```diff
@@ -51,7 +51,8 @@
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Regenerating the primary files is pretty straight-forward.

Fixed!

File: scripts/funcotator/testing/testFuncotator.sh [hunk 28]
```diff
@@ -0,0 +1,134 @@
...
+	r=$?
+else
+	./gradlew compileJava compileTestJava installDist
+	r=$?
+fi 
+
+if [[ $r -eq 0 ]] && ${doUnitTests} ; then
+	echo "################################################################################"
+	echo "## Running Unit Tests... "
+	./gradlew test --tests org.broadinstitute.hellbender.tools.funcotator* --stacktrace
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply scripts/funcotator/testing/testFuncotator.sh]: Yes.

File: scripts/funcotator/testing/testFuncotator.sh [hunk 29]
```diff
@@ -0,0 +1,134 @@
...
+
+doClean=false
+
+REF_VER=hg19
+OUT_FORMAT=VCF
+useAOUDataSources=false
+
+DATA_SOURCES_PATH=/Users/jonn/Development/funcotator_dataSources_latest
+HG19=/Users/jonn/Development/references/Homo_sapiens_assembly19.fasta
+HG38=/Users/jonn/Development/references/Homo_sapiens_assembly38.fasta
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply scripts/funcotator/testing/testFuncotator.sh]: Added a `manual mode` to allow a user to run it.  Also added a lot more documentation.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 30]
```diff
@@ -342,6 +339,23 @@ public void apply(final VariantContext variant, final ReadsContext readsContext,
...
+            logger.warn("\u001B[43m     _  _  _   __        __               _                   _  _  _           ");
+            logger.warn("    | || || |  \\ \\      / /_ _ _ __ _ __ (_)_ __   __ _      | || || |        ");
+            logger.warn("    | || || |   \\ \\ /\\ / / _` | '__| '_ \\| | '_ \\ / _` |     | || || |     ");
+            logger.warn("    |_||_||_|    \\ \\V V / (_| | |  | | | | | | | | (_| |     |_||_||_|        ");
+            logger.warn("    (_)(_)(_)     \\_/\\_/ \\__,_|_|  |_| |_|_|_| |_|\\__, |     (_)(_)(_)      ");
+            logger.warn("                                                  |___/                         \u001B[0;0m");
+            logger.warn("--------------------------------------------------------------------------------");
+            logger.warn(" Only IGRs were produced for this dataset.  This STRONGLY indicates that this   ");
+            logger.warn(" run was misconfigured.     ");
+            logger.warn(" You MUST check your data sources to make sure they are correct for these data.");
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: The mismatch is not between the VCF and reference dictionary, but between the reference dictionary and the data sources dictionary.  This is a by-product of allowing fuzzy-matching between `B37` and `HG19` references (which is very clear at this point was a mistake).

I've added an issue (#5347) to fix the data sources for `B37` and `HG19` so that we can have dedicated data sources for each reference.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngine.java [hunk 31]
```diff
@@ -69,6 +69,12 @@
      */
     private final boolean mustConvertInputContigsToHg19;
 
+    /**
+     * Whether this {@link FuncotatorEngine} has only produced annotations on variants that have been labeled by the
+     * {@link org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory} as {@link org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotation.VariantClassification#IGR}.
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorEngine.java]: No.  A Gencode data source is currently required for Funcotator to run.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 32]
```diff
@@ -313,9 +313,9 @@ else if ( secondAlleleBase != firstAlleleBase ) {
      * @param strand The strand on which the transcript is read.    Must not be {@code null}.  Must not be {@link Strand#NONE}.
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: I reverted the name of the method - it does, in fact, get the position in the transcript (not the coding sequence).

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 33]
```diff
@@ -408,6 +408,7 @@ public static boolean isInFrameWithEndOfRegion(final int startPosition, final in
         // Micro-optimization to split the return statements based on
         // the if statement so we don't have to do unnecessary math in the "normal" case:
         if ( startPosition > 0 ) {
+            // Add 1 because of the 1-based/inclusive positions:
             return (((regionLength - startPosition + 1) % 3) == 0);
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 34]
```diff
@@ -479,143 +514,242 @@ private static String createCapitalizedAlternateAlleleInsertionCodonChangeString
...
+        Utils.nonNull(seqComp.getCodingSequenceAlleleStart());
+        assertValidStrand(seqComp.getStrand());
+
+        // WHY would seqComp.getAlignedCodingSequenceReferenceAllele() == seqComp.getAlignedCodingSequenceAlternateAllele() here?
+        // see 1:1152971 T>C for details
 
         // ONP:
-        if ( GATKVariantContextUtils.isXnp(seqComp.getAlignedReferenceAllele(), seqComp.getAlignedAlternateAllele()) ) {
+        if ( GATKVariantContextUtils.isXnp(seqComp.getAlignedCodingSequenceReferenceAllele(), seqComp.getAlignedCodingSequenceAlternateAllele()) ) {
+//        if ( seqComp.getAlignedCodingSequenceReferenceAllele().length() == seqComp.getAlignedCodingSequenceAlternateAllele().length() ) {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 35]
```diff
@@ -479,143 +514,242 @@ private static String createCapitalizedAlternateAlleleInsertionCodonChangeString
...
+                //
+                if ( ((seqComp.getCodingSequenceAlleleStart() % 3) == 0) ) {
+                    // If we're an insertion and we start at the begining of a codon, we have to adjust for
+                    // the preceding base in the input VCF.  This means we have to skip the first or last 3 bases in the aligned
+                    // codon, because we have included them to grab the aligned data for the preceding base.
+                    // Note: This is not the aligned coding sequence position, but the raw coding sequence position:
+                    if ( isInsertion ) {
+                        if ( seqComp.getStrand() == Strand.POSITIVE ) {
+                            // Skip the first 3 bases in the aligned codon:
+                            alignedCodonStart += 3;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: This is something I've thought about for a long time.

Adding in `AminoAcid.CODON_LENGTH`.

Done!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 36]
```diff
@@ -479,143 +514,242 @@ private static String createCapitalizedAlternateAlleleInsertionCodonChangeString
...
-                    if ( isIndelBetweenCodons(seqComp.getCodingSequenceAlleleStart(), seqComp.getAlignedCodingSequenceAlleleStart(), seqComp.getReferenceAllele()) ) {
-                        final String nextRefCodon = getNextReferenceCodon(seqComp.getTranscriptCodingSequence(), seqComp.getAlignedCodingSequenceAlleleStart(), seqComp.getAlignedReferenceAlleleStop(), seqComp.getStrand());
 
-                        // Here we adjust everything "right" by 3 bases (1 codon) because of the leading base that is
-                        // required for indels:
-                        return "c.(" + (seqComp.getAlignedCodingSequenceAlleleStart() + 3) + "-" + (seqComp.getAlignedCodingSequenceAlleleStart() + 5) + ")" +
-                                nextRefCodon.toLowerCase() + ">" + seqComp.getAlignedAlternateAllele().substring(3) + nextRefCodon.toLowerCase();
-                    }
-                    else {
+                return "c.(" + alignedCodonStart + "-" + alignedCodonEnd + ")" +
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 37]
```diff
@@ -479,143 +514,242 @@ private static String createCapitalizedAlternateAlleleInsertionCodonChangeString
...
+                        refCodon + "fs";
+            }
+            else {
+                // Insertions:
+                if ( isInsertion ) {
+                    if ( indelIsBetweenCodons ) {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Sure.  Done.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 38]
```diff
@@ -676,43 +811,32 @@ private static String getNextReferenceCodon(final ReferenceSequence referenceSeq
...
-                    referenceSequence.getBaseString().substring(currentAlignedCodingSequenceAlleleStart - 3, currentAlignedCodingSequenceAlleleStart ).getBytes()
-            );
+            // Make sure we don't try to get bases before the start of our reference sequence:
+            if ( currentAlignedCodingSequenceAlleleStart == 1 ) {
+                nextRefCodon = "";
+            }
+            else {
+                // Subtract 1 because of 1-inclusive genomic positions
+                // Subtract 3 to get the "next" codon on the - strand:
+                nextRefCodon = referenceSequence.getBaseString().substring(currentAlignedCodingSequenceAlleleStart - 1 - 3, currentAlignedCodingSequenceAlleleStart - 1);
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Yes - at this point in the code `currentAlignedCodingSequenceAlleleStart - 1 - 3` is guaranteed to be `>= 4`.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 39]
```diff
@@ -657,17 +791,18 @@ private static String getCodonChangeStringForOnp( final String alignedRefAllele,
     }
 
     /**
-     * Gets the next complete in-frame codon from the given {@link ReferenceSequence} according to the current codon position and strand.
+     * Gets the next (+ strand) or previous (- strand) complete in-frame codon from the given {@link ReferenceSequence}
+     * according to the current codon position and strand.
      * @param referenceSequence The {@link ReferenceSequence} for the current codon.  Must not be {@code null}.
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 40]
```diff
@@ -777,487 +901,141 @@ public static String createSpliceSiteCodonChange(final int variantStart,
...
      * @return A {@link String} representing the codon change for the given {@link SequenceComparison}.
      */
-    public static String getProteinChangeString(final SequenceComparison seqComp) {
-
-        Utils.nonNull(seqComp);
-        Utils.nonNull(seqComp.getReferenceAminoAcidSequence());
-        Utils.nonNull(seqComp.getProteinChangeStartPosition());
-        Utils.nonNull(seqComp.getProteinChangeEndPosition());
-        Utils.nonNull(seqComp.getAlternateAminoAcidSequence());
+    public static String renderProteinChangeString(final SequenceComparison seqComp,
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: I like the idea of refactoring to make `ProteinChangeInfo` smarter, but since a lot of the data required are in the `SequenceComparison` object, I'm going to leave it as-is for now.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 41]
```diff
@@ -777,487 +901,141 @@ public static String createSpliceSiteCodonChange(final int variantStart,
...
-                    (refAaSeq.charAt(refAaSeq.length() - 1 - offset) == altAaSeq.charAt(altAaSeq.length()  - 1 - offset)) ) {
-                ++offset;
-            }
-
-            for ( int i = 0; i < (refAaSeq.length() - offset) ; ++i ) {
-                outRefAa.append( refAaSeq.charAt(i) );
+        else if (GATKVariantContextUtils.isDeletion( seqComp.getReferenceAllele(), seqComp.getAlternateAllele() )) {
+            //  In-Frame Deletion
+            if ( protChangeStartPos != protChangeEndPos ) {
+                return "p." + protChangeStartPos + '_' + protChangeEndPos + refAaSeq + ">" + altAaSeq;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 42]
```diff
@@ -1736,18 +1802,15 @@ private static GencodeFuncotationBuilder createGencodeFuncotationBuilderWithTriv
                  .setNcbiBuild(gtfFeature.getUcscGenomeVersion())
                  .setChromosome(gtfFeature.getChromosomeName())
                  .setStart(variant.getStart())
-                 .setGeneTranscriptType(gtfFeature.getTranscriptType());
+                 .setGeneTranscriptType(transcript.getTranscriptType());
 
          // The end position is inclusive, so we need to make sure we don't double-count the start position (so we subtract 1):
          gencodeFuncotationBuilder
                  .setEnd(variant.getStart() + altAllele.length() - 1)
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: It turns out the lengths were equivalent.  Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 43]
```diff
@@ -1511,47 +1294,57 @@ public static String getAlignedRefAllele(final String referenceSnippet,
...
-     * @param refAllele The reference {@link Allele} for the variant in question.  If on {@link Strand#NEGATIVE}, must have already been reverse complemented.  Must not be {@code null}.
-     * @param altAllele The alternate {@link Allele} for the variant in question.  If on {@link Strand#NEGATIVE}, must have already been reverse complemented.  Must not be {@code null}.
-     * @param strand The {@link Strand} on which the variant in question lives.  Must not be {@code null}.  Must not be {@link Strand#NONE}.
-     * @param referenceWindowInBases The number of bases to the left and right of the variant to return.  Must be > 0.
-     * @param referenceContext The {@link ReferenceContext} centered around the variant in question.  Must not be {@code null}.
-     * @return A string containing {@code referenceWindowInBases} bases to either side of the specified refAllele.
+     * @param refAllele The reference {@link Allele} for the variant.  Used
+     * @param altAllele The alternate {@link Allele} for the variant.
+     * @param reference The {@link ReferenceContext} for the variant, with the current window around the variant.
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Yes.  Fixed in documentation and added an assert.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 44]
```diff
@@ -2187,6 +1982,336 @@ public static boolean areAnyGencodeFuncotation(final List<Funcotation> funcotati
...
+     * @param codingSequenceAlleleStart The position (1-based, inclusive) in the _coding sequence_ at which the variant begins.  (NOTE: This is _not_ the same the genomic position, nor is it necessarily the same as the transcript position of the variant).
+     * @param alignedCodingSequenceAlleleStart The codon-aligned position (1-based, inclusive) in the _coding sequence_ at which the variant begins.  (NOTE: This is _not_ the same the genomic position, nor is it necessarily the same as the transcript position of the variant).
+     * @param codingSequence The strand-corrected (i.e. if on the - strand, it has been reverse-complemented) sequence of bases containing the _coding sequence_ for a particular transcript of a gene, from which we should render a protein change.  (NOTE: This is _not_ the same the gene sequence, nor is it necessarily the same as the whole transcript sequence).  Must not be {@code null}.
+     * @param strand The {@link Strand} on which the transcript for this protein change occurs.  Must not be {@link Strand#NONE}.  Must not be {@code null}.
+     * @return
+     */
+    public static ProteinChangeInfo createProteinChangeInfo(final Allele refAllele,
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Sure, I'll put it in there and break `ProteinChangeInfo` into it's own high-level class.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 45]
```diff
@@ -2187,6 +1982,336 @@ public static boolean areAnyGencodeFuncotation(final List<Funcotation> funcotati
...
+        Utils.nonNull(altAllele);
+        Utils.nonNull(codingSequence);
+        Utils.nonNull(strand);
+
+        // Cache whether it's a frameshift variant:
+        final boolean isFrameshift =  GATKVariantContextUtils.isFrameshift( refAllele, altAllele );
+
+        // Get our protein sequences:
+        final String referenceProteinSequence = FuncotatorUtils.createAminoAcidSequence(codingSequence, false, "(size=" + codingSequence.length() + ", ref allele: " + refAllele.getBaseString() + ")");
+        final String alternateProteinSequence = FuncotatorUtils.createAminoAcidSequence(
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Sure.  Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 46]
```diff
@@ -2187,6 +1982,336 @@ public static boolean areAnyGencodeFuncotation(final List<Funcotation> funcotati
...
+                // We should attempt to simplify it into a simple insertion.
+                // To do this we must detect the bases that have been inserted into the reference amino acid
+                // string.
+                // For this case, we check the first and last amino acids in the ref and alt strings to
+                // see if they match.  If so we remove that amino acid from the change string.
+                //
+                // Note this case is similar to the complementary deletion case.
+                // Note that we must attempte to alternate looking at the front and the back to get the proper
+                //      and correct protein change.
+                boolean frontMustBeTrimmed = (!refAaSeq.isEmpty()) && (!altAaSeq.isEmpty()) && (refAaSeq.charAt(0) == altAaSeq.charAt(0));
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Sure.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 47]
```diff
@@ -2187,6 +1982,336 @@ public static boolean areAnyGencodeFuncotation(final List<Funcotation> funcotati
...
+
+                        refAaSeq = refAaSeq.substring(0, refAaSeq.length() - 1);
+                        altAaSeq = altAaSeq.substring(0, altAaSeq.length() - 1);
+                    }
+
+                    frontMustBeTrimmed = (!refAaSeq.isEmpty()) && (!altAaSeq.isEmpty()) && (refAaSeq.charAt(0) == altAaSeq.charAt(0));
+                }
+            }
+        }
+        else if ( GATKVariantContextUtils.isDeletion( refAllele, altAllele ) ) {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: I've refactored the code to be a little easier to read.

At this point it would be difficult to factor out the shared code (specifically for the trimming / reduction) because of the small differences in operations.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 48]
```diff
@@ -2187,6 +1982,336 @@ public static boolean areAnyGencodeFuncotation(final List<Funcotation> funcotati
...
+            }
+        }
+
+        return ProteinChangeInfo.create(aaStartPos, aaEndPos, refAaSeq, altAaSeq);
+    }
+
+    /**
+     * A simple container class that holds the required information about a protein change.
+     */
+    public static final class ProteinChangeInfo {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Done.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/SequenceComparison.java [hunk 49]
```diff
@@ -166,17 +146,17 @@
...
     /**
      * The fraction of Guanine and Cytosine bases in a window of a given size around a variant.
      * The default windows size is {@link org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory#gcContentWindowSizeBases}.
      */
     private Double gcContent                             = null;
 
+    /**
+     * Container holding information on the protein change represented by this {@link SequenceComparison} object.
+     */
+    private FuncotatorUtils.ProteinChangeInfo proteinChangeInfo = null;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/SequenceComparison.java]: Fair enough.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 50]
```diff
@@ -77,6 +77,12 @@
      */
     private static final int defaultNumTrailingBasesForUtrAnnotationSequenceConstruction = 3;
 
+    /**
+     * The window for an indel to be within the end of a transcript to trigger padding the end of the
+     * transcript with additional bases from the reference.
+     */
+    private static final int TRANSCRIPT_END_WINDOW_PADDING_THRESHOLD = 10;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: It can reference the `referenceWindow`, but in practice it shouldn't matter.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 51]
```diff
@@ -652,7 +660,7 @@ private GencodeFuncotation createGencodeFuncotationOnTranscript(final VariantCon
 
         // Make sure the sub-regions in the transcript actually contain the variant:
         // TODO: this is slow, and repeats work that is done later in the process (we call getSortedCdsAndStartStopPositions when creating the sequence comparison)
-        final int startPosInTranscript =  FuncotatorUtils.getStartPositionInTranscript(variantToUse, getSortedCdsAndStartStopPositions(transcript), transcript.getGenomicStrand() );
+        final int startPosInTranscript =  FuncotatorUtils.getStartPositionInCodingSequence(variantToUse, getSortedCdsAndStartStopPositions(transcript), transcript.getGenomicStrand() );
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: OBE - fixed by renaming the method itself.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 52]
```diff
@@ -745,27 +753,41 @@ private GencodeFuncotation createCodingRegionFuncotationForNonProteinCodingFeatu
...
         // Set the reference context with the bases from the sequence comparison
         // NOTE: The reference context is ALWAYS from the + strand, so we need to reverse our bases back in the - case:
-        if ( sequenceComparison.getStrand() == Strand.POSITIVE ) {
-            gencodeFuncotationBuilder.setReferenceContext(sequenceComparison.getReferenceBases());
+        if ( exon.getGenomicStrand() == Strand.POSITIVE ) {
+            gencodeFuncotationBuilder.setReferenceContext(referenceBases);
         }
         else {
-            gencodeFuncotationBuilder.setReferenceContext(ReadUtils.getBasesReverseComplement(sequenceComparison.getReferenceBases().getBytes()));
+            gencodeFuncotationBuilder.setReferenceContext(ReadUtils.getBasesReverseComplement(referenceBases.getBytes()));
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 53]
```diff
@@ -946,8 +975,13 @@ else if ( exon.getStopCodon() != null ) {
 
         boolean hasBeenClassified = false;
 
+        // Adjust the variant interval for the overlap check, specifically to properly test for the indel cases.
+        // That is, since we always have a preceding base with indels, we adjust the variant interval to remove this
+        // base so we can use the `overlaps` methods and get the correct results:
+        final SimpleInterval realVariationInterval = getChangedBasesInterval(variant, altAllele);
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Changed to `getBasesChangedIntervalIgnoringLeadingVcfContextBase`

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 54]
```diff
@@ -1193,16 +1227,23 @@ private GencodeFuncotation createUtrFuncotation(final VariantContext variant,
...
                         getFivePrimeUtrSequenceFromTranscriptFasta( transcript.getTranscriptId(), transcriptIdMap, transcriptFastaReferenceDataSource, numExtraTrailingBases);
 
-                final int codingStartPos = FuncotatorUtils.getStartPositionInTranscript(variant, activeRegions, strand);
+                final int codingStartPos = FuncotatorUtils.getStartPositionInCodingSequence(variant, activeRegions, strand);
 
-                // But we can really just use the referenceBases to do this:
-                final String rawAltUtrSubSequence = (referenceBases.substring(referenceWindow-numLeadingBasesForUtrAnnotationSequenceConstruction, referenceWindow) +
+                // We can use the `referenceBases` to get the alt subsequence, but we need to adjust it for indels.
+                // We make this adjustment with knowledge of how the referenceBases sequence was created in the first
+                // place.
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Thtat's a good idea.  At this point it will require a lot of instrumentation, but I have created issue #5349 to track this.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 55]
```diff
@@ -1314,47 +1354,6 @@ private GencodeFuncotation createIntronFuncotation(final VariantContext variant,
...
-        // Get the bases in the correct direction:
-        if ( strand == Strand.POSITIVE ) {
-            return new String(referenceBases);
-        }
-        else {
-            return ReadUtils.getBasesReverseComplement(referenceBases);
-        }
-    }
-
     private static SimpleInterval getChangedBasesInterval(final VariantContext variant,
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Fixed (`getBasesChangedIntervalIgnoringLeadingVcfContextBase`)

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 56]
```diff
@@ -1501,6 +1504,8 @@ static SequenceComparison createSequenceComparison(final VariantContext variant,
                                                        final ReferenceDataSource transcriptFastaReferenceDataSource,
                                                        final boolean processSequenceInformation) {
 
+        // TODO: Somewhere down the line we should adjust the positions at creation-time to account for the leading bases in VCF input files.  This will have ramifications down the line for all fields that get rendered.
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Created issue #5349 to track this.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 2 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 7 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: #5350

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 8 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 9 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 11 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 10 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: FIXED.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 12 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 13 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 15 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java (hunk 17 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java]: Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java (hunk 18 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java]: Sure.  Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java (hunk 19 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtilsUnitTest.java]: Yes - #5351

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java (hunk 20 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java]: Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java (hunk 21 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java]: Fixed!

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java (hunk 22 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorTestConstants.java]: Sure.  Fixed.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 14 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Sure.  This seems somewhat redundant given that there is a test for VCF/MAF concordance already, but I'll add in a MAF check.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 16 above)
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: It is being run, but the mapped asserts do not function as expected.

I will fix them.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 57]
```diff
@@ -1511,47 +1294,57 @@ public static String getAlignedRefAllele(final String referenceSnippet,
...
+        // Get the bases in the correct direction:
         if ( strand == Strand.POSITIVE ) {
-            // Get the reference sequence:
-            referenceBases = new String(bases);
+            return new String(referenceBases);
         }
         else {
-            // Get the reference sequence:
-            referenceBases = ReadUtils.getBasesReverseComplement(referenceContext.getBases(referenceWindowInBases, endWindow));
+            return ReadUtils.getBasesReverseComplement(referenceBases);
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Sure.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 58]
```diff
@@ -2205,5 +2047,53 @@ public static String renderSanitizedFuncotationForVcf(final Funcotation funcotat
                 .map(field -> FuncotatorUtils.sanitizeFuncotationFieldForVcf(funcotation.getField(field)))
                 .collect(Collectors.joining(VcfOutputRenderer.FIELD_DELIMITER));
     }
+
+    /**
+     * Simple container class to represent bases that have been corrected for strandedness already.
+     * That is, if they would occur on {@link Strand#NEGATIVE}, they have been reverse-complemented.
+     * If they would occur on {@link Strand#POSITIVE}, they have not been altered.
+     */
+    public static class StrandCorrectedReferenceBases {
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Might want to add the Strand as a field here, so that the strand correction could be reversed if needed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 59]
```diff
@@ -1515,13 +1528,13 @@ static SequenceComparison createSequenceComparison(final VariantContext variant,
         // Get the strand-corrected alleles from the inputs.
         // Also get the reference sequence for the variant region.
         // (spanning the entire length of both the reference and the variant, regardless of which is longer).
-        final Allele refAllele = FuncotatorUtils.getStrandCorrectedAllele(variant.getReference(), transcript.getGenomicStrand());
-        final Allele altAllele = FuncotatorUtils.getStrandCorrectedAllele(alternateAllele, transcript.getGenomicStrand());
-        final String referenceBases = getReferenceBases(variant.getReference(), alternateAllele, reference, transcript.getGenomicStrand());
+        final Allele                                        refAllele      = FuncotatorUtils.getStrandCorrectedAllele(variant.getReference(), transcript.getGenomicStrand());
+        final Allele                                        altAllele      = FuncotatorUtils.getStrandCorrectedAllele(alternateAllele, transcript.getGenomicStrand());
+        final FuncotatorUtils.StrandCorrectedReferenceBases referenceBases = FuncotatorUtils.createReferenceSnippet(variant.getReference(), alternateAllele, reference, transcript.getGenomicStrand(), referenceWindow);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Move `StrandCorrectedReferenceBases` out of `FuncotatorUtils` and into its own file, so that you don't have to qualify it everywhere. Funcotator package is fine for now, but might want to consider moving to `utils.reference` eventually.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 60]
```diff
@@ -1515,13 +1528,13 @@ static SequenceComparison createSequenceComparison(final VariantContext variant,
         // Get the strand-corrected alleles from the inputs.
         // Also get the reference sequence for the variant region.
         // (spanning the entire length of both the reference and the variant, regardless of which is longer).
-        final Allele refAllele = FuncotatorUtils.getStrandCorrectedAllele(variant.getReference(), transcript.getGenomicStrand());
-        final Allele altAllele = FuncotatorUtils.getStrandCorrectedAllele(alternateAllele, transcript.getGenomicStrand());
-        final String referenceBases = getReferenceBases(variant.getReference(), alternateAllele, reference, transcript.getGenomicStrand());
+        final Allele                                        refAllele      = FuncotatorUtils.getStrandCorrectedAllele(variant.getReference(), transcript.getGenomicStrand());
+        final Allele                                        altAllele      = FuncotatorUtils.getStrandCorrectedAllele(alternateAllele, transcript.getGenomicStrand());
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: There's no marker type for strand-corrected Alleles, so we still have the same problem with Alleles as we did with reference bases. Recommend that you introduce an empty subclass of `Allele` to serve as a marker, and use that whenever a method expects the alleles to be strand-corrected.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 61]
```diff
@@ -946,13 +979,18 @@ else if ( exon.getStopCodon() != null ) {
...
+
         // Check for non-stop first:
-        if ( (exon.getStopCodon() != null) && (exon.getStopCodon().overlaps(variant)) ) {
+        if ( (exon.getStopCodon() != null) && (exon.getStopCodon().overlaps(realVariationInterval)) ) {
 
             boolean foundStop = false;
 
-            for (int i = 0; (i+3) < sequenceComparison.getAlignedCodingSequenceAlternateAllele().length(); i+=3 ){
-                final String codon = sequenceComparison.getAlignedCodingSequenceAlternateAllele().substring(i, i+3);
+            for (int i = 0; (i+AminoAcid.CODON_LENGTH-1) < sequenceComparison.getAlignedCodingSequenceAlternateAllele().length(); i+=AminoAcid.CODON_LENGTH ){
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Did you intend to add the -1 here? (in `i+AminoAcid.CODON_LENGTH-1`)

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java (hunk 58 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Sure.

Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 59 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: I've put it in the `funcotator` package.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 61 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Yes.

Otherwise the last codon would not be checked in the for loop because of the end condition.  Since the second argument to `String::substring` is exclusive, it is OK if `i == sequenceComparison.getAlignedCodingSequenceAlternateAllele().length()`.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 60 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: This is a good idea.  I've created the base class type and issue #5354 to track this.
