### PR TITLE
Adding in a prototype MafOutputRenderer for Funcotator (and many fixes)

### LINKED ISSUE #3922: Funcotator - Create a MAF Output renderer
To create output to MAF files, a MAF output renderer must be created in Funcotator.

### LINKED ISSUE #4022: Funcotator - Reference version input should be string, not enum
The reference version should be specified as a string, not an enum.

This will allow a user to add data sources for arbitrary references.

### LINKED ISSUE #4420: Funcotator - Transcript position is being computed incorrectly in GencodeFuncotationFactory
The `transcriptPosition` annotation is being computed incorrectly in the `GencodeFuncotationFactory`.  This erroneous logic must be replaced with logic that is correct for the definition of the field as found here:

https://wiki.nci.nih.gov/display/TCGA/Mutation+Annotation+Format+(MAF)+Specification

### PR DESCRIPTION
**Pull request by jonn-smith**
Added in argument for MAF out.
Added more "required" MAF fields.
Added Funcotation::getDataSourceName
Added contig name overrides for hg19 VS B37
Added in code to convert VCF INDEL positions to MAF INDEL positions.
Added start/stop positions for IGRs.
Added argument to ignore filtered variants at the front of processing to save time.
Added a script to fully retrieve the COSMIC data sources.

Fixed how the MafOutputRenderer handles mapping fields to values.
Fixed a bug in LocatableXsv and COSMIC parsers (was missing name and
    version).
In Gencode: Now TumorSeqAllele1 is the refAllele, not the AltAllele.
Fixed some problems with VCF output.
Updated VCF outputs to have better header info.
Refactored header output for OutputRenderers.
Changed the logic for creating alt protein sequences.
Fixed a bug in the LocatableXsvFuncotationFactory that caused annotations to be incorrectly associated with a factory.
Fixed several bugs in the GencodeFuncotationFactory.
Fixed bugx in the handling of UTR variants.
Fixed the Transcript Selection Mode ordering.
Fixed an issue with splice sites.

Minor speed fix to GencodeFuncotationFactory.

Now CosmicFuncotationFactory opens the database in read-only mode.

Bugfix - now LocatableXsvFuncotationFactories use overrides.

Now the reference should properly align with ALL indels regardless of
length.

ReferenceContext now always rendered on + strand.

Now will create funcotations for transcripts without fasta sequences.

Minor changes to FuncotatorIntegrationTest.

- Added in more integration test files.  These are as yet unused - must
refactor the files themselves to actually reflect what should be correct
as far as produced funcotations.

- Updated LocatableXsvFuncotationFactoryUnitTest.java and SimpleKeyXsvFuncotationFactoryUnitTest.java
to reflect the change to funcotation factories to always produce the
expected funcotations (rather than only producing funcotations when
    there are data that match the target variant).

Fixed an issue with the new VariantClassification code.

Fixed issue #4410

Fixed #4022

Fixed #4420

Fixed #3922

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 1]
```diff
@@ -529,7 +624,11 @@ else if ( configFileSet.size() == 0 ) {
             }
         }
 
-        if ( !hasGencodeDataSource ) {
+        // Sanity checks to make sure we actually found our data sources:
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Would this imply that there was a folder for a data source + genome build (e.g. `hg38/my_datasource/`), but that it was empty or had invalid files?  If so, that is fine.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 2]
```diff
@@ -576,7 +676,7 @@ private void createLocatableXsvDataSource(final Path dataSourceFile,
         manualFeatureInputs.add(featureInput);
 
         // Create a locatable XSV feature reader to handle XSV Locatable features:
-        final LocatableXsvFuncotationFactory locatableXsvFuncotationFactory = new LocatableXsvFuncotationFactory();
+        final LocatableXsvFuncotationFactory locatableXsvFuncotationFactory = new LocatableXsvFuncotationFactory(name, version, annotationOverridesMap);
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: I'm not sure that we want the overrides going into each datasource.  Seems unnecessary...  Wouldn't we want to have the overrides applied after the datasources had generated their funcotations?

Comment (LeeTL1220) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: If you agree, feel free to file an issue instead of addressing immediately.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 3]
```diff
@@ -246,9 +268,9 @@
     @Argument(
             fullName  = FuncotatorArgumentDefinitions.TRANSCRIPT_LIST_LONG_NAME,
             optional = true,
-            doc = "Set of transcript IDs to use for annotation to override selected transcript."
+            doc = "File to use as a list of transcripts (one transcript ID per line) OR A set of transcript IDs to use for annotation to override selected transcript."
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Do the transcript IDs need to have the version numbers (e.g. ENST00000123456.5) or not (e.g. ENST00000123456)?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 4]
```diff
@@ -1725,6 +1796,639 @@ public static void assertValidStrand( final Strand strand ) {
...
+        b37ToHg19ContigNameMap.put( "GL000220.1", "GL000220.1" );
+        b37ToHg19ContigNameMap.put( "GL000236.1", "GL000236.1" );
+
+        return b37ToHg19ContigNameMap;
+    }
+
+    /**
+     * @return An initialized {@link SAMSequenceDictionary} containing the {@link SAMSequenceRecord}s from the B37 Human Genome Reference.
+     */
+    private static final SAMSequenceDictionary initializeB37SequenceDict() {
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Is there really no other way to do this?  This seems like a lot of hardcoding for what could just be a resource file in the jar and then read in with one line of code.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 5]
```diff
@@ -390,13 +416,53 @@ private static MappedTranscriptIdInfo createMappedTranscriptIdInfo( final SAMSeq
             }
         }
 
+        // TODO: This may not be correct.  It's not clear that the whole sequence should be taken.  Perhaps it should be handled with logic downstream...
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Has this TODO been addressed?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 6]
```diff
@@ -538,60 +638,39 @@ private GencodeFuncotation createGencodeFuncotationOnTranscript(final VariantCon
                                                                     final GencodeGtfTranscriptFeature transcript) {
         final GencodeFuncotation gencodeFuncotation;
 
-        // We only fully process protein-coding regions.
-        // For other gene types, we do trivial processing and label them as either LINCRNA or RNA:
-        // TODO: Add more types to Variant Classification to be more explicit and a converter function to go from gene type to variant classification.
-        if ( gtfFeature.getGeneType() != GencodeGtfFeature.GeneTranscriptType.PROTEIN_CODING ) {
+        // TODO: check for complex INDEL and warn and skip.
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Has this been addressed?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 7]
```diff
@@ -717,28 +910,30 @@ else if ( exon.getStopCodon() != null ) {
...
-        if ( altAllele.length() >= variant.getReference().length()  ) {
-            endPos = sequenceComparison.getAlleleStart() + altAllele.length() - 1;
-        }
-        else {
-            endPos = sequenceComparison.getAlleleStart() + variant.getReference().length() - 1;
-        }
-
-        // Calculate the number of inserted bases so we can account for them in the splice site calculations:
-        final int numInsertedBases = (altAllele.length() > variant.getReference().length()) ? altAllele.length() - variant.getReference().length() : 0;
+//        // Get our start position:
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Can you delete code that is being commented out?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 8]
```diff
@@ -1026,9 +1263,70 @@ private static GencodeFuncotation createIntronFuncotation(final VariantContext v
...
+        if ( strand == Strand.POSITIVE ) {
+
+            final int endWindow =
+                    refAllele.length() >= altAllele.length() ?
+                            referenceWindow + refAllele.length() - 1 :
+                            referenceWindow + altAllele.length() - 1;
+
+            // Get the reference sequence:
+             return new String(reference.getBases(
+//                    new SimpleInterval(reference.getWindow().getContig(),
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Can you get rid of code that has been commented out?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 9]
```diff
@@ -1026,9 +1263,70 @@ private static GencodeFuncotation createIntronFuncotation(final VariantContext v
...
+                            referenceWindow + altAllele.length() - 1;
+
+            // Get the reference sequence:
+            // NOTE: The "frontPadding" actually adds padding to the back of the coding sequence because the strand
+            //       is negative and we have to reverse complement the bases.
+            //       However, we pass in the overall interval before reverse complementing, so this padding happens on
+            //       the front of the query interval.
+            return ReadUtils.getBasesReverseComplement(
+                    reference.getBases(
+//                            new SimpleInterval(reference.getWindow().getContig(),
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Delete commented out code

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 10]
```diff
@@ -1026,9 +1263,70 @@ private static GencodeFuncotation createIntronFuncotation(final VariantContext v
...
+     * @param strand The {@link Strand} on which the variant occurs.
+     * @return A {@link String} of bases of length {@link #referenceWindow} * 2 + |variant|
+     */
+    private static String getReferenceBases(final Allele refAllele, final Allele altAllele, final ReferenceContext reference, final Strand strand ) {
+
+        // Adjustment for the start of the variant based on whether it's a deletion or not.
+        // NOTE: This is an artifact of the GATK representation of variants (that they must be at least 1 base)
+        final int deletionStartAdjustment =  GATKVariantContextUtils.isDeletion(refAllele, altAllele) ? 1 : 0;
+
+        if ( strand == Strand.POSITIVE ) {
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: I'm not sure why you need the strand to figure out the reference window to use around a variant.  Can you explain?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 11]
```diff
@@ -1454,13 +1764,8 @@ else if ( variant.getReference().length() == 1 ) {
      */
     private void sortFuncotationsByTranscriptForOutput( final List<GencodeFuncotation> funcotationList ) {
         //TODO: Make this sort go from "worst" -> "best" so we can just pop the last element off and save some time.
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Have you addressed these TODOs?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 12]
```diff
@@ -0,0 +1,764 @@
...
+            // Check to see if it's a deletion:
+            else if ( refAlleleLength > altAlleleLength ) {
+                // We must:
+                //    Remove the first N bases from the REF_allele where N = length(alt_allele)
+                //    Remove the first N bases from the Tumor_Seq_Allele1
+                //    Replace the alt_allele with "-"
+                //    Increment the Start_Position by 1 (start position should be inclusive of the first base deleted)
+                //    Increment the End_Position by M-1 where M = length(ref_allele) (end position should be inclusive of the last base deleted)
+                finalOutMap.put("Reference_Allele", finalOutMap.get("Reference_Allele").substring(altAlleleLength));
+                finalOutMap.put("Tumor_Seq_Allele1", finalOutMap.get("Tumor_Seq_Allele1").substring(altAlleleLength));
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Use constants instead of raw strings, especially for repeated fields.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 13]
```diff
@@ -0,0 +1,764 @@
...
+        writeLine(FIELD_DELIMITER + manualAnnotations.keySet().stream().collect(Collectors.joining(FIELD_DELIMITER)));
+
+        // Make sure we keep track of the fact that we've now written the header:
+        hasWrittenHeader = true;
+    }
+
+    /**
+     * Initializes {@link MafOutputRenderer#defaultMap} with the default keys for the columns in a MAF file.
+     */
+    protected void initializeDefaultMapWithKeys() {
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Can we drive this from a config file or just a list of MAF field Strings?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 14]
```diff
@@ -0,0 +1,764 @@
...
+        defaultMap.put("FamilialCancerDatabase_Syndromes",            UNKNOWN_VALUE_STRING);
+        defaultMap.put("MUTSIG_Published_Results",                    UNKNOWN_VALUE_STRING);
+        defaultMap.put("OREGANNO_ID",                                 UNKNOWN_VALUE_STRING);
+        defaultMap.put("OREGANNO_Values",                             UNKNOWN_VALUE_STRING);
+    }
+
+    /**
+     * Initializes the output map
+     */
+    private void initializeOutputFieldNameMap() {
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: You may want to drive this from a configuration file.  Even if not, you should refactor out some constants (at least for the actual MAF Field names)

File: scripts/funcotator/data_sources/cosmic/getCosmicDataSources.sh [hunk 15]
```diff
@@ -0,0 +1,213 @@
+#!/usr/bin/env bash
+
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply scripts/funcotator/data_sources/cosmic/getCosmicDataSources.sh]: It doesn't accept any parameters, but I'll add in some -h information and a message when run normally.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java (hunk 1 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: That is one case, but another would be if there was no gencode directory at all.

If any error in creating the gencode data source occurs, it will not set `hasGencodeDataSource` to true.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java (hunk 2 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: This is the way all the manual annotations have been working since that feature was implemented - I just forgot to hook them into the `LocatableXsvFuncotationFactory` in the construction.

I built them this way because it made overriding fields with VCF much easier.

Because MAF needs a map for the funcotations, it may now be easier to do this in the output renderers themselves.  It will probably simplify a few things.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java (hunk 3 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Version numbers are ignored - I'll update the documentation.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java (hunk 4 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: That's true.  I didn't think about including the sequence dictionary in the jar.  

I'll fix it.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 5 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Not yet.  I haven't thought through what should be done if there is no CDS.

In practice I'm not sure that this case actually comes up.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 6 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: No - not yet.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 7 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Sure.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 8 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Sure.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 9 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 10 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: I use the reference window to create the in-frame alleles so I need to make it strand-correct.  When I report it in the funcotation itself, I make sure it's always in the forward direction.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 11 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: No, not yet.  I was waiting to do these for when I start speeding it up.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java (hunk 12 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java (hunk 13 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Yeah - the plan is to have a config file for funcotator that can have all these fields in it, but there needs to be a hard-coded default in the case of no config.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java (hunk 14 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Agreed - again, I'd like to have a config file, but I wanted to have some hard-coded defaults for when there is no config file given.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java [hunk 16]
```diff
@@ -155,6 +163,11 @@ public static GencodeFuncotationBuilder getBuilder() {
 
     //==================================================================================================================
 
+    @Override
+    public Allele getAltAllele() {
+        return Allele.create(tumorSeqAllele2.getBytes(), false);
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java]: tumorSeqAllele2 is not an ideal name, that's a maf thing though isn't it?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java [hunk 17]
```diff
@@ -187,59 +200,68 @@ public String serializeToVcfString() {
 
     @Override
     public void setFieldSerializationOverrideValue( final String fieldName, final String overrideValue ) {
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java]: this method and the next method and the override variables feel like they could maybe be replaced with a map instead of hardcoded cases?  Is there a reason to do it this way?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationBuilder.java [hunk 18]
```diff
@@ -163,7 +164,7 @@ public GencodeFuncotationBuilder setAnnotationTranscript(final String transcript
      * @param transcriptPos The position (1-based, inclusive) relative to the start of the transcript of a the variant in the {@link GencodeFuncotation}.
      * @return {@code this} {@link GencodeFuncotationBuilder}
      */
-    public GencodeFuncotationBuilder setTranscriptPos(final int transcriptPos) {
+    public GencodeFuncotationBuilder setTranscriptPos(final Integer transcriptPos) {
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationBuilder.java]: this became an `Integer` to support the case where there's no transcript?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 19]
```diff
@@ -177,25 +192,36 @@ public GencodeFuncotationFactory(final Path gencodeTranscriptFastaFile,
             this.userRequestedTranscripts.add( getTranscriptIdWithoutVersionNumber(transcript) );
         }
 
+        // Set our comparator for outputting our funcotations in the right order with the correct "best" transcript:
+        if ( transcriptSelectionMode == FuncotatorArgumentDefinitions.TranscriptSelectionMode.BEST_EFFECT ) {
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: I would also tend to bake the comparator into the TranscriptSelectionMode enum itself, so instead of this if statement you just call `transcriptSelectMode.getComparator(userRequestedTranscripts)`

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 20]
```diff
@@ -390,13 +416,53 @@ private static MappedTranscriptIdInfo createMappedTranscriptIdInfo( final SAMSeq
...
 
+    /**
+     * Get the whole sequence from the GENCODE Transcript FASTA file for a given {@code transcriptId}.
+     * This will get ALL bases in the sequence of the given {@code transcriptId}, including any UTRs and the coding region.
+     * @param transcriptId The ID of the transcript to get from the FASTA file.
+     * @param transcriptIdMap A map from transcriptId to MappedTranscriptIdInfo, which tells us how to pull information for the given {@code transcriptId} out of the given {@code transcriptFastaReferenceDataSource}.
+     * @param transcriptFastaReferenceDataSource A {@link ReferenceDataSource} for the GENCODE transcript FASTA file.
+     * @return The whole sequence for the given {@code transcriptId} as represented in the GENCODE transcript FASTA file.
+     */
+    private static String getWholeSequenceFromTranscriptFasta( final String transcriptId,
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: this method seems to be unused

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 21]
```diff
@@ -600,58 +679,170 @@ else if ( GencodeGtfTranscriptFeature.class.isAssignableFrom(containingSubfeatur
...
+                                                                                    final ReferenceContext reference,
+                                                                                    final GencodeGtfTranscriptFeature transcript,
+                                                                                    final GencodeGtfExonFeature exon) {
 
-        // Set the Coding DNA change:
-        final boolean isInCodingRegion = isVariantInCodingRegion( varClass, secondaryVarClass );
+        // Get the list of exons by their locations so we can use them to determine our location in the transcript and get
+        // the transcript code itself:
+        final List<? extends Locatable> exonPositionList = getSortedExonAndStartStopPositions(transcript);
+//        final List<? extends Locatable> exonPositionList = transcript.getExons();
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: commented out line here, should probably be deleted

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 22]
```diff
@@ -1026,9 +1248,64 @@ private static GencodeFuncotation createIntronFuncotation(final VariantContext v
...
+    private static String getReferenceBases(final Allele refAllele, final Allele altAllele, final ReferenceContext reference, final Strand strand ) {
+
+        // Adjustment for the start of the variant based on whether it's a deletion or not.
+        // NOTE: This is an artifact of the GATK representation of variants (that they must be at least 1 base)
+        final int deletionStartAdjustment =  GATKVariantContextUtils.isDeletion(refAllele, altAllele) ? 1 : 0;
+
+        if ( strand == Strand.POSITIVE ) {
+
+            final int endWindow =
+                    refAllele.length() >= altAllele.length() ?
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: this might read better as `endWindow = Math.max(refAllele.length, altAlleleLength) + referenceWindow -1;`

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 23]
```diff
@@ -1026,9 +1248,64 @@ private static GencodeFuncotation createIntronFuncotation(final VariantContext v
...
+             return new String(reference.getBases(
+                     new SimpleInterval(reference.getWindow().getContig(),
+                             reference.getWindow().getStart() - referenceWindow,
+                             reference.getWindow().getEnd() + endWindow)
+                )
+            );
+        }
+        else {
+            // Calculate our window to include any extra bases but also have the right referenceWindow.
+            final int frontPadding =
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: same here

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 24]
```diff
@@ -1026,9 +1248,64 @@ private static GencodeFuncotation createIntronFuncotation(final VariantContext v
...
+     * @param altAllele The alternate {@link Allele} for the variant.
+     * @param reference The {@link ReferenceContext} for the variant, with the current window around the variant.
+     * @param strand The {@link Strand} on which the variant occurs.
+     * @return A {@link String} of bases of length {@link #referenceWindow} * 2 + |variant|
+     */
+    private static String getReferenceBases(final Allele refAllele, final Allele altAllele, final ReferenceContext reference, final Strand strand ) {
+
+        // Adjustment for the start of the variant based on whether it's a deletion or not.
+        // NOTE: This is an artifact of the GATK representation of variants (that they must be at least 1 base)
+        final int deletionStartAdjustment =  GATKVariantContextUtils.isDeletion(refAllele, altAllele) ? 1 : 0;
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: this is unused, I assume it's supposed to be used in here somewhere

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 25]
```diff
@@ -1082,7 +1360,8 @@ private static GencodeGtfFeature getContainingGtfSubfeature(final VariantContext
             // where this overlaps something more meaningful.
             // For example, see HG19 - chr19:8959608
             for (final GencodeGtfExonFeature exon : transcript.getExons()) {
-                if ((exon.getCds() != null) && (exon.getCds().overlaps(variant))) {
+                // TODO: It would be really nice if you could make this work for the OVERLAPS method not just the CONTAINS method.  This is in here for issue #4307.
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: I don't understand this todo.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 26]
```diff
@@ -1120,85 +1402,55 @@ static SequenceComparison createSequenceComparison(final VariantContext variant,
                                                        final GencodeGtfTranscriptFeature transcript,
                                                        final List<? extends htsjdk.samtools.util.Locatable> exonPositionList,
                                                        final Map<String, MappedTranscriptIdInfo> transcriptIdMap,
-                                                       final ReferenceDataSource transcriptFastaReferenceDataSource) {
+                                                       final ReferenceDataSource transcriptFastaReferenceDataSource,
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: stopping here for now.  So much code..

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 27]
```diff
@@ -223,19 +232,32 @@
...
 
     @Argument(
             fullName =  FuncotatorArgumentDefinitions.DATA_SOURCES_PATH_LONG_NAME,
             doc = "The path to a data source folder for Funcotator.  May be specified more than once to handle multiple data source folders."
     )
     protected List<String> dataSourceDirectories;
 
+    @Argument(
+            fullName =  FuncotatorArgumentDefinitions.OUTPUT_FORMAT_LONG_NAME,
+            doc = "The output file format.  Either VCF or MAF"
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Does it fill it out in the doc?  I wanted to let users know that only those 2 output formats are supported right now.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 28]
```diff
@@ -223,19 +232,32 @@
...
+    )
+    protected FuncotatorArgumentDefinitions.OutputFormatType outputFormatType;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: I prefer to have choices like this explicit.  It makes the user more aware of what is happening.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java [hunk 29]
```diff
@@ -20,9 +20,14 @@
 
     public static final String DATA_SOURCES_PATH_LONG_NAME = "data-sources-path";
 
+    public static final String OUTPUT_FORMAT_LONG_NAME = "output-file-format";
+
     // ------------------------------------------------------------
     // Definitions for optional arguments:
 
+    public static final String IGNORE_FILTERED_VARIANTS_LONG_NAME = "ignore-filtered-variants";
+    public static final boolean IGNORE_FILTERED_VARIANTS_DEFFAULT_VALUE = false;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java]: Sounds good.  Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java [hunk 30]
```diff
@@ -35,6 +40,12 @@
     public static final String ANNOTATION_OVERRIDES_LONG_NAME = "annotation-override";
     public static final List<String> ANNOTATION_OVERRIDES_DEFAULT_VALUE = new ArrayList<>();
 
+    public static final String ALLOW_HG19_GENCODE_B37_CONTIG_MATCHING_LONG_NAME = "allow-hg19-gencode-b37-contig-matching";
+    public static final boolean ALLOW_HG19_GENCODE_B37_CONTIG_MATCHING_DEFAULT_VALUE = false;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorArgumentDefinitions.java]: Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 31]
```diff
@@ -272,15 +301,26 @@
 
     private List<FeatureInput<? extends Feature>> manualFeatureInputs = new ArrayList<>();
 
+    private Boolean inputReferenceIsB37 = null;
+
     //==================================================================================================================
 
+    @Override
+    protected String getVersion() {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Sounds good.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 32]
```diff
@@ -312,6 +364,20 @@ public void apply(final VariantContext variant, final ReadsContext readsContext,
             throw new GATKException("No reference context for variant.  Cannot annotate!");
         }
 
+        if ( allowHg19GencodeContigNamesWithB37 &&
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Sounds good.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 33]
```diff
@@ -295,13 +335,25 @@ public void onTraversalStart() {
...
+            // Default to VCF output:
+            default:
+                outputRenderer = new VcfOutputRenderer(getHeaderForVariants(),
+                        createVCFWriter(outputFile),
+                        dataSourceFactories,
+                        unaccountedForDefaultAnnotations,
+                        unaccountedForOverrideAnnotations,
+                        getDefaultToolVCFHeaderLines());
+                break;
+        }
```
[the remark this answers is not in the document]
Comment (pshapiro4broad) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Another (better, IMO) way to avoid this issue is to put the logic in the enum. This code becomes 
```
outputRenderer  = outputFormatType.createRenderer(outputFile, dataSourceFactories, unaccountedForDefaultAnnotations, unaccountedForOverrideAnnotations, getHeaderForVariants(), getDefaultToolVCFHeaderLines();
```
The enum code would look like
```
    enum OutputFormatType {
        MAF {
            OutputRenderer createRenderer(...) {
                return new MafOutputRenderer(...);
            }
        },
        VCF {
            OutputRenderer createRenderer(...) {
                return VcfOutputRenderer(...);
            }
        };
        abstract OutputRenderer createRenderer();
    }
```
This is better as it doesn't require `default` and it requires that any future change to `OutputFormatType` requires adding a new `createRenderer()` method.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 34]
```diff
@@ -312,6 +364,20 @@ public void apply(final VariantContext variant, final ReadsContext readsContext,
             throw new GATKException("No reference context for variant.  Cannot annotate!");
         }
 
+        if ( allowHg19GencodeContigNamesWithB37 &&
+                (referenceVersion.equals(FuncotatorArgumentDefinitions.HG19_REFERENCE_VERSION_STRING)) &&
+                (inputReferenceIsB37 == null) ) {
+            // NOTE AND WARNING:
+            // hg19 is from ucsc. b37 is from the genome reference consortium. ucsc decided the grc version had crap in it, so they blocked out some of the bases, aka "masked" them
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: No prob. :P

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 35]
```diff
@@ -295,13 +335,25 @@ public void onTraversalStart() {
...
-                                               unaccountedForOverrideAnnotations);
-
+        switch (outputFormatType) {
+            case MAF:
+                outputRenderer = new MafOutputRenderer(outputFile.toPath(),
+                        dataSourceFactories,
+                        unaccountedForDefaultAnnotations,
+                        unaccountedForOverrideAnnotations,
+                        getHeaderForVariants(),
+                        getDefaultToolVCFHeaderLines().stream().map(x -> x.toString()).collect(Collectors.toCollection(LinkedHashSet::new)));
```
Comment (pshapiro4broad) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: A more natural way to write `x -> x.toString()` is `Object::toString`

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 36]
```diff
@@ -1646,6 +1673,55 @@ public static String getCodingSequence(final ReferenceContext reference, final L
...
+        return true;
+    }
+
+    /**
+     * Converts a given B37 style contig name to the equivalent in hg19.
+     * @param b37Contig The contig name from the B37 Human Genome reference to convert to the equivalent contig from the HG19 Human Genome reference.
+     * @return The HG19 equivalent of the given B37 contig name, if such an equivalent name exists.  If no equivalent name exists, returns the given {@code b37Contig}.
+     */
+    public static String convertB37ContigToHg19Contig( final String b37Contig ) {
+        if ( B37_To_HG19_CONTIG_NAME_MAP.containsKey(b37Contig) ) {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Neat.  Fixed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 37]
```diff
@@ -1725,6 +1801,142 @@ public static void assertValidStrand( final Strand strand ) {
...
+
+    /**
+     * @return An initialized {@link SAMSequenceDictionary} containing the {@link SAMSequenceRecord}s from the B37 Human Genome Reference.
+     */
+    private static synchronized final SAMSequenceDictionary initializeB37SequenceDict() {
+
+        if ( B37_SEQUENCE_DICTIONARY == null ) {
+            try {
+                final File b37SeqDictFile = new File(
+                        ClassLoader.class.getResource("/org/broadinstitute/hellbender/tools/funcotator/Homo_sapiens_assembly19.dict").toURI()
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: I agree!

But this is what the name of the file is here, and I believe it's the official name of the file.

I can append `b37` (or something similar) to it, but I would worry it might lose its significance.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 38]
```diff
@@ -1533,33 +1537,56 @@ public static String getAlternateSequence(final String referenceSequence,
...
+        // Set up our position variable:
+        int position;
 
-        if ( strand == Strand.POSITIVE ) {
-            return variantGenomicStartPosition - codingRegionGenomicStartPosition + 1;
+        // NOTE: We don't need to worry about UTRs in here - all UTRs occur somewhere in an exon in GENCODE.
+
+        // Filter the elements by whether they come before the variant in the transcript and
+        // then sort them by their order in the transcript:
+        final List<Locatable> sortedFilteredExons;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: By the time this code is run the exons in question all come from the same gene.  

Yeah - for Gencode, each exon in a gene is within the span of that gene (and each gene seems to be on one and only one contig).

File: src/main/java/org/broadinstitute/hellbender/engine/ReferenceDataSource.java [hunk 39]
```diff
@@ -28,6 +27,21 @@ public static ReferenceDataSource of(final Path fastaPath) {
...
+     * The provided fasta file must have companion .fai and .dict files.
+     *
+     * If {@code preserveFileBases} is {@code true}, will NOT convert IUPAC bases in the file to `N` and will NOT capitalize lower-case bases.
+     *
+     * NOTE: Most GATK tools do not support data created by setting {@code preserveFileBases} to {@code true}.
+     *
+     * @param fastaPath reference fasta Path
+     * @param preserveFileBases Whether to preserve the original bases in the given reference file path.
+     */
+    public static ReferenceDataSource of(final Path fastaPath, final boolean preserveFileBases) {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/engine/ReferenceDataSource.java]: I wanted to keep the general interface for `ReferenceDataSource` the same, so I thought overloading the `of` method made the most sense.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 40]
```diff
@@ -295,13 +335,25 @@ public void onTraversalStart() {
...
+                break;
+            // Default to VCF output:
+            default:
+                outputRenderer = new VcfOutputRenderer(getHeaderForVariants(),
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: I hadn't thought of that.  I'll make them match eachother.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java (hunk 33 above)
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Sounds good.

Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 41]
```diff
@@ -369,22 +435,51 @@ public void closeTool() {
...
+        }
+
         // Get our feature inputs:
         final List<Feature> featureList = new ArrayList<>();
-        for ( final FeatureInput<? extends Feature> featureInput : manualFeatureInputs ) {
-            featureList.addAll( featureContext.getValues(featureInput) );
+
+        // Create a variant context for annotation that has a new contig based on whether we need to overwrite the
+        // contig names in the next section.
+        final VariantContextBuilder variantContextBuilderForFixedContigForDataSources = new VariantContextBuilder(variant);
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: This is actually a really good point.  Since the input file is assumed to be sorted, most cases will have the same contig.

That said, I think I'd like to wait on the optimization.  I'll add a `todo` in the code.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 42]
```diff
@@ -663,6 +766,42 @@ private void createGencodeDataSource(final Path dataSourceFile,
...
+    /**
+     * Processes the given {@link Set} into a list of transcript IDs.
+     * This is necessary because the command-line input argument is overloaded to be either a file containing transcript
+     * IDs (1 per line) OR as a list of transcript IDs.
+     * @param rawTranscriptSet {@link Set} of {@link String}s from which to create a list of Transcript IDs.  If of size 1, will try to open as a file.
+     * @return A {@link Set} of {@link String} contianing Transcript IDs in which the user is interested.
+     */
+    private Set<String> processTranscriptList(final Set<String> rawTranscriptSet) {
+        if ( rawTranscriptSet.size() == 1 ) {
+            final String filePathString = rawTranscriptSet.toArray(new String[ 1 ])[ 0 ];
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Sounds good.  Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 43]
```diff
@@ -1533,33 +1537,56 @@ public static String getAlternateSequence(final String referenceSequence,
...
+
+            // We are guaranteed that the variant occurs in the last element of sortedTranscriptElements because of the sorting.
+            // Add 1 to position to account for inclusive values:
+            position = sortedFilteredExons.get(sortedFilteredExons.size()-1).getEnd() - variant.getStart() + 1;
+        }
+
+        // Add up the lengths of all exons before the last one:
+        for ( int i = 0; i < sortedFilteredExons.size() - 1; ++i ) {
+            // Add 1 to position to account for inclusive values:
+            position += sortedFilteredExons.get(i).getEnd() - sortedFilteredExons.get(i).getStart() + 1;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: Interesting... I figured the compiler would be smart enough to optimize these kinds of things out of loops.

I'll update it.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/TableFuncotation.java [hunk 44]
```diff
@@ -27,15 +28,23 @@
     //==================================================================================================================
     // Private Members:
 
+    /**
+     * Name of the factory that created this {@link TableFuncotation}.
+     */
+    private String dataSourceName;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/TableFuncotation.java]: Sounds good.  Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java (hunk 16 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java]: Yup.  This is an official field in MAF...

File: src/main/java/org/broadinstitute/hellbender/engine/ReferenceDataSource.java (hunk 39 above)
[the remark this answers is not in the document]
Comment (lbergelson) [reply src/main/java/org/broadinstitute/hellbender/engine/ReferenceDataSource.java]: Oh, I agree with that, I meant that preserveFileBases argument

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java (hunk 17 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java]: In the initial implementation there was no ability to override fields, so every field had its own variable. 

I agree - now that there are overrides, it makes more sense to replace all the variables with a map so that they can have their fields overridden easily.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationBuilder.java (hunk 18 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationBuilder.java]: Correct.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 19 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Interesting.  Sounds good.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 20 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Yeah - it's a left-over idea I had.  I want to be able to get the sequences from the list of exons and the reference itself, rather than requiring the gencode sequence fasta file.

That said, it never worked properly so I'll take it out.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 21 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 22 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Sounds good.  Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 23 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 24 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: No... this is leftover from a previous fix for the reference context field.  I'll remove it.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 25 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Part of that `todo` was leftover from another note I had previously.  I've updated it with a better explanation.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 26 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Oh, there's plenty more. :P

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java (hunk 35 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Sounds good.  Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 45]
```diff
@@ -1120,85 +1402,55 @@ static SequenceComparison createSequenceComparison(final VariantContext variant,
...
+                                                       final boolean processSequenceInformation) {
 
         final SequenceComparison sequenceComparison = new SequenceComparison();
 
         // Get the contig:
         sequenceComparison.setContig(variant.getContig());
 
         // Get the strand:
-        final Strand strand = Strand.decode( transcript.getGenomicStrand().toString() );
+        final Strand strand = Strand.decode(transcript.getGenomicStrand().toString());
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: It seems unnecessary to go through string here.  It seems like it would be more efficient to have a direct conversion method.    It's also generally a sketchy idea to use toString to encode things like this, toString is generally meant as a human readable form, and we don't like to rely on it producing specific results.  Better to have an encode() method even if it matches the toString.

File: src/main/java/org/broadinstitute/hellbender/engine/ReferenceDataSource.java (hunk 39 above)
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/engine/ReferenceDataSource.java]: Oh.  Sure!

Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java (hunk 33 above)
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: @pshapiro4broad Good suggestion.  I'll change it to do this.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 45 above)
Comment (lbergelson) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: While I was looking at this, I noticed some sort of strange patterns  GencodeGtfFeature.

ex:
```
 public enum GenomicPhase {
   
        public static GenomicPhase getEnum(final String s) {
            for( final GenomicPhase val : values() ) {
                if(val.serialized.equalsIgnoreCase(s)) {
                    return val;
                }
            }
            throw new IllegalArgumentException("Unexpected value: " + s);
        }
    }
```

You've added your own `getEnum(String s)` method.  There's a built in method valueOf() which does this already (although it doesn't ignore case).  It might make sense to normalize the case of everything before passing it in and use that.  Alternatively, if you're implementing this, you don't want to call `values()` repeatedly.  Every call to `values()` allocates a new array which is pretty expensive, you should cache it in a private variable and use that.

Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: That's fair.

In the future I'd like to refactor this to use the built-in `Strand` type, rather than the one I made for the `GencodeFuncotationFactory`.

Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: I made those enum patterns because I needed a serialization method where I could ignore the case of the enums before conversion.

I'll pull out the `values()` calls.  I'll need to think about case normalization.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 46]
```diff
@@ -0,0 +1,733 @@
...
+
+    //==================================================================================================================
+    // Instance Methods:
+
+    /**
+     * Ensures each value in the given {@code outputMap} is compliant with MAF-expected values.
+     * @param outputMap The {@link Map} of output field -> values to be checked for MAF compliance.
+     * @return A {@link LinkedHashMap} of output field strings -> values to be written to the MAF file.
+     */
+    private LinkedHashMap<String, String> replaceFuncotationValuesWithMafCompliantValues(final Map<String, Object> outputMap ) {
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: I think there should be unit tests for this, and for the `write`.  That probably means extracting a method from within write that returns the output string , or the array of things to write instead actually writing to disk.  I think at a minimum we need a test to show that we're correctly handling  deletion and insertion alleles.  As well as basic conversion, defaulting, and overriding is working.  We don't need exhaustive tests for every case right now, but there should be something.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 45 above)
Comment (lbergelson) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: yeah, it makes sense if you need to ignore the case.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 47]
```diff
@@ -1330,29 +1607,35 @@ private static GencodeFuncotationBuilder createGencodeFuncotationBuilderWithTriv
...
                  .setChromosome(gtfFeature.getChromosomeName())
-                 .setStart(variant.getStart());
+                 .setStart(variant.getStart())
+                 .setGeneTranscriptType(gtfFeature.getTranscriptType());
 
          // The end position is inclusive, so we need to make sure we don't double-count the start position (so we subtract 1):
          gencodeFuncotationBuilder.setEnd(variant.getStart() + altAllele.length() - 1)
                  .setVariantType(getVariantType(variant.getReference(), altAllele))
-                 .setTumorSeqAllele1(altAllele.getBaseString())
+                 .setTumorSeqAllele1(variant.getReference().getBaseString())
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: There is already a `refAllele` field.

I think it might make sense just to remove the `tumorSeqAllele1` field and only output it on serialization, since it's just the ref allele.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 48]
```diff
@@ -1362,7 +1645,13 @@ private static GencodeFuncotationBuilder createGencodeFuncotationBuilderWithTriv
 
          // Get the length of the transcript:
          // NOTE: We add 1 because of genomic cordinates:
-         gencodeFuncotationBuilder.setTranscriptLength( transcript.getEnd() - transcript.getStart() + 1);return gencodeFuncotationBuilder;
+        gencodeFuncotationBuilder.setTranscriptLength(
+                transcript.getExons().stream()
+                .mapToInt(e -> e.getEnd() - e.getStart() + 1) // Add 1 because it's inclusive.
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Cool.  Sounds good.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 49]
```diff
@@ -1642,19 +2024,32 @@ else if ( a.getVariantClassification().getSeverity() > b.getVariantClassificatio
                 return 1;
             }
 
-            // 3)
+            // 2a) Is it protein coding?
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: I'll build some other comparator objects and chain them together.  I think it's cleaner.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/LocatableXsvFuncotationFactory.java [hunk 50]
```diff
@@ -117,57 +176,87 @@ public String getName() {
...
+                        final int startColumn    = Integer.valueOf(configProperties.getProperty(XsvLocatableTableCodec.CONFIG_FILE_START_COLUMN_KEY));
+                        final int endColumn      = Integer.valueOf(configProperties.getProperty(XsvLocatableTableCodec.CONFIG_FILE_END_COLUMN_KEY));
+                        final String delimiter      = configProperties.getProperty(XsvLocatableTableCodec.CONFIG_FILE_DELIMITER_KEY);
+                        final String dataSourceName = configProperties.getProperty(XsvLocatableTableCodec.CONFIG_FILE_DATA_SOURCE_NAME_KEY);
+
+                        // Create our index to remove list:
+                        final Set<Integer> indicesToRemove = new HashSet<>(Arrays.asList(contigColumn, startColumn, endColumn));
+
+                        // Get the raw header:
+                        List<String> header = null;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/LocatableXsvFuncotationFactory.java]: Sounds good!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/SimpleKeyXsvFuncotationFactory.java [hunk 51]
```diff
@@ -184,11 +202,25 @@ public String getName() {
...
+                // Create 1 annotation for each alt allele and add our annotations to the list:
+                for ( final Allele altAllele : variant.getAlternateAlleles() ) {
+                    outputFuncotations.add(new TableFuncotation(annotationColumnNames, annotations, altAllele, name));
+                    annotatedAltAlleles.add(altAllele);
+                }
+            }
+
+            // If we didn't add funcotations for an allele, we should add in blank funcotations to that allele for
+            // each field that can be produced by this SimpleKeyXsvFuncotationFactory:
+            if ( annotatedAltAlleles.size() != variant.getAlternateAlleles().size() ) {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/xsv/SimpleKeyXsvFuncotationFactory.java]: Interesting.

Sounds good.  Fixed!

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 52]
```diff
@@ -17,111 +23,434 @@
...
         arguments.add("-" + StandardArgumentDefinitions.OUTPUT_SHORT_NAME);
         arguments.add(outputFile.getAbsolutePath());
+        arguments.add("-" + FuncotatorArgumentDefinitions.OUTPUT_FORMAT_LONG_NAME);
+        arguments.add(outputFormatType.toString());
 
         runCommandLine(arguments);
     }
 
-    @Test(enabled = false)
+    @Test(enabled = doDebugTests)
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Yes.  This test is here so I can easily go through debug cycles interactively with Lee to see what the differences are between my output and Oncotator output.

My plan is to roll these special cases into a larger set of integration tests with validation (providing that I can actually release these data files).

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 53]
```diff
@@ -17,111 +23,434 @@
...
+    private static void addManualAnnotationsToArguments(final List<String> arguments) {
+
+        // ================================================================================
+        // Annotation Defaults:
+        arguments.add("--" + FuncotatorArgumentDefinitions.ANNOTATION_DEFAULTS_LONG_NAME);
+        arguments.add("dbSNP_RS:0");
+        arguments.add("--" + FuncotatorArgumentDefinitions.ANNOTATION_DEFAULTS_LONG_NAME );
+        arguments.add("dbSNP_Val_Status:No Value");
+
+        arguments.add("--" + FuncotatorArgumentDefinitions.ANNOTATION_DEFAULTS_LONG_NAME);
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Sounds good.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java [hunk 54]
```diff
@@ -687,13 +687,13 @@ private static ReferenceContext referenceHelperForTestCalculateGcContent(final S
...
                         createFuncotationForTestGencodeFuncotationComparatorUnitTest(transcriptId2 + ".5", GencodeGtfFeature.FeatureTag.APPRIS_PRINCIPAL, 2, GencodeFuncotation.VariantClassification.THREE_PRIME_UTR, 5000),
-                        -1
+                        1
                 },
                 {
                         new GencodeFuncotationFactory.BestEffectGencodeFuncotationComparator(transcriptSet),
                         createFuncotationForTestGencodeFuncotationComparatorUnitTest(transcriptId1 + ".5", GencodeGtfFeature.FeatureTag.APPRIS_PRINCIPAL, 2, GencodeFuncotation.VariantClassification.THREE_PRIME_UTR, 5000),
                         createFuncotationForTestGencodeFuncotationComparatorUnitTest(transcriptId2 + ".5", GencodeGtfFeature.FeatureTag.APPRIS_PRINCIPAL, 1, GencodeFuncotation.VariantClassification.THREE_PRIME_UTR, 5000),
-                        1
+                        -1
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactoryUnitTest.java]: Yeah - I reviewed the comparators with @LeeTL1220 and they needed to be swapped to have correct behavior.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRendererUnitTest.java [hunk 55]
```diff
@@ -0,0 +1,26 @@
+package org.broadinstitute.hellbender.tools.funcotator.mafOutput;
+
+import org.broadinstitute.hellbender.GATKBaseTest;
+
+/**
+ * Unit test class for the {@link MafOutputRenderer}.
+ * Created by jonn on 1/22/18.
+ */
+public class MafOutputRendererUnitTest extends GATKBaseTest {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRendererUnitTest.java]: True.

I made the unit test class when I built the class initially, but haven't populated it. 

I'll add simple unit tests for writing a small piece of output to make sure the mechanics are tested.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java (hunk 46 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Fair point.  I'll add the tests when I build out the `MafOutputRendererUnitTest`.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gencode/GencodeGtfFeature.java [hunk 56]
```diff
@@ -763,6 +763,8 @@ public GencodeGtfFeature create(final String[] gtfFields) {
             }
         };
 
+        private static final FeatureType[] valueArray = values();
```
Comment (pshapiro4broad) [inline src/main/java/org/broadinstitute/hellbender/utils/codecs/gencode/GencodeGtfFeature.java]: Java code conventions are to use all uppercase for static final fields, e..g `VALUES`

Also, I'm not sure why you need to create a static array for this object. If you want to converting from string very fast, you could use a static `Map`.

Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gencode/GencodeGtfFeature.java]: I wanted bi-directional conversion (string <-> enum) without case sensitivity, so this seemed fairly straightforward.  I can refactor to use a `Map`.

I have no problem renaming the field to `VALUEMAP` once the above refactor is complete.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 57]
```diff
@@ -0,0 +1,733 @@
...
+    public static String VERSION = "2.4";
+
+    //==================================================================================================================
+    // Private Static Members:
+
+    /**
+     * Default set of columns to include in this {@link MafOutputRenderer}.
+     * Order of the columns is preserved by the {@link LinkedHashMap}, while still being able to access each field via
+     * the associated key.
+     */
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Yup.  Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 58]
```diff
@@ -0,0 +1,733 @@
...
+                    }
+                }
+                if (isAliasedName) {
+                    it.remove();
+                }
+            }
+        }
+
+        // Set values for unused fields:
+        defaultMap.put(MafOutputRendererConstants.FieldName_Score, MafOutputRendererConstants.UNUSED_STRING);
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: There are a lot of those constants... 

I think I'm gonna leave in the full class reference - I prefer to be explicit.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 59]
```diff
@@ -0,0 +1,733 @@
...
+
+        // Cache the manual annotation string so we can pass it easily into any Funcotations:
+        manualAnnotationSerializedString = (manualAnnotations.size() != 0 ? MafOutputRendererConstants.FIELD_DELIMITER + String.join( MafOutputRendererConstants.FIELD_DELIMITER, manualAnnotations.values() ) + MafOutputRendererConstants.FIELD_DELIMITER : "");
+    }
+
+    //==================================================================================================================
+    // Override Methods:
+
+    @Override
+    public void open() {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: I designed the `OutputRenderer` class to have `open`/`close`/`write` methods so they could later be extended flexibly.  

I'll pull the `Open` method out of the `OutputRenderer`.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 60]
```diff
@@ -0,0 +1,733 @@
...
+            printWriter = new PrintWriter(Files.newOutputStream(outputFilePath));
+        }
+        catch (final IOException ex) {
+            throw new UserException("Error opening output file path: " + outputFilePath.toUri().toString(), ex);
+        }
+    }
+
+    @Override
+    public void close() {
+        printWriter.flush();
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Sounds good.  Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 61]
```diff
@@ -0,0 +1,733 @@
...
+            writeLine(
+                    mafCompliantOutputMap.values().stream().collect(Collectors.joining(MafOutputRendererConstants.FIELD_DELIMITER))
+                    + manualAnnotationSerializedString
+            );
+        }
+    }
+
+
+    //==================================================================================================================
+    // Static Methods:
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Sounds good.  I generally like to leave them in so that when I create methods / fields that go in the blocks there is an obvious place in which to put them.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 62]
```diff
@@ -0,0 +1,733 @@
...
+            final LinkedHashMap<String, String> mafCompliantOutputMap = replaceFuncotationValuesWithMafCompliantValues(outputMap);
+
+            // Write our header if we have to:
+            if ( ! hasWrittenHeader ) {
+                writeHeader(mafCompliantOutputMap);
+            }
+
+            // Write the output (with manual annotations at the end):
+            writeLine(
+                    mafCompliantOutputMap.values().stream().collect(Collectors.joining(MafOutputRendererConstants.FIELD_DELIMITER))
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: I'll just update it now.  It's not a big deal to iterate through and write them.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 63]
```diff
@@ -0,0 +1,733 @@
...
+            case MafOutputRendererConstants.FieldName_Chromosome:
+                if ( value.equals(MafOutputRendererConstants.FieldValue_Gencode_Chromosome_Mito) ) {
+                    return MafOutputRendererConstants.FieldValue_Chromosome_Mito;
+                }
+                else if ( value.startsWith("chr") ) {
+                    return value.substring(3);
+                }
+                break;
+            case MafOutputRendererConstants.FieldName_Other_Transcripts:
+                return value.replaceAll( GencodeFuncotation.VariantClassification.IN_FRAME_DEL.toString(),        MafOutputRendererConstants.VariantClassificationMap.get(GencodeFuncotation.VariantClassification.IN_FRAME_DEL.toString()) )
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Yup - Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java [hunk 64]
```diff
@@ -0,0 +1,733 @@
...
+            outputMap.put(key, MafOutputRendererConstants.UNKNOWN_VALUE_STRING);
+        }
+    }
+
+    /**
+     * Write the given line to the {@link #printWriter}.
+     * @param line The {@link String} to write as a line to the {@link #printWriter}.
+     */
+    private void writeLine(final String line) {
+        printWriter.write(line + System.lineSeparator());
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/mafOutput/MafOutputRenderer.java]: Fixed!

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/vcfOutput/VcfOutputRenderer.java [hunk 65]
```diff
@@ -116,31 +155,29 @@ public void write(final VariantContext variant, final List<Funcotation> funcotat
...
+     * Includes fields from the manual annotation maps.
      * @return The {@link VCFHeader} object with relevant information for {@link Funcotator}.
      */
-    private static VCFHeader createVCFHeader(final VCFHeader existingHeader,
-                                             final List<DataSourceFuncotationFactory> dataSourceFactories,
-                                             final LinkedHashMap<String, String> manualAnnotations) {
+    private VCFHeader createVCFHeader() {
 
-        final Set<VCFHeaderLine> headerLines = new HashSet<>();
+        final Set<VCFHeaderLine> headerLines = new LinkedHashSet<>();
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/vcfOutput/VcfOutputRenderer.java]: Thanks.  They need to be ordered for output, so I wanted to make sure they would stay that way :P

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 66]
```diff
@@ -17,111 +23,434 @@
...
 
-    //TODO: Add checks on the output file.
+    //TODO: SUPER IMPORTANT! Add checks on the output file to make sure it's equal to an expected output file!
+
+    // Temp directory in which to place output files.
+    private static final File tmpOutDir;
+
+    // Whether to do debug output (i.e. leave output around).
+    // This should always be true when checked in.
+    private static final boolean doDebugTests = false;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Out of date documentation.  Fixed!

File: src/main/java/org/broadinstitute/hellbender/utils/fasta/CachingIndexedFastaSequenceFile.java [hunk 67]
```diff
@@ -175,15 +170,57 @@ public static CachingIndexedFastaSequenceFile checkAndCreate(final Path fastaPat
...
+    }
+
+    /**
+     * Create reference data source from fasta file, after performing several preliminary checks on the file.
+     * This static utility was refactored from the constructor of ReferenceDataSource.
+     * Possibly may be better as an overloaded constructor.
+     * @param fastaPath Fasta file to be used as reference
+     * @return A new instance of a CachingIndexedFastaSequenceFile.
+     */
+    public static CachingIndexedFastaSequenceFile checkAndCreate(final Path fastaPath) {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/fasta/CachingIndexedFastaSequenceFile.java]: It sure can!

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 68]
```diff
@@ -17,111 +23,434 @@
  */
 public class FuncotatorIntegrationTest extends CommandLineProgramTest {
 
-    //TODO: Add checks on the output file.
+    //TODO: SUPER IMPORTANT! Add checks on the output file to make sure it's equal to an expected output file!
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Still outstanding.

I need to create more tests that do proper verification.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 69]
```diff
@@ -17,111 +23,434 @@
...
+            if ( !tmpOutDir.mkdirs() && !tmpOutDir.exists() ) {
+                throw new GATKException("Error making output folder for test: " + FuncotatorIntegrationTest.class.getName());
+            }
+        }
+    }
+
+    //==================================================================================================================
+    // Helper methods to create output files and maybe leave them around to debug the test output.
+
+    private static File getOutputFile(final FuncotatorArgumentDefinitions.OutputFormatType outputFormatType) {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Yeah - that sounds good.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 70]
```diff
@@ -256,14 +251,14 @@
             optional = true,
             doc = "Whether to ignore variants that have been filtered or to annotate them."
     )
-    protected boolean ignoreFilteredVariants = FuncotatorArgumentDefinitions.IGNORE_FILTERED_VARIANTS_DEFFAULT_VALUE;
+    protected boolean ignoreFilteredVariants = true;
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: This value switched from false -> true didn't it?  Typically if we have a boolean commandline option we want to to always be false by default.  ItSo if you want the default to be true here it's probably best to switch it to "includeFilteredVariants" and invert it.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java [hunk 71]
```diff
@@ -377,6 +379,14 @@ public void apply(final VariantContext variant, final ReadsContext readsContext,
                         "There MAY be some errors in the Y chromosome due to changes between the two references.");
             }
         }
+    }
+
+    @Override
+    public void apply(final VariantContext variant, final ReadsContext readsContext, final ReferenceContext referenceContext, final FeatureContext featureContext) {
+
+        if ( !referenceContext.hasBackingDataSource() ) {
+            throw new GATKException("No reference context for variant.  Cannot annotate!");
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: It shouldn't.

I didn't realize that would prevent this case from happening.  I'll take out the check.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java [hunk 72]
```diff
@@ -0,0 +1,490 @@
...
+import java.nio.file.*;
+import java.util.*;
+import java.util.stream.Collectors;
+
+/**
+ * Utilities for reading / working with / manipulating Data Sources.
+ * Designed to be a static utility class with no state.
+ * Created by jonn on 3/8/18.
+ */
+public class DataSourceUtils {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java]: 👍

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java [hunk 73]
```diff
@@ -0,0 +1,490 @@
...
+                throw new UserException("ERROR: Directory contains more than one config file: " + directory.toUri().toString());
+            }
+            else if ( configFileSet.size() == 0 ) {
+                throw new UserException("ERROR: Directory does not contain a config file: " + directory.toUri().toString());
+            }
+
+            return configFileSet.get(0);
+        }
+        catch (final IOException ex) {
+            throw new GATKException("Unable to read contents of: " + directory.toUri().toString());
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java]: Sounds good.  I forgot to add the exception to the throw.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java [hunk 74]
```diff
@@ -0,0 +1,490 @@
...
+
+            logger.debug("Creating Funcotation Factory for " + entry.getValue().getProperty("name") + " ...");
+
+            final DataSourceFuncotationFactory funcotationFactory;
+
+            // Note: we need no default case since we know these are valid:
+            final String stringType = entry.getValue().getProperty("type");
+            switch ( FuncotatorArgumentDefinitions.DataSourceType.getEnum(stringType) ) {
+                case LOCATABLE_XSV:
+                    funcotationFactory = DataSourceUtils.createLocatableXsvDataSource(entry.getKey(), entry.getValue(), annotationOverridesMap);
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java]: Sure.  Sounds good.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java [hunk 75]
```diff
@@ -0,0 +1,490 @@
...
+
+    /**
+     * Create a {@link LocatableXsvFuncotationFactory} from filesystem resources and field overrides.
+     * @param dataSourceFile {@link Path} to the data source file.  Must not be {@code null}.
+     * @param dataSourceProperties {@link Properties} consisting of the contents of the config file for the data source.  Must not be {@code null}.
+     * @param annotationOverridesMap {@link LinkedHashMap}{@code <String->String>} containing any annotation overrides to be included in the resulting data source.  Must not be {@code null}.
+     * @return A new {@link LocatableXsvFuncotationFactory} based on the given data source file information and field overrides map.
+     */
+    public static LocatableXsvFuncotationFactory createLocatableXsvDataSource(final Path dataSourceFile,
+                                                                              final Properties dataSourceProperties,
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java]: I want to make these files Owner readable in the future, so I'm going to wait on this one.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java [hunk 76]
```diff
@@ -0,0 +1,490 @@
...
+            type = FuncotatorArgumentDefinitions.DataSourceType.getEnum(stringType);
+        }
+        catch (final IllegalArgumentException ex) {
+            throw new UserException.BadInput("ERROR in config file: " + configFilePath.toUri().toString() +
+                    " - Invalid value in \"" + CONFIG_FILE_FIELD_NAME_TYPE + "\" field: " + stringType, ex);
+        }
+
+        // Validate remaining values based on type:
+        switch (type) {
+            case LOCATABLE_XSV: assertLocatableXsvConfigFilePropertiesAreValid(configFileProperties, configFilePath); break;
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/DataSourceUtils.java]: That's a good idea.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java [hunk 77]
```diff
@@ -183,7 +181,8 @@ public String serializeToVcfString() {
                 (secondaryVariantClassificationSerializedOverride != null ? secondaryVariantClassificationSerializedOverride : (secondaryVariantClassification != null ? secondaryVariantClassification : "")) + DELIMITER +
                 (variantTypeSerializedOverride != null ? variantTypeSerializedOverride : (variantType != null ? variantType : "")) + DELIMITER +
                 (refAlleleSerializedOverride != null ? refAlleleSerializedOverride : (refAllele != null ? refAllele : "")) + DELIMITER +
-                (tumorSeqAllele1SerializedOverride != null ? tumorSeqAllele1SerializedOverride : (tumorSeqAllele1 != null ? tumorSeqAllele1 : "")) + DELIMITER +
+                // NOTE: Ref allele gets serialized as the tumorSeqAllele1 as well, but we have to account for the override:
+                (tumorSeqAllele1SerializedOverride != null ? tumorSeqAllele1SerializedOverride : (refAllele != null ? refAllele : "")) + DELIMITER +
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java]: You're welcome :)

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gencode/GencodeGtfFeature.java [hunk 78]
```diff
@@ -794,38 +816,6 @@ public static FeatureType getEnum(final String s) {
...
     }
 
-    /**
-     * The strand of DNA from which a given feature was read.
-     *
-     * For more information, see:
-     *     https://www.gencodegenes.org/data_format.html
-     *     https://en.wikipedia.org/wiki/General_feature_format
-     */
-    public enum GenomicStrand {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gencode/GencodeGtfFeature.java]: Yeah -  I didn't look for when when I initially made it.  Ever since I found out one existed I've wanted to remove it.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 79]
```diff
@@ -1102,20 +1039,16 @@ private GencodeFuncotation createUtrFuncotation(final VariantContext variant,
...
-        final Strand strand = Strand.decode( transcript.getGenomicStrand().toString() );
-        FuncotatorUtils.assertValidStrand(strand);
-
         // Get the strand-corrected alleles from the inputs.
         // Also get the reference sequence for the variant region.
         // (spanning the entire length of both the reference and the variant, regardless of which is longer).
-        final Allele strandCorrectedRefAllele = FuncotatorUtils.getStrandCorrectedAllele(variant.getReference(), strand);
-        final Allele strandCorrectedAltAllele = FuncotatorUtils.getStrandCorrectedAllele(altAllele, strand);
-        final String referenceBases = getReferenceBases(variant.getReference(), altAllele, reference, strand);
+        final Allele strandCorrectedRefAllele = FuncotatorUtils.getStrandCorrectedAllele(variant.getReference(), transcript.getGenomicStrand());
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Fixed!

File: src/main/java/org/broadinstitute/hellbender/utils/test/ArgumentsBuilder.java [hunk 80]
```diff
@@ -38,13 +38,23 @@ public ArgumentsBuilder(Object[] args){
     public ArgumentsBuilder add(String arg){
         List<String> chunks = Arrays.asList(StringUtils.split(arg.trim()));
         for (String chunk : chunks){
-            if(chunk.contains("=")){
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/test/ArgumentsBuilder.java]: None of the tests seem to fail with this removed, so it seems OK.

Added issue #4550 to investigate.

File: src/main/java/org/broadinstitute/hellbender/utils/test/ArgumentsBuilder.java [hunk 81]
```diff
@@ -114,6 +124,17 @@ public ArgumentsBuilder addArgument(final String argumentName, final String argu
         return this;
     }
 
+    /**
+     * Add an argument with a given value to this builder without processing the value string.
+     */
+    public ArgumentsBuilder addArgumentWithRawValue(final String argumentName, final String argumentValue) {
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/test/ArgumentsBuilder.java]: Sounds good.

File: src/main/java/org/broadinstitute/hellbender/utils/test/ArgumentsBuilder.java [hunk 82]
```diff
@@ -38,13 +38,23 @@ public ArgumentsBuilder(Object[] args){
...
-            else{
-                args.add(chunk);
-            }
+            addRaw(chunk);
+        }
+        return this;
+    }
+
+    /**
+     * Add a string to the arguments list without processing the string itself.
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/test/ArgumentsBuilder.java]: 👍

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java (hunk 70 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/Funcotator.java]: Sounds good.  I switched it because my understanding is that this is the default operating mode.

File: src/main/java/org/broadinstitute/hellbender/engine/ReferenceDataSource.java [hunk 83]
```diff
@@ -28,6 +27,21 @@ public static ReferenceDataSource of(final Path fastaPath) {
         return new ReferenceFileSource(fastaPath);
     }
 
+    /**
+     * Initialize this data source using a fasta file.
+     *
+     * The provided fasta file must have companion .fai and .dict files.
+     *
+     * If {@code preserveFileBases} is {@code true}, will NOT convert IUPAC bases in the file to `N` and will NOT capitalize lower-case bases.
```
Comment (pshapiro4broad) [inline src/main/java/org/broadinstitute/hellbender/engine/ReferenceDataSource.java]: Javadoc doesn't match code, this parameter doesn't appear in the method signature.

Also note that javadoc doesn't preserve newlines in its output. If you want newlines between text in Javadoc, put a `<p>` tag on each empty line.
