### PR TITLE
Fixed bugs and simplified AlleleLikelihoods evidence-to-index cache

### LINKED ISSUE #6586: Bug in HaplotypeCaller 'evidence provided is not in sample'
### Instructions

In one of the six samples that the DSP pipelines team ('lantern') uses for scientific testing, found bug in GATK 4.1.7.0's HaplotypeCaller.  'java.lang.IllegalArgumentException: evidence provided is not in sample'.  Full stack trace below.

This is found for Sample NA17-308, Shard 49.
https://cromwell.gotc-dev.broadinstitute.org/api/workflows/1/83938362-b9b5-49f3-a65d-715065d6eabd/metadata
Execution bucket is:
broad-gotc-dev-cromwell-execution (results will stay there for 30 days before being automatically cleaned up).

----

### Affected tool(s) or class(es)
HaplotypeCaller

### Affected version(s)
- 4.1.7.0

### Description 
Stack trace:
java.lang.IllegalArgumentException: evidence provided is not in sample
	at org.broadinstitute.hellbender.utils.genotyper.AlleleLikelihoods.lambda$removeEvidence$9(AlleleLikelihoods.java:1124)
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.IntPipeline.toArray(IntPipeline.java:504)
	at org.broadinstitute.hellbender.utils.genotyper.AlleleLikelihoods.removeEvidence(AlleleLikelihoods.java:1128)
	at org.broadinstitute.hellbender.utils.genotyper.AlleleLikelihoods.contaminationDownsampling(AlleleLikelihoods.java:315)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.assignGenotypeLikelihoods(HaplotypeCallerGenotypingEngine.java:173)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:608)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:210)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) or class(es) involved
_Tool/class name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) or class(es) involved
_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #6586.  @droazen 

`AlleleLikelihoods` caches the evidence-to-index `Map`.  The previous implementation tried to update this map on the fly whenever evidence was removed.  The new approach is to simply invalidate the cache and allow the existing code to generate it to run later.

I don't expect this to cause performance problems for a few reasons:

1.  It only applies when we're doing contamination downsampling.
2.  It may save time whenever evidence is removed and we don't need the evidence-to-index map later.
3.  Regenerating the cache is O(N), but so is updating on-the-fly even when only one read is removed.

### CODE REVIEW

**Comment by droazen** [comment]
@jamesemery and @vruano , could you two review when you get a chance? Thanks!

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 1]
```diff
@@ -1129,60 +1129,45 @@ private void removeEvidence(final int sampleIndex, final Collection<EVIDENCE> ev
...
-                    }
+                newEvidence.add(oldEvidence.get(n));
+            }
+        }
+        Utils.validate(newEvidence.size() == newEvidenceCount, "Indices to remove contained duplicates, was not ordered, or contained out-of-range indices.");
+        evidenceBySampleIndex.set(sampleIndex, newEvidence);
+        numberOfEvidences[sampleIndex] = newEvidenceCount;
+
+        //  invalidate the cached evidence to index map
+        evidenceIndexBySampleIndex.set(sampleIndex, null);
```
[the remark this answers is not in the document]
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1158]: Done, but I didn't call the invalidate method for the case of adding evidence, for which updating the cache on the fly is easy.

And I could just be really tired but I don't think there are any methods to add or remove samples.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 2]
```diff
@@ -1129,60 +1129,45 @@ private void removeEvidence(final int sampleIndex, final Collection<EVIDENCE> ev
         removeEvidenceByIndex(sampleIndex, indexesToRemove);
     }
 
+    // remove evidence and unset the {@code evidenceIndexBySampleIndex} Map for this sample
```
[the remark this answers is not in the document]
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1132]: done

**Comment by davidbenjamin** [comment]
> At the very least we should add a unit test that generates the evidenceIndexBySampleIndex cache, then calls marginalize() (both types) and asserts that we have emptied the cache. I would do the same for appendEvidence() and addMissingAlleles()

It's simpler than this because allele operations such as `marginalize()` and `addMissingAlleles` don't modify the evidence list.  While they require care with the likelihoods arrays they don't require anything at all from the evidence-to-index caches.  As I mentioned above, I left the cache updating in `appendEvidence` as it was because it was so simple.

I will try to write the test for removing evidence tomorrow.  Tempting to try tonight, but I'm trying to accept the reality that working until 2 am is a bad idea.

**Comment by davidbenjamin** [comment]
Back to @jamesemery.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 3]
```diff
@@ -758,46 +759,28 @@ private void extendsLikelihoodArrays(final double initialLikelihood, final int s
...
-            } else {
-                actuallyAdded = new ArrayList<>(newSampleEvidence.subList(0, i));
-                i++; // skip the repeated element.
-                break;
-            }
-        }
-        // second for below only use if we encounter some evidence that is already in the table:
-        for (; i < stop; i++) {
-            final EVIDENCE newEvidence = newSampleEvidence.get(i);
+        int nextIndex = sampleEvidence.size();
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:771]: You just calculated that values when initializing `previousEvidenceCount` why not simply reuse it here:
```int nextIndex = previousEvidenceCount;```

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 4]
```diff
@@ -758,46 +759,28 @@ private void extendsLikelihoodArrays(final double initialLikelihood, final int s
...
             if (previousValue == MISSING_INDEX) {
                 nextIndex++;
                 sampleEvidence.add(newEvidence);
-                actuallyAdded.add(newEvidence);
             } else {
                 sampleEvidenceIndex.put(newEvidence, previousValue); // revert
             }
         }
+
         numberOfEvidences[sampleIndex] = sampleEvidence.size();
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:782]: ```nextIndex``` contains the value you need here.
perhaps it would be better to call this variable ```currentSize```

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 5]
```diff
@@ -758,46 +759,28 @@ private void extendsLikelihoodArrays(final double initialLikelihood, final int s
...
-        return actuallyAdded;
+        return sampleEvidence.size() - previousEvidenceCount;
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:783]: ```return nextIndex - previousEvidenceCount;```

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 6]
```diff
@@ -1129,60 +1112,50 @@ private void removeEvidence(final int sampleIndex, final Collection<EVIDENCE> ev
...
-            if (newEvidenceCount < 0) {
-                throw new IllegalStateException("attempt to remove non-existent evidence or repeated evidence");
-            } else if (newEvidenceCount == 0) { // taking in consideration the assumption we simply remove
-                // all evidence.
-                evidenceIndex.clear();
-                numberOfEvidences[sampleIndex] = 0;
+        }
+        final int oldEvidenceCount = numberOfEvidences[sampleIndex];
+        final int newEvidenceCount = oldEvidenceCount - evidencesToRemove.length;
+        Utils.validate(newEvidenceCount >= 0, "attempted to remove non-existent evidence or repeated evidence");
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1124]: This method is ```private``` do we really need to check this, can we simply assume the input is correct?

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 7]
```diff
@@ -1129,60 +1112,50 @@ private void removeEvidence(final int sampleIndex, final Collection<EVIDENCE> ev
...
+
+        // update the list of evidence and evidence count
+        final List<EVIDENCE> oldEvidence = evidenceBySampleIndex.get(sampleIndex);
+        final List<EVIDENCE> newEvidence = new ArrayList<>(newEvidenceCount);
+        for (int n = 0, numRemoved = 0; n < oldEvidenceCount; n++) {
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1129]: You can be a bit more efficient by putting the next to skip "on-deck":

```
for (int n = 0, numRemoved = 0, nextToRemove = evidencesToRemove[0]; n < oldEvidenceCount; n++) {
     if (n == nextToRemove) {
         nextToRemove = ++numRemoved < evidencesToRemove.length ? evidencesToRemove[numRemoved] : -1;
     } else {
         newEvidence.add(oldEvidence.get(n));
     }
}
```

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 8]
```diff
@@ -1129,60 +1112,50 @@ private void removeEvidence(final int sampleIndex, final Collection<EVIDENCE> ev
...
-                    for (int etrIndex = 1, to = evidencesToRemove[0], from = to + 1; to < newEvidenceCount; from++, etrIndex++) {
-                        nextIndexToRemove = etrIndex < evidencesToRemove.length ? evidencesToRemove[etrIndex] : oldEvidenceCount;
-                        for (; from < nextIndexToRemove; from++) {
-                            alleleValues[to++] = alleleValues[from];
-                        }
-                    }
+                newEvidence.add(oldEvidence.get(n));
+            }
+        }
+        Utils.validate(newEvidence.size() == newEvidenceCount, "Indices to remove contained duplicates, was not ordered, or contained out-of-range indices.");
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1136]: Again a ```private``` does not need to perform this checks... This is something that must be cached by unit tests, perhaps you should increase testing coverage if you are worried that this is a real issue.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 9]
```diff
@@ -1129,60 +1112,50 @@ private void removeEvidence(final int sampleIndex, final Collection<EVIDENCE> ev
...
+
+        invalidateEvidenceToIndexCache(sampleIndex);
+
+        // update the likelihoods arrays in place
+        for (final double[] alleleValues : valuesBySampleIndex[sampleIndex]) {
+            for (int n = 0, numRemoved = 0; n < oldEvidenceCount; n++) {
+                if (numRemoved < numToRemove && n == evidencesToRemove[numRemoved]) {
+                    numRemoved++;
+                } else {
+                    alleleValues[n - numRemoved] = alleleValues[n];
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1148]: why we have two for loops that seem to do pretty much the same. Can we simply move this line of code to the ```for``` loop above?... I mean:

```
for (...) {
   if (n == nextToRemove) {
     ...
   } else {
     ...
     for (final double[] alleleValues : valuesBySampleIndex[sampleIndex]) {
          alleleValues[n - numRemoved] = alleleValues[n];
     }
   }
```

Otherwise if you want to keep it this way, you could start the loop on the first removed-index:

```
   for (int n = evidencesToRemove[0] + 1, ...; n < oldEvidenceCount; n++) {
       ...
   }
```

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 10]
```diff
@@ -1216,18 +1189,26 @@ public void filterPoorlyModeledEvidence(final ToDoubleFunction<EVIDENCE> log10Mi
...
-            final Object2IntMap<EVIDENCE> index = new Object2IntOpenHashMap<>(sampleEvidenceCount);
-            index.defaultReturnValue(MISSING_INDEX);
-            evidenceIndexBySampleIndex.set(sampleIndex, index);
-            for (int r = 0; r < sampleEvidenceCount; r++) {
-                index.put(sampleEvidence.get(r), r);
-            }
-            return index;
-        } else {
-            return evidenceIndexBySampleIndex.get(sampleIndex);
+            fillEvidenceToIndexCache(sampleIndex);
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1192]: You can avoid the double ```get``` if the index map is not null, but is just a direct get acces to an array-list so perhaps not worth the trouble.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 11]
```diff
@@ -1216,18 +1189,26 @@ public void filterPoorlyModeledEvidence(final ToDoubleFunction<EVIDENCE> log10Mi
...
+        return evidenceIndexBySampleIndex.get(sampleIndex);
+    }
+
+    @VisibleForTesting
+    void fillEvidenceToIndexCache(int sampleIndex) {
+        final List<EVIDENCE> sampleEvidence = evidenceBySampleIndex.get(sampleIndex);
+        final int sampleEvidenceCount = sampleEvidence.size();
+        final Object2IntMap<EVIDENCE> index = new Object2IntOpenHashMap<>(sampleEvidenceCount);
+        index.defaultReturnValue(MISSING_INDEX);
+        evidenceIndexBySampleIndex.set(sampleIndex, index);
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1203]: We are not multithread safe in general but as a matter of principle I think you should only set the list once the map is filled and not before.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 12]
```diff
@@ -1216,18 +1189,26 @@ public void filterPoorlyModeledEvidence(final ToDoubleFunction<EVIDENCE> log10Mi
...
+        for (int r = 0; r < sampleEvidenceCount; r++) {
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1204]: what about using a ```foreach```:

```
int nextIdx = 0;
for( final EVIDENCE evi : sampleEvidence) {
    index.put(evi, nextIdx++);
}
```

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java [hunk 13]
```diff
@@ -1216,18 +1189,26 @@ public void filterPoorlyModeledEvidence(final ToDoubleFunction<EVIDENCE> log10Mi
...
+            index.put(sampleEvidence.get(r), r);
+        }
+    }
+
+    @VisibleForTesting
+    boolean evidenceToIndexCacheIsFilled(final int sampleIndex) {
```
Comment (vruano) [inline src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1210]: I like more ```...IsPresent``` rather than ```...isFilled```, but my mother's tongle is not English.

File: src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoodsUnitTest.java [hunk 14]
```diff
@@ -174,11 +174,19 @@ public void testFilterPoorlyModeledReads(final String[] samples, final Allele[]
         final AlleleLikelihoods<GATKRead, Allele> original = makeGoodAndBadLikelihoods(samples, alleles, reads);
 
         final AlleleLikelihoods<GATKRead, Allele> result = makeGoodAndBadLikelihoods(samples, alleles, reads);
+
+        // fill the evidence-to-index cache now to check that it is invalidated below
```
Comment (vruano) [inline src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoodsUnitTest.java:178]: IMO this cache is a implementation business and the using code is not supposed to know or care about it. I don't think there is the need to check the inner state of the likelihood collection this way which results in exposing its workings for the sake of this testing.

Instead you could focus that the index are consistent after several mutating operations.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java (hunk 3 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:771]: done

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java (hunk 4 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:782]: I agree, but now that you mention it I think it's even better to drop `nextIndex` entirely and replace it with `sampleEvidence.size()`.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java (hunk 5 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:783]: True, but upon further thought I realized this method should be `void` because its return value is not really needed.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java (hunk 6 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1124]: Works for me.  Done.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java (hunk 8 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1136]: I wasn't worried, just preserving a check from before the PR.  Deleting validating code from private methods always makes me happy.  Done.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java (hunk 12 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1204]: I like the `foreach` but my distaste for introducing a variable outside the scope of the `for` loop is stronger.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java (hunk 11 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1203]: Can't argue with principle.  Done.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java (hunk 7 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1129]: That's pretty neat but I think I'll keep the loop simpler as-is.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java (hunk 9 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1148]: Your way is better.  Done.

File: src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java (hunk 10 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoods.java:1192]: done

File: src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoodsUnitTest.java (hunk 14 above)
Comment (davidbenjamin) [reply src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleLikelihoodsUnitTest.java:178]: done

**Comment by davidbenjamin** [comment]
Done with Valentin's comments.
