### PR TITLE
Changed FilterIntervals to operate on the intersection of intervals in all inputs.

### LINKED ISSUE #5388: GermlineCNVCaller `-XL` gives error "Intervals for read-count file do not contain all specified intervals"
### Affected tool(s) or class(es)
GermlineCNVCaller 

### Affected version(s)
v4.0.4.0 and v4.0.11.0 tested with same result

### Description 
screenshot 2018-11-02 14 50 17

```
java.lang.IllegalArgumentException: Intervals for read-count file /home/shlee/gcnv/cvg/HG00096_chr20XY.hdf5 do not contain all specified intervals.
        at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:724)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.writeIntervalSubsetReadCountFiles(GermlineCNVCaller.java:390)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.doWork(GermlineCNVCaller.java:285)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

Command runs fine sans `-XL` parameter. The contents of `-XL` are simply:

screenshot 2018-11-02 14 51 58

#### Expected behavior
It would be great to be able to iterate GermlineCNVCaller on coverage data while excluding various regions, e.g. centromeric regions, to test the impact of such regions on the denoising. Currently, the hypothetical workaround would be to collect coverage while excluding regions or to manually remove such intervals from the coverage data. Having to collect coverage once over all of the data is preferable to collecting coverage again and again over slightly variable regions.

### PR DESCRIPTION
**Pull request by samuelklee**
Closes #5388.

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervals.java [hunk 1]
```diff
@@ -281,51 +283,71 @@ private void validateFilesAndResolveIntervals() {
...
+            resolved = intervalArgumentCollection.getIntervals(metadata.getSequenceDictionary());
+            intersected = ListUtils.intersection(
+                    resolved,
+                    annotatedIntervals.getIntervals());
+        } else if (inputAnnotatedIntervalsFile == null && !inputReadCountFiles.isEmpty()) {
+            //only counts provided
+            final File firstReadCountFile = inputReadCountFiles.get(0);
+            final SimpleCountCollection firstReadCounts = SimpleCountCollection.read(firstReadCountFile);
+            metadata = firstReadCounts.getMetadata();
+            resolved = intervalArgumentCollection.getIntervals(metadata.getSequenceDictionary());
```
Comment (asmirnov239) [inline src/main/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervals.java]: Maybe check that the sequence dictionary is the same in counts file and intervals file?

File: src/test/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervalsIntegrationTest.java [hunk 2]
```diff
@@ -262,20 +267,25 @@ public void testCountBasedFilters(final File intervalsFile,
...
+                //intervals file, array of strings for excluded intervals, annotated-intervals file, min/max GC content, mix/max mappability, min/max seg-dupe content,
                 //count files, lowCountFilterCountThreshold, lowCountFilterPercentageOfSamples,
                 //extremeCountFilterMinimumPercentile, extremeCountFilterMaximumPercentile, extremeCountFilterPercentageOfSamples,
                 //expected array of indices of retained intervals
-                {intervalsFile, annotatedIntervalsFile, 0.1, 0.9, 0.1, 0.9, 0.1, 0.9,
+                {intervalsFile, Collections.emptyList(), annotatedIntervalsFile, 0.1, 0.9, 0.1, 0.9, 0.1, 0.9,
                         countFiles, lowCountFilterCountThreshold, percentageOfSamples, 1., 99., percentageOfSamples,
                         IntStream.range(numIntervalsBelowCountThreshold + 1, numIntervalsBelowCountThreshold + 99).boxed().collect(Collectors.toList())},
-                {intervalsFile, annotatedIntervalsFile, 0.1, 0.9, 0.1, 0.9, 0.1, 0.9,
+                {intervalsFile, Collections.emptyList(), annotatedIntervalsFile, 0.1, 0.9, 0.1, 0.9, 0.1, 0.9,
```
Comment (asmirnov239) [inline src/test/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervalsIntegrationTest.java]: It would be nice to have a test case where the annotatedIntervalsFile and countFiles is missing a few entries, up to you!

File: src/main/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervals.java (hunk 1 above)
Comment (samuelklee) [reply src/main/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervals.java]: The intervals file may not have a sequence dictionary (e.g., we can just pass intervals as strings from the command line).  This code takes the sequence dictionary from the first read count file, which is used to check other inputs.  Probably we should check for the presence of a master dictionary, which may come from the intervals---let me try that.

Comment (samuelklee) [reply src/main/java/org/broadinstitute/hellbender/tools/copynumber/FilterIntervals.java]: Hmm, actually it looks like checking interval files for a sequence dictionary would require a bit of extra code.  (Even `getBestAvailableSequenceDictionary` in `GATKTool` has a `TODO` for this.)  Will punt for the time being.
