### PR TITLE
Check for bad sequence dictionaries in ReferenceUtils.loadFastaDictionary

### LINKED ISSUE #2609: ReferenceUtils.loadFastaDictionary should throw a UserException if given an invalid .dict file.

### PR DESCRIPTION
**Pull request by jonn-smith**
Now throws a UserException.MalformedFile if the resulting header has no
dictionary.

Added testLoadFastaDictionaryWithFastaFile to test this case.

resolves #2609

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java [hunk 1]
```diff
@@ -65,6 +71,15 @@ public static SAMSequenceDictionary loadFastaDictionary( final InputStream fasta
 
         final SAMTextHeaderCodec codec = new SAMTextHeaderCodec();
         final SAMFileHeader header = codec.decode(reader, fastaDictionaryStream.toString());
+
+        // Make sure we have a valid sequence dictionary before continuing:
+        if (header.getSequenceDictionary().isEmpty()) {
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java]: Protect against null as well: `if (header.getSequenceDictionary() == null || header.getSequenceDictionary().isEmpty())`

File: src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java [hunk 2]
```diff
@@ -49,6 +49,12 @@ public static SAMSequenceDictionary loadFastaDictionary( final File fastaDiction
         catch ( IOException e ) {
             throw new UserException.CouldNotReadInputFile("Error loading fasta dictionary file " + fastaDictionaryFile, e);
         }
+        catch ( UserException.MalformedFile e ) {
+            throw new UserException.MalformedFile(
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java]: A little weird, but I guess worth doing to increase the specificity of the error message.

File: src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java [hunk 3]
```diff
@@ -65,6 +71,15 @@ public static SAMSequenceDictionary loadFastaDictionary( final InputStream fasta
 
         final SAMTextHeaderCodec codec = new SAMTextHeaderCodec();
         final SAMFileHeader header = codec.decode(reader, fastaDictionaryStream.toString());
+
+        // Make sure we have a valid sequence dictionary before continuing:
+        if (header.getSequenceDictionary().isEmpty()) {
+            throw new UserException.MalformedFile (
+                    "Could not read sequence dictionary from given fasta stream " +
+                            fastaDictionaryStream.toString()
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java]: Explicit `toString()` call unnecessary (Java invokes it for you)

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java [hunk 4]
```diff
@@ -52,6 +53,25 @@ public void testLoadFastaDictionaryFromStream() throws IOException {
         }
     }
 
+    @Test
+    public void testLoadFastaDictionaryWithFastaFile() throws IOException {
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: The name of this test case will be confusing to anyone not familiar with the original issue -- recommend renaming to something like `testLoadWrongFormatFastaDictionary()`

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java [hunk 5]
```diff
@@ -52,6 +53,25 @@ public void testLoadFastaDictionaryFromStream() throws IOException {
...
+        Assert.assertThrows(UserException.MalformedFile.class, () -> {
+            ReferenceUtils.loadFastaDictionary(testFastaFile);
+        });
+
+        // Test loadFastaDictionary with Stream argument:
+        try ( final ClosingAwareFileInputStream referenceDictionaryStream = new ClosingAwareFileInputStream(testFastaFile) ) {
+
+            Assert.assertThrows(UserException.MalformedFile.class, () -> {
+                ReferenceUtils.loadFastaDictionary(referenceDictionaryStream);
+            });
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: You should be using TestNG's `expectedExceptions` feature here. Exceptions you expect to be thrown should go in the `@Test` annotation itself: `(expectedExceptions = UserException.MalformedFile.class)`. That way you don't have to call `assertThrows()` yourself. 

You'll need to break this up into two test cases to do this -- you can use a `DataProvider` with two test cases that passes in a `File` plus a boolean flag indicating whether to call the stream version.

File: src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java (hunk 1 above)
Comment (jonn-smith) [inline src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java]: Done!

File: src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java (hunk 3 above)
Comment (jonn-smith) [inline src/main/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtils.java]: Removed!

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java (hunk 4 above)
Comment (jonn-smith) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: Renamed as suggested.

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java (hunk 5 above)
Comment (jonn-smith) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: Updated to use expectedExceptions and a DataProvider.

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java [hunk 6]
```diff
@@ -52,6 +57,34 @@ public void testLoadFastaDictionaryFromStream() throws IOException {
         }
     }
 
+    @DataProvider(name = "testData_testLoadWrongFormatFastaDictionary")
+    public Object[][] testData_testLoadWrongFormatFastaDictionary(final Method testMethod) {
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: Your `DataProvider` method should take no parameters.

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java [hunk 7]
```diff
@@ -52,6 +57,34 @@ public void testLoadFastaDictionaryFromStream() throws IOException {
...
+        Object[][] tests = {
+                {hg19MiniReference, true},
+                {hg19MiniReference, false}
+        };
+
+        return tests;
+    }
+
+    @Test(expectedExceptions = UserException.MalformedFile.class, dataProvider = "testData_testLoadWrongFormatFastaDictionary")
+    public void testLoadWrongFormatFastaDictionary(final String fastaFileName, boolean doLoadAsStream ) throws IOException {
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: `loadAsStream` is a bit less awkward than `doLoadAsStream`

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java (hunk 6 above)
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: Also, if you don't provide an explicit name for your `DataProvider`, it will default to using the method name as the `DataProvider` name.

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java [hunk 8]
```diff
@@ -52,6 +57,34 @@ public void testLoadFastaDictionaryFromStream() throws IOException {
         }
     }
 
+    @DataProvider(name = "testData_testLoadWrongFormatFastaDictionary")
+    public Object[][] testData_testLoadWrongFormatFastaDictionary(final Method testMethod) {
+
+        Object[][] tests = {
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: Add a comment explaining that we're trying to load a fasta file as a `dict` file to trigger a malformed file error.

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java [hunk 9]
```diff
@@ -52,6 +57,34 @@ public void testLoadFastaDictionaryFromStream() throws IOException {
...
+    public void testLoadWrongFormatFastaDictionary(final String fastaFileName, boolean doLoadAsStream ) throws IOException {
+
+        File testFastaFile = new File(fastaFileName);
+
+        if ( doLoadAsStream ) {
+            // Test loadFastaDictionary with Stream argument:
+            try ( final ClosingAwareFileInputStream referenceDictionaryStream = new ClosingAwareFileInputStream(testFastaFile) ) {
+                ReferenceUtils.loadFastaDictionary(referenceDictionaryStream);
+            }
+        }
```
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: We typically do braces like 
```
} else {
```
 rather than
``` 
}
 else  {
```

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java (hunk 8 above)
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: I would probably just inline this variable

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java (hunk 9 above)
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: David claims he writes with this style. So I guess do whatever you want.

Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: Not me :)

File: src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java (hunk 8 above)
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/reference/ReferenceUtilsUnitTest.java]: ie., `return new Object[][] {`
