### PR TITLE
fixing test failures when AVX is supported but the library doesn't exist

### LINKED ISSUE #1575: VectorPairHMMUnitTest fails if the machine supports AVX but the library isn't built
`VectorPairHMMUnitTest` checks `isAVXSupported()` and skips tests if it's not.  However, if AVX is supported on the machine, but the library isn't available it fails with 

```
Caused by: java.lang.IllegalArgumentException: Resource not found relative to class org.broadinstitute.hellbender.utils.pairhmm.VectorLoglessPairHMM: /lib/libVectorLoglessPairHMM.so
	at org.broadinstitute.hellbender.utils.io.Resource.getResourceContentsAsStream(Resource.java:60)
	at org.broadinstitute.hellbender.utils.io.IOUtils.writeResource(IOUtils.java:234)
	at org.broadinstitute.hellbender.utils.io.IOUtils.writeTempResource(IOUtils.java:222)
	at org.broadinstitute.hellbender.utils.pairhmm.VectorLoglessPairHMM.<init>(VectorLoglessPairHMM.java:106)
	at org.broadinstitute.hellbender.utils.pairhmm.VectorPairHMMUnitTest.<init>(VectorPairHMMUnitTest.java:22)
	... 46 more
```

This should be fixed so that the tests are skipped instead.

### PR DESCRIPTION
**Pull request by lbergelson**
Fixing an issue where AVX tests would fail if AVX was supported by the computer but the library hadn't been built for some reason.  

Fixes #1575

### CODE REVIEW

**Comment by lbergelson** [comment]
@droazen Could you take a look at this?

File: src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java [hunk 1]
```diff
@@ -101,12 +101,16 @@ public VectorLoglessPairHMM() throws UserException.HardwareFeatureException {
...
                     //Could not load from Java's library path - try unpacking from jar
-                    logger.debug("libVectorLoglessPairHMM not found in JVM library path - trying to unpack from GATK jar file");
-                    String path = "/lib/libVectorLoglessPairHMM" + (runningOnMac ? ".dylib" : ".so");
-                    File temp = IOUtils.writeTempResource(new Resource(path, VectorLoglessPairHMM.class));
-                    temp.deleteOnExit();
-                    System.load(temp.getAbsolutePath());
-                    logger.info("libVectorLoglessPairHMM unpacked successfully from GATK jar file");
+                    try {
+                        logger.debug("libVectorLoglessPairHMM not found in JVM library path - trying to unpack from GATK jar file");
+                        String path = "/lib/libVectorLoglessPairHMM" + (runningOnMac ? ".dylib" : ".so");
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java]: Declare path to library as a static constant at the top of the class

File: src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java [hunk 2]
```diff
@@ -101,12 +101,16 @@ public VectorLoglessPairHMM() throws UserException.HardwareFeatureException {
...
+                        File temp = IOUtils.writeTempResource(new Resource(path, VectorLoglessPairHMM.class));
+                        temp.deleteOnExit();
+                        System.load(temp.getAbsolutePath());
+                        logger.info("libVectorLoglessPairHMM unpacked successfully from GATK jar file");
+                    } catch (final Exception furtherException){
+                        throw new UserException.HardwareFeatureException("Could not load AVX PairHMM library from GATK jar", furtherException);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java]: Adjust this error message slightly to make it clearer what the situation is -- eg., "Machine supports AVX, but failed to load AVX PairHMM library from classpath"

File: src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java [hunk 3]
```diff
@@ -101,12 +101,16 @@ public VectorLoglessPairHMM() throws UserException.HardwareFeatureException {
                     logger.info("libVectorLoglessPairHMM found in JVM library path");
                 } catch (UnsatisfiedLinkError e) {
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java]: Wish there were a way to unit test the two failure modes here (AVX not supported and library not loadable) via mocks or something similar

**Comment by droazen** [comment]
Review complete -- back to @lbergelson

File: src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java (hunk 3 above)
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java]: Tricky to mock a static method.  See our conversation about how I wish java had a concept for "abstract static method".

Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/pairhmm/VectorLoglessPairHMM.java]: We could do it enterprise style and provide an `AVXAvailableProviderFactory` and then mock that...
