### PR TITLE
Fixed a bug where invalid feature file intervals weren't being checked for validity against the sequence dictionary

### LINKED ISSUE #7289: 4.2.0.0 : HC  java.lang.IllegalStateException: Padded span must contain active span
### Affected tool(s) or class(es)

HC  java.lang.IllegalStateException: Padded span must contain active span

### Affected version(s)
- [X] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description

```
Runtime.totalMemory()=2494038016
java.lang.IllegalStateException: Padded span must contain active span.
        at org.broadinstitute.hellbender.utils.Utils.validate(Utils.java:814)
        at org.broadinstitute.hellbender.engine.AssemblyRegion.<init>(AssemblyRegion.java:104)
        at org.broadinstitute.hellbender.engine.AssemblyRegion.<init>(AssemblyRegion.java:80)
        at org.broadinstitute.hellbender.utils.activityprofile.ActivityProfile.popNextReadyAssemblyRegion(ActivityProfile.java:332)
        at org.broadinstitute.hellbender.utils.activityprofile.ActivityProfile.popReadyAssemblyRegions(ActivityProfile.java:277)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.loadNextAssemblyRegion(AssemblyRegionIterator.java:159)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:112)
        at org.broadinstitute.hellbender.engine.AssemblyRegionIterator.next(AssemblyRegionIterator.java:35)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:192)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

#### Steps to reproduce

see attachement.

```
gatk  HaplotypeCaller  -I jeter.bam -L jeter.bed --seconds-between-progress-updates 600 --minimum-mapping-quality 30  -R  hs37d5_all_chr.fasta -O jeter.vcf.gz
```

#### Expected behavior

no exception

#### Actual behavior

```
  java.lang.IllegalStateException: Padded span must contain active span
```

### PR DESCRIPTION
**Pull request by jamesemery**
Fixes #7289

### CODE REVIEW

File: src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java [hunk 1]
```diff
@@ -608,6 +608,13 @@ public void testUseAllHG38ContigsInIntervalQuery() {
         );
     }
 
+    @Test(expectedExceptions = org.broadinstitute.hellbender.exceptions.UserException.class)
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java:611]: Import this class instead of writing out the full package name

File: src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java [hunk 2]
```diff
@@ -608,6 +608,13 @@ public void testUseAllHG38ContigsInIntervalQuery() {
...
+    public void testReasonableErrorWithInvalidBedFile() throws IOException {
+        File outOfBoundsBedFile = new File(INTERVAL_TEST_DATA + "bad_interval_span.bed"); // this bed file has a bogus interval the extends past the end of the
+        // this should throw a user exception because of the invalid interval
+        IntervalUtils.featureFileToIntervals(hg19GenomeLocParser, outOfBoundsBedFile.getAbsolutePath());
+    }
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java:616]: Add similar tests with an out-of-bounds interval in Picard and GATK format interval files

File: src/test/resources/org/broadinstitute/hellbender/utils/interval/bad_interval_span.bed [hunk 3]
```diff
@@ -0,0 +1 @@
+1	249240000	249260000
```
Comment (droazen) [inline src/test/resources/org/broadinstitute/hellbender/utils/interval/bad_interval_span.bed:1]: The name of this bed file should indicate which reference it uses (eg., `bad_hg19_interval.bed`)

File: src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java (hunk 2 above)
Comment (jamesemery) [reply src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java:616]: added

File: src/main/java/org/broadinstitute/hellbender/utils/GenomeLocParser.java [hunk 4]
```diff
@@ -405,7 +405,7 @@ public GenomeLoc createGenomeLoc(final Feature feature) {
      */
     public GenomeLoc createGenomeLoc(final Locatable locatable) {
         Utils.nonNull(locatable, "the input locatable cannot be null");
-        return createGenomeLoc(locatable.getContig(), locatable.getStart(), locatable.getEnd());
+        return createGenomeLoc(locatable.getContig(), locatable.getStart(), locatable.getEnd(), true);
```
[the remark this answers is not in the document]
Comment (jamesemery) [reply src/main/java/org/broadinstitute/hellbender/utils/GenomeLocParser.java:408]: I'm worried about breaking something or adding expensive validation operations onto some other tools accidentally. I'll create a ticket to do this audit at this point and we can tackle this later. My priority now is to get this guardrail in for the parser argument that gets triggered by users.

[the remark this answers is not in the document]
Comment (jamesemery) [reply src/main/java/org/broadinstitute/hellbender/utils/GenomeLocParser.java:408]: #7300

**Comment by jamesemery** [comment]
@droazen responded to comments and back to you.

**Comment by jamesemery** [comment]
@droazen sigh... I would rather not get into why exactly the CNV tests are relying on bogus intervals that don't pass validation and what to do about it on this branch. I would rather get this version of things in now to help in at least the -L interval file use case

File: src/main/java/org/broadinstitute/hellbender/utils/GenomeLocParser.java [hunk 5]
```diff
@@ -393,7 +393,17 @@ public GenomeLoc createGenomeLoc( final GATKRead read ) {
...
+    }
+
+    /**
+     * Creates a GenomeLoc from a Tribble feature
+     * @param feature
+     * @param skipValidation  true to disable check for features to be on the reference
+     * @return
+     */
+    public GenomeLoc createGenomeLoc(final Feature feature, final boolean skipValidation) {
+        return createGenomeLoc(feature.getContig(), feature.getStart(), feature.getEnd(), !skipValidation);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/GenomeLocParser.java:406]: It is very confusing to introduce a new boolean parameter `skipValidation` that is the inverse of the existing `mustBeOnReference` boolean that is everywhere else in this class. Can you rename this one to `mustBeOnReference` as well for consistency, and remove the negation / flip the values passed in?

File: src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java [hunk 6]
```diff
@@ -608,6 +608,21 @@ public void testUseAllHG38ContigsInIntervalQuery() {
...
+
+    @Test(expectedExceptions = UserException.class)
+    public void testReasonableErrorWithInvalidListFile() throws IOException {
+        File outOfBoundsBedFile = new File(INTERVAL_TEST_DATA + "bad_hg19_example_intervals.list"); // this list file has a bogus interval the extends past the end chr1 and should throw an exception
+        // this should throw a user exception because of the invalid interval
+        IntervalUtils.featureFileToIntervals(hg19GenomeLocParser, outOfBoundsBedFile.getAbsolutePath());
+    }
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/IntervalUtilsUnitTest.java:623]: Can we get a test with a Picard `.interval_list` file as well?

**Review by droazen — CHANGES_REQUESTED** [review]
@jamesemery Back to you with a few additional comments

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/evaluators/VariantSummary.java [hunk 7]
```diff
@@ -167,9 +167,9 @@ private boolean overlapsKnownCNV(VariantContext cnv, VariantEvalContext context)
         if ( knownCNVs != null ) {
             List<Feature> overlaps = context.queryFeaturesIncludingOverlapping(knownCNVs, new SimpleInterval(cnv.getContig(), cnv.getStart(), cnv.getEnd()));
             GenomeLocParser parser = new GenomeLocParser(context.getSequenceDictionaryForDrivingVariants());
-            GenomeLoc loc1 = parser.createGenomeLoc(cnv);
+            GenomeLoc loc1 = parser.createGenomeLoc(cnv, true);
             for (Feature vc : overlaps) {
-                GenomeLoc loc2 = parser.createGenomeLoc(vc);
+                GenomeLoc loc2 = parser.createGenomeLoc(vc, true);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/evaluators/VariantSummary.java:172]: Add a comment above these lines pointing out that we're explicitly allowing intervals that go off the end of the reference

**Comment by jamesemery** [comment]
@droazen responded

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/evaluators/VariantSummary.java [hunk 8]
```diff
@@ -167,6 +167,7 @@ private boolean overlapsKnownCNV(VariantContext cnv, VariantEvalContext context)
         if ( knownCNVs != null ) {
             List<Feature> overlaps = context.queryFeaturesIncludingOverlapping(knownCNVs, new SimpleInterval(cnv.getContig(), cnv.getStart(), cnv.getEnd()));
             GenomeLocParser parser = new GenomeLocParser(context.getSequenceDictionaryForDrivingVariants());
+            // NOTE: by using this overload we are explicitly allowing variants that don't with the reference intervals
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/varianteval/evaluators/VariantSummary.java:170]: Missing a verb here -- "overlap", perhaps?

**Comment by jamesemery** [comment]
@droazen this has passed tests

**Review by droazen — APPROVED** [review]
+1
