### PR TITLE
Explicitly sort the list of bam fragments before merging in ReadsSparkSink

### LINKED ISSUE #1258: MarkDuplicatesSparkIntegrationTest.testMDOrder() passes locally, but fails intermittently in travis
`MarkDuplicatesSparkIntegrationTest.testMDOrder()` *always* passes when run locally, but fails about 50% of the time when run in travis. As a result, it's currently disabled.

Some things I've tried to fix the test on travis, without success:
-Run MD with `--parallelism 1` instead of `--parallelism 0` (which doesn't guarantee ordering at all!) -- the original version of the test was running with `--parallelism 0`
-Converted test inputs from sam to bam
-Cleared all of travis's caches.

This may be purely a travis issue or a flaw in the test itself, or it may indicate that there remain issues with `MarkDuplicatesSpark` output and ordering despite the recent fixes. Note, however, that the original test from @davidadamsphd that first detected the ordering issue with MD on spark now passes, as do the new `ReadsSparkSink` ordering tests.

### PR DESCRIPTION
**Pull request by droazen**
We were victims of a known bug in Hadoop (https://issues.apache.org/jira/browse/HADOOP-10798)
that caused us to sometimes assemble our bam fragments in ReadsSparkSink out-of-order.
Adding an explicit sort fixes this.

Resolves #1258

### CODE REVIEW

**Comment by droazen** [comment]
Don't merge yet until we run this through travis a bunch of times to prove that the bug is fixed.

**Comment by droazen** [comment]
@lbergelson and/or @akiezun can you review this while we're waiting for the travis results?

File: src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java [hunk 1]
```diff
@@ -258,4 +260,16 @@ private static void mergeInto(OutputStream out, Path directory, Configuration co
             fs.delete(part.getPath(), false);
         }
     }
+
+    protected static FileStatus[] getBamFragments( final Path directory, final FileSystem fs ) throws IOException {
+        final FileStatus[] parts = fs.globStatus(new Path(directory, "part-r-[0-9][0-9][0-9][0-9][0-9]*"));
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java]: this should be based on the value of `mapreduce.output.basename` in case someone sets it on us

File: src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java [hunk 2]
```diff
@@ -258,4 +260,16 @@ private static void mergeInto(OutputStream out, Path directory, Configuration co
...
+
+        // FileSystem.globStatus() has a known bug that causes it to not sort the array returned by
+        // name (despite claiming to): https://issues.apache.org/jira/browse/HADOOP-10798
+        // Because of this bug, we do an explicit sort here to avoid assembling the bam fragments
+        // in the wrong order.
+        Arrays.sort(parts);
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java]: useful comment, thanks

Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java]: should we have a ticket to update hadoop to 2.8 and remove this workaround at that point?

File: src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java (hunk 1 above)
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java]: Good idea -- created a separate ticket https://github.com/broadinstitute/gatk/issues/1281 to address this.

File: src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java (hunk 2 above)
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReadsSparkSink.java]: This workaround shall live forever as a defensive measure! :)

But, yes, we should update to Hadoop 2.8 when it's out.

**Comment by droazen** [comment]
This has now passed 5 consecutive builds in travis (counting both the pr and push builds) -- merging!
