### PR TITLE
BQSR pipeline without saving + fixed tests for BQSR on spark

### LINKED ISSUE #799: Remove save&reload requirement for BQSR
This was mentioned already as a comment in #562 but it should be an issue instead.

BQSR on Dataflow can *theoretically* avoid the step of saving the textual report, instead piping the recalibration analysis results directly to the ApplyBQSR phase. In practice it cannot, because it turns out that **saving a report and immediately loading it back is not a no-op**. it actually changes in some necessary way.

It would be great if someone familiar with that part of the code could help factor the mutation apart from the saving/loading, so I could just call that in the pipeline. This would speed things up a bit and the code would be that much cleaner.

### LINKED ISSUE #1017: BQSR Spark integration tests use incorrect list of variants
BQSR tests in spark use a bam file and dbSNP file that are non-corresponding (coming from different chromosomes). 

"CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
"dbsnp_132.b37.excluding_sites_after_129.chr17_69k_70k.vcf";

the same tests in non-spark use properly matched bam and vcf file

### PR DESCRIPTION
**Pull request by akiezun**
fixes #799 
fixes #1017 
Adds BQSRSpark program that runs 2 steps of BQSR without writing the tables to a file.

### CODE REVIEW

**Comment by akiezun** [comment]
for @droazen

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+@CommandLineProgramProperties(
+        summary = "This tools performs 2 steps of BQSR - crection of recalibration tables and rewriting of the bam, without writing the tables to disk. ",
+        oneLineSummary = "Both steps of BQSR",
+        usageExample = "BQSRSpark -I in.bam --BQSRKnownVariants in.vcf -O out.bam",
+        programGroup = SparkProgramGroup.class
+)
+/**
+ * BQSR. The final result is analysis-ready reads.
+ */
+public final class BQSRSpark extends GATKSparkTool {
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: It is very confusing to have both `BQSRSpark` and `BaseRecalibratorSpark`. Can you name this something like `BQSRSparkPipeline` (since it runs two tools)?

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+import org.broadinstitute.hellbender.utils.read.ReadsWriteFormat;
+import org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine;
+import org.broadinstitute.hellbender.utils.recalibration.RecalibrationArgumentCollection;
+import org.broadinstitute.hellbender.utils.recalibration.RecalibrationReport;
+import org.broadinstitute.hellbender.utils.variant.Variant;
+
+import java.io.IOException;
+import java.util.List;
+@CommandLineProgramProperties(
+        summary = "This tools performs 2 steps of BQSR - crection of recalibration tables and rewriting of the bam, without writing the tables to disk. ",
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: crection -> creation

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+public final class BQSRSpark extends GATKSparkTool {
+    private static final long serialVersionUID = 1L;
+
+    @Override
+    public boolean requiresReads() { return true; }
+
+    @Override
+    public boolean requiresReference() { return true; }
+
+    @Argument(doc = "the known variants", shortName = "BQSRKnownVariants", fullName = "baseRecalibrationKnownVariants", optional = true)
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: Name this argument `knownSites` (both full and short name) for consistency with the other versions of BQSR.

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+    protected List<String> baseRecalibrationKnownVariants;
+
+    @Argument(doc = "the output bam", shortName = StandardArgumentDefinitions.OUTPUT_SHORT_NAME,
+            fullName = StandardArgumentDefinitions.OUTPUT_LONG_NAME, optional = false)
+    protected String output;
+
+    @Argument(doc = "If specified, shard the output bam", shortName = "shardedOutput", fullName = "shardedOutput", optional = true)
+    private boolean shardedOutput = false;
+
+    @Argument(doc = "the join strategy for reference bases", shortName = "joinStrategy", fullName = "joinStrategy", optional = true)
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: The join strategy for references bases and variants

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+    private JoinStrategy joinStrategy = JoinStrategy.SHUFFLE;
+    
+    @Override
+    public SerializableFunction<GATKRead, SimpleInterval> getReferenceWindowFunction() {
+        return BaseRecalibrationEngine.BQSR_REFERENCE_WINDOW_FUNCTION;
+    }
+
+    @Override
+    protected void runTool(final JavaSparkContext ctx) {
+        JavaRDD<GATKRead> markedReads = getReads();
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: Don't assume that the reads have been processed in any particular way (by naming this `markedReads`). Just name it `initialReads`

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+        VariantsSparkSource variantsSparkSource = new VariantsSparkSource(ctx);
+
+        if ( baseRecalibrationKnownVariants.isEmpty() ) { // Warn the user if no dbSNP file or other variant mask was specified
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: I think this check is missing from `BaseRecalibratorSpark` -- can you add it there as well?

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+
+        // TODO: workaround for known bug in List version of getParallelVariants
+        if ( baseRecalibrationKnownVariants.size() > 1 ) {
+            throw new GATKException("Cannot currently handle more than one known sites file, " +
+                                    "as getParallelVariants(List) is broken");
+        }
+        JavaRDD<Variant> bqsrKnownVariants = variantsSparkSource.getParallelVariants(baseRecalibrationKnownVariants.get(0));
+
+        // TODO: Look into broadcasting the reference to all of the workers. This would make AddContextDataToReadSpark
+        // TODO: and ApplyBQSRStub simpler (#855).
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: Delete this comment -- the reference will be broadcast if the BROADCAST join strategy is selected (and it's a `.2bit` reference)

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+        JavaPairRDD<GATKRead, ReadContextData> rddReadContext = AddContextDataToReadSpark.add(markedReads, getReference(), bqsrKnownVariants, joinStrategy);
+        // TODO: broadcast the reads header?
+
+        //note: we use the reference dictionary from the reads themselves.
+        final RecalibrationReport bqsrReport = BaseRecalibratorSparkFn.apply(rddReadContext, getHeaderForReads(), getHeaderForReads().getSequenceDictionary(), new RecalibrationArgumentCollection());
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: Shouldn't you be exposing the `RecalibrationArgumentCollection` as an `@ArgumentCollection` here (as in `BaseRecalibratorSpark`) so that the BQSR settings can be customized?

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java [hunk 9]
```diff
@@ -0,0 +1,102 @@
...
+        final Broadcast<RecalibrationReport> reportBroadcast = ctx.broadcast(bqsrReport);
+        final JavaRDD<GATKRead> finalReads = ApplyBQSRSparkFn.apply(markedReads, reportBroadcast, getHeaderForReads(), new ApplyBQSRArgumentCollection());
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: Here too -- shouldn't you be exposing the `ApplyBQSRArgumentCollection` as an `@ArgumentCollection` so that `ApplyBQSR` settings can be customized?

File: src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java [hunk 10]
```diff
@@ -54,18 +50,13 @@ public static RecalibrationReport apply( final JavaPairRDD<GATKRead, ReadContext
...
-                RecalUtils.outputRecalibrationReport(reportStream, recalArgs, quantizationInfo, combinedTables, new StandardCovariateList(recalArgs, header), recalArgs.SORT_BY_ALL_COLUMNS);
-            }
-            return new RecalibrationReport(tempReport);
-        } catch (FileNotFoundException e) {
-            throw new GATKException("can't find my own temporary file", e);
-        }
+        final StandardCovariateList covariates = new StandardCovariateList(recalArgs, header);
+        final RecalibrationArgumentCollection RAC = recalArgs;
+        final boolean sortByCols = recalArgs.SORT_BY_ALL_COLUMNS;
+        final RecalibrationTables recalibrationTables = combinedTables;
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java]: variable is redundant -- just use `combinedTables` directly

File: src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java [hunk 11]
```diff
@@ -54,18 +50,13 @@ public static RecalibrationReport apply( final JavaPairRDD<GATKRead, ReadContext
...
-            File tempReport = IOUtils.createTempFile("temp-recalibrationtable-", ".tmp");
-            try ( PrintStream reportStream = new PrintStream(tempReport) ) {
-                RecalUtils.outputRecalibrationReport(reportStream, recalArgs, quantizationInfo, combinedTables, new StandardCovariateList(recalArgs, header), recalArgs.SORT_BY_ALL_COLUMNS);
-            }
-            return new RecalibrationReport(tempReport);
-        } catch (FileNotFoundException e) {
-            throw new GATKException("can't find my own temporary file", e);
-        }
+        final StandardCovariateList covariates = new StandardCovariateList(recalArgs, header);
+        final RecalibrationArgumentCollection RAC = recalArgs;
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java]: Use `recalArgs` directly -- we've tried hard to purge this cryptic `RAC` acronym from everywhere

File: src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java [hunk 12]
```diff
@@ -54,18 +50,13 @@ public static RecalibrationReport apply( final JavaPairRDD<GATKRead, ReadContext
...
+        final boolean sortByCols = recalArgs.SORT_BY_ALL_COLUMNS;
+        final RecalibrationTables recalibrationTables = combinedTables;
+        final GATKReport report = RecalUtils.createRecalibrationGATKReport(RAC.generateReportTable(covariates.covariateNames()), quantizationInfo.generateReportTable(sortByCols), RecalUtils.generateReportTables(recalibrationTables, covariates, sortByCols));
+        return new RecalibrationReport(report);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java]: Should `createRecalibrationGATKReport()` just return a `RecalibrationReport` directly?

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java [hunk 13]
```diff
@@ -164,6 +165,34 @@ public static void finalizeRecalibrationTables( final RecalibrationTables tables
...
+        }
+    }
+
+    /**
+     * Rounds the double to the given number of decimal places.
+     * For example, rounding 3.1415926 to 3 places would give 3.142.
+     * Not put into MathUtils because it uses the horrible path of going through a formatted String (to match String.format)
+     */
+    @VisibleForTesting
+    static double roundToNDecimalPlaces(final double in, final int n) {
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: Move to `MathUtils`

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java [hunk 14]
```diff
@@ -164,6 +165,34 @@ public static void finalizeRecalibrationTables( final RecalibrationTables tables
...
+        if (n < 1) {
+            throw new IllegalArgumentException("cannot round to " + n + " decimal places");
+        }
+
+        //Note: this code is very ugly because it goes through parsing and unparsing.
+        //The reason is that we want to match what writing the recalibration tables down to a file would do.
+        return Double.valueOf(String.format("%." + n + "f", in));
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: Gross! How about something like this instead:

    BigDecimal bd = new BigDecimal(in);
    bd = bd.setScale(n, RoundingMode.HALF_UP);
    return bd.doubleValue();

And then move to `MathUtils` ;)

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationReport.java [hunk 15]
```diff
@@ -325,12 +325,24 @@ else if (argument.equals("binary_tag_name"))
...
             else if (argument.equals("sort_by_all_columns"))
-                RAC.SORT_BY_ALL_COLUMNS = Boolean.parseBoolean((String) value);
+                RAC.SORT_BY_ALL_COLUMNS = decodeBoolean(value);
         }
 
         return RAC;
     }
 
+    private byte decodeByte(final Object value) {
+        return value instanceof Byte ? (Byte)value: Byte.parseByte((String)value);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationReport.java]: Can you assume that `value` is a `String` if it's not a `Byte`? Could you ever get a `ClassCastException` here? (applies to the new methods below as well).

File: src/main/java/org/broadinstitute/hellbender/utils/test/IntegrationTestSpec.java [hunk 16]
```diff
@@ -180,11 +181,16 @@ public static void assertEqualTextFiles(final File resultFile, final File expect
         final List<String> actualLines = new XReadLines(resultFile).readLines().stream().filter(startsWithComment.negate()).collect(Collectors.toList());
         final List<String> expectedLines = new XReadLines(expectedFile).readLines().stream().filter(startsWithComment.negate()).collect(Collectors.toList());
 
-        Assert.assertEquals(actualLines.toString(), expectedLines.toString());
+        //For ease of debugging, we look at the lines first and only then check their counts
+        final int minLen = Math.min(actualLines.size(), expectedLines.size());
+        for (int i = 0; i < minLen; i++) {
+            Assert.assertEquals(actualLines.get(i).toString(), expectedLines.get(i).toString(), "Line number " + i + " (not counting comments)");
+        }
+        Assert.assertEquals (actualLines.size(), expectedLines.size(), "line counts");
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/test/IntegrationTestSpec.java]: Wouldn't you want to check for a size mismatch first to avoid doing the extra work (and save test suite runtime)?

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java [hunk 17]
```diff
@@ -67,22 +67,22 @@ private String getCloudInputs() {
         final String localResources =  getResourceDir();
         final String hg19Ref = "EMWV_ZfLxrDY-wE";
         final String GRCh37Ref = ReferenceAPISource.URL_PREFIX + ReferenceAPISource.GRCH37_REF_ID;
-        final String HiSeqBam = localResources + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
-        final String dbSNPb37 =  getResourceDir() + "dbsnp_132.b37.excluding_sites_after_129.chr17_69k_70k.vcf";
-        final String moreSites = getResourceDir() + "bqsr.fakeSitesForTesting.b37.chr17.vcf"; //for testing 2 input files
+        final String HiSeqBam_chr20 = localResources + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
+        final String dbSNPb37_chr2021 = largeFileTestDir + "/dbsnp_138.b37.20.21.vcf";
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: `largeFileTestDir` already ends in `/`

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java [hunk 18]
```diff
@@ -67,22 +67,22 @@ private String getCloudInputs() {
...
+        final String moreSites = getResourceDir() + "bqsr.fakeSitesForTesting.b37.chr17.vcf"; //for testing 2 input files (FIXME - this file is bogus because uses chr17)
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: Shouldn't you fix this as part of this PR? Otherwise how can you claim to resolve https://github.com/broadinstitute/gatk/issues/1017 completely?

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java [hunk 19]
```diff
@@ -67,22 +67,22 @@ private String getCloudInputs() {
...
 
         return new Object[][]{
                 // local computation and files (except for the reference)
-                {new BQSRTest(GRCh37Ref, HiSeqBam, dbSNPb37, "", localResources + "expected.CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.recal.txt")},
+                {new BQSRTest(GRCh37Ref, HiSeqBam_chr20, dbSNPb37_chr2021, "", localResources + "expected.CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.recal.txt")},
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: The expected output for these tests didn't change at all with the new known sites file??? That can't be right...

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java [hunk 20]
```diff
@@ -91,26 +91,26 @@ private String getCloudInputs() {
     public Object[][] createBQSRTestDataBucket() {
         final String GRCh37Ref = ReferenceAPISource.URL_PREFIX + ReferenceAPISource.GRCH37_REF_ID;
         final String localResources =  getResourceDir();
-        final String HiSeqBamCloud = getCloudInputs() + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
-        final String dbSNPb37 =  getResourceDir() + "dbsnp_132.b37.excluding_sites_after_129.chr17_69k_70k.vcf";
+        final String HiSeqBamCloud_chr20 = getCloudInputs() + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
+        final String dbSNPb37_chr2010 = largeFileTestDir + "/dbsnp_138.b37.20.21.vcf";
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: Remove extra `/`

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java [hunk 21]
```diff
@@ -91,26 +91,26 @@ private String getCloudInputs() {
...
     @DataProvider(name = "BQSRLocalRefTest")
     public Object[][] createBQSRLocalRefTestData() {
-        final String GRCh37Ref = b37_reference_20_21;
-        final String GRCh37Ref2bit = b37_2bit_reference_20_21;
-        final String hiSeqBam = getResourceDir() + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
-        final String dbSNPb37 =  getResourceDir() + "dbsnp_132.b37.excluding_sites_after_129.chr17_69k_70k.vcf";
+        final String GRCh37Ref_chr2021 = b37_reference_20_21;
+        final String GRCh37Ref2bit_chr2021 = b37_2bit_reference_20_21;
+        final String hiSeqBam_chr20 = getResourceDir() + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
+        final String dbSNPb37_chr2021 = largeFileTestDir + "/dbsnp_138.b37.20.21.vcf";
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: Remove extra `/`

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java [hunk 22]
```diff
@@ -148,21 +148,22 @@ public void testBQSRBucket(BQSRTest params) throws IOException {
     public void testPlottingWorkflow() throws IOException {
         final String resourceDir = getTestDataDir() + "/" + "BQSR" + "/";
         final String GRCh37Ref = ReferenceAPISource.GRCH37_REF_ID; // that's the "full" version
-        final String dbSNPb37 =  getResourceDir() + "dbsnp_132.b37.excluding_sites_after_129.chr17_69k_70k.vcf";
-        final String HiSeqBam = getResourceDir() + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
+        final String dbSNPb37_chr2021 = largeFileTestDir + "/dbsnp_138.b37.20.21.vcf";
+        final String HiSeqBam_chr20 = getResourceDir() + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
 
+        //FIXME - this file is definitely not the right one
         final File actualHiSeqBam_recalibrated = createTempFile("actual.NA12878.chr17_69k_70k.dictFix.recalibrated", ".bam");
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: We can't really close https://github.com/broadinstitute/gatk/issues/1017 if there are still FIXMEs like this one.

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorIntegrationTest.java [hunk 23]
```diff
@@ -55,24 +55,28 @@ private String getResourceDir(){
...
+                {new BQSRTest(hg18Reference, HiSeqBam_chr17, dbSNPb37_chr17, "-knownSites " + moreSites, getResourceDir() + "expected.NA12878.chr17_69k_70k.2inputs.txt")},
+                {new BQSRTest(hg18Reference, HiSeqBam_chr17, dbSNPb37_chr17, "--indels_context_size 4", getResourceDir() + "expected.NA12878.chr17_69k_70k.indels_context_size4.txt")},
+                {new BQSRTest(hg18Reference, HiSeqBam_chr17, dbSNPb37_chr17, "--low_quality_tail 5", getResourceDir() + "expected.NA12878.chr17_69k_70k.low_quality_tail5.txt")},
+                {new BQSRTest(hg18Reference, HiSeqBam_chr17, dbSNPb37_chr17, "--quantizing_levels 6", getResourceDir() + "expected.NA12878.chr17_69k_70k.quantizing_levels6.txt")},
+                {new BQSRTest(hg18Reference, HiSeqBam_chr17, dbSNPb37_chr17, "--mismatches_context_size 4", getResourceDir() + "expected.NA12878.chr17_69k_70k.mismatches_context_size4.txt")},
+                {new BQSRTest(b36Reference, origQualsBam_chr1, dbSNPb36_chr1, "-OQ", getResourceDir() + "expected.originalQuals.1kg.chr1.1-1K.1RG.dictFix.OQ.txt")},
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorIntegrationTest.java]: Again, can you explain why the expected outputs didn't change at all here?

File: src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTests.java [hunk 24]
```diff
@@ -288,8 +288,8 @@ public void testCompareDoubles(){
         Assert.assertEquals(MathUtils.compareDoubles(0.1, 0.2), 1);
         Assert.assertEquals(MathUtils.compareDoubles(0.2, 0.1), -1);
         Assert.assertEquals(MathUtils.compareDoubles(0.1, 0.1), 0);
-        Assert.assertEquals(MathUtils.compareDoubles(0.1, 0.1+(1e-7)), 0);
-        Assert.assertEquals(MathUtils.compareDoubles(0.1, 0.1+(1e-7), 1e-8), 1);
+        Assert.assertEquals(MathUtils.compareDoubles(0.1, 0.1 + (1e-7)), 0);
+        Assert.assertEquals(MathUtils.compareDoubles(0.1, 0.1 + (1e-7), 1e-8), 1);
     }
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTests.java]: This file should end in `*UnitTest`, not `UnitTests`

**Comment by droazen** [comment]
First-pass review complete -- back to @akiezun

File: src/main/java/org/broadinstitute/hellbender/utils/test/IntegrationTestSpec.java (hunk 16 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/utils/test/IntegrationTestSpec.java]: no, because sometimes files are just a bit different and this would fail saying that the number of lines is different, which is true but not helpful. What is helpful is seeing the actual differences

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java (hunk 1 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: done

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java (hunk 2 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: done

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java (hunk 3 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: done, also renamed in ReadsPipelineSpark

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java (hunk 4 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: done

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java (hunk 5 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: done

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java (hunk 6 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: hmm, that's different than GATK3 and different than BaseRecalibrator. How about we make it non optional throughout?

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java (hunk 7 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: done

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java (hunk 8 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: fixed here and in ReadsPipelineSpark

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java (hunk 9 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: fixed here and in ReadsPipelineSpark

File: src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java (hunk 10 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java]: done

File: src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java (hunk 11 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java]: done

File: src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java (hunk 12 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java]: done

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java (hunk 14 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: nope, does not do exactly the same as write and read back. Here's a case:
1.025 rounded to 2 places is 1.02 using your snippet
but when you write with format %.f2 and read back you get 1.03

Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: @tedsharpe's solution works:
```
        final double multiplier = Math.pow(10, n);
        return (Math.round(in * 10. * multiplier)+5)/ 10 / multiplier;
```

Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: done, moved to mathutils

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationReport.java (hunk 15 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationReport.java]: i put an explicit check and blow up with IllegalArgumentException

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java (hunk 17 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: fixed

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java (hunk 20 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: done

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java (hunk 21 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: done

File: src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTests.java (hunk 24 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTests.java]: fixed

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java (hunk 18 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: in this case, it's irrelevant anyway because Spark BQSR can't take multiple --knownSites https://github.com/broadinstitute/gatk/issues/1085

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java (hunk 14 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: i take it back. the new solution does not work:
34.356845398701736 with 4 decimal points returns 34.3569 but expected 34.3568
0.43452380952380953 with 2 points gives 0.44 but expected 0.43

@droazen @tedsharpe any ideas that would work for all 3 cases?

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java (hunk 6 above)
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRSpark.java]: Yes, let's make it a required arg in all versions. It makes zero sense to run BQSR with no known sites.

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java (hunk 14 above)
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: @akiezun Search stackoverflow for canonical solutions and try the most promising ones -- I am surprised that `BigDecimal` with `RoundingMode.HALF_UP` did not round `1.025` to `1.03`! If all else fails, revert back to the `String.format()` approach.

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java (hunk 18 above)
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: Then https://github.com/broadinstitute/gatk/issues/1017 should not be marked as resolved by this PR.

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java (hunk 19 above)
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: Definitely needs to be explained...

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java (hunk 14 above)
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: Was surprised to learn that `BigDecimal` was not working with `RoundingMode.HALF_UP`, so did a little digging and found this: http://stackoverflow.com/questions/7124448/how-does-java-math-roundingmode-work

Basically if you replace `new BigDecimal(in)` with `BigDecimal.valueOf(in)` it works. Ie., 

           BigDecimal bd = BigDecimal.valueOf(1.025);
           bd = bd.setScale(2, RoundingMode.HALF_UP);
           System.out.println(bd.doubleValue());

prints 1.03

Comment (tedsharpe) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: Yeah.  Sorry.  Dumb.  Should have been thinking about machine epsilons.  I'm currently of the opinion that this will work:
final double mult = Math.pow(10,n);
return Math.round( (in+Math.ulp(in))*mult )/mult;

Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: excellent! thanks guys - both of those work great.

I did a microbenchmark, 10M random numbers:
1) the string format dance: 10s 83ms
2) BigDecimal = 5s 465ms
3) math.round: 1s 44ms

Easy winner then.

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorIntegrationTest.java (hunk 23 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/bqsr/BaseRecalibratorIntegrationTest.java]: here i think the inputs and outputs did not change, did they? It's the spark version that is suspicious.

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java [hunk 25]
```diff
@@ -91,26 +91,26 @@ private String getCloudInputs() {
...
+        final String GRCh37Ref2bit_chr2021 = b37_2bit_reference_20_21;
+        final String hiSeqBam_chr20 = getResourceDir() + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
+        final String dbSNPb37_chr2021 = largeFileTestDir + "dbsnp_138.b37.20.21.vcf";
 
         return new Object[][]{
                 // input local, computation local.
-                {new BQSRTest(GRCh37Ref2bit, hiSeqBam, dbSNPb37, "--joinStrategy BROADCAST", getResourceDir() + "expected.CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.recal.txt")},
-                {new BQSRTest(GRCh37Ref, hiSeqBam, dbSNPb37, "--joinStrategy SHUFFLE", getResourceDir() + "expected.CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.recal.txt")},
+                {new BQSRTest(GRCh37Ref2bit_chr2021, hiSeqBam_chr20, dbSNPb37_chr2021, "--joinStrategy BROADCAST", getResourceDir() + "expected.CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.recal.txt")},
+                {new BQSRTest(GRCh37Ref_chr2021, hiSeqBam_chr20, dbSNPb37_chr2021, "--joinStrategy SHUFFLE", getResourceDir() + "expected.CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.recal.txt")},
```
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: this is the suspicious one: used to use chr20 bam and chr17 vcf and now uses chr20/chr20 and results are the same =  weird.

Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: ha, so the reason is that the BAM file and the dbSNP files don't overlap!

**Comment by akiezun** [comment]
back to @droazen - all comments addressed. BaseRecalibratorSparkOptimized seems broken - when I used the correct test files, it became visible that it quite possibly is losing some overlapping variants because the counts are different than GATK3, stand-along BaseRecalibeator in GATK4, and BaseRecalibratorSpark - on exactly the same inputs. I think the reason why it seemed to have worked before was that the bam input and vcf input did not overlap and so missing some overlapping variants was not a problem (because there were 0 to begin with).

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java [hunk 26]
```diff
@@ -0,0 +1,112 @@
...
+import org.broadinstitute.hellbender.utils.recalibration.RecalibrationArgumentCollection;
+import org.broadinstitute.hellbender.utils.recalibration.RecalibrationReport;
+import org.broadinstitute.hellbender.utils.variant.Variant;
+
+import java.io.IOException;
+import java.util.List;
+@CommandLineProgramProperties(
+        summary = "This tools performs 2 steps of BQSR - creation of recalibration tables and rewriting of the bam, without writing the tables to disk. ",
+        oneLineSummary = "Both steps of BQSR",
+        usageExample = "BQSRSpark -I in.bam --knownSites in.vcf -O out.bam",
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java]: Usage example is incorrect: `BQSRSpark` -> `BQSRPipelineSpark`

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java [hunk 27]
```diff
@@ -0,0 +1,112 @@
...
+    }
+
+    @Override
+    protected void runTool(final JavaSparkContext ctx) {
+        final JavaRDD<GATKRead> initialReads = getReads();
+        final VariantsSparkSource variantsSparkSource = new VariantsSparkSource(ctx);
+
+        if ( baseRecalibrationKnownVariants.isEmpty() ) { // Warn the user if no dbSNP file or other variant mask was specified
+            throw new UserException.CommandLineException(BaseRecalibrator.NO_DBSNP_EXCEPTION);
+        }
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java]: You forgot to fix this -- `baseRecalibrationKnownVariants` should be marked as `optional = false`, and let the command-line parser do this check for you.

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java [hunk 28]
```diff
@@ -53,7 +54,7 @@
     @Override
     public boolean requiresReference() { return true; }
 
-    @Argument(doc = "the known variants", shortName = "BQSRKnownVariants", fullName = "baseRecalibrationKnownVariants", optional = true)
+    @Argument(doc = "the known variants", shortName = "knownSites", fullName = "knownSites", optional = true)
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java]: `optional = false`

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java [hunk 29]
```diff
@@ -63,9 +64,22 @@
...
+     * all the command line arguments for BQSR and its covariates
+     */
+    @ArgumentCollection(doc = "all the command line arguments for BQSR and its covariates")
+    private final RecalibrationArgumentCollection bqsrArgs = new RecalibrationArgumentCollection();
+
+    /**
+     * command-line arguments to fine tune the apply BQSR step.
+     */
+    @ArgumentCollection
+    public ApplyBQSRArgumentCollection applyBqsrArgs = new ApplyBQSRArgumentCollection();
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java]: Shouldn't this be a `ApplyBQSRUniqueArgumentCollection`, with a conversion `toApplyBQSRArgumentCollection()` below?

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java [hunk 30]
```diff
@@ -22,10 +20,14 @@
 import org.broadinstitute.hellbender.utils.read.AlignmentUtils;
 import org.broadinstitute.hellbender.utils.read.GATKRead;
 import org.broadinstitute.hellbender.utils.read.ReadUtils;
+import org.broadinstitute.hellbender.utils.recalibration.covariates.Covariate;
+import org.broadinstitute.hellbender.utils.recalibration.covariates.StandardCovariateList;
 
 import java.io.Serializable;
 import java.util.Arrays;
 
+import static org.broadinstitute.hellbender.utils.MathUtils.roundToNDecimalPlaces;
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: Avoid unnecessary static imports

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java [hunk 31]
```diff
@@ -164,6 +166,18 @@ public static void finalizeRecalibrationTables( final RecalibrationTables tables
                 rgDatum.combine(qualDatum);
             }
         }
+
+        roundDecimalPlaces(tables);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: How about naming this `roundTableValues()`?

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationReport.java [hunk 32]
```diff
@@ -325,12 +325,33 @@ else if (argument.equals("binary_tag_name"))
...
         }
 
         return RAC;
     }
 
+    private byte decodeByte(final Object value) {
+        if (!(value instanceof Byte || value instanceof String)){
+            throw new IllegalArgumentException("expected a Byte or a String but got " + value);
+        }
+        return value instanceof Byte ? (Byte)value: Byte.parseByte((String)value);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationReport.java]: Cache the first `instanceof` check in these `decode*` methods, as `instanceof` is actually a bit expensive.

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java [hunk 33]
```diff
@@ -148,21 +152,22 @@ public void testBQSRBucket(BQSRTest params) throws IOException {
     public void testPlottingWorkflow() throws IOException {
         final String resourceDir = getTestDataDir() + "/" + "BQSR" + "/";
         final String GRCh37Ref = ReferenceAPISource.GRCH37_REF_ID; // that's the "full" version
-        final String dbSNPb37 =  getResourceDir() + "dbsnp_132.b37.excluding_sites_after_129.chr17_69k_70k.vcf";
-        final String HiSeqBam = getResourceDir() + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
+        final String dbSNPb37_chr2021 = resourceDir + "dbsnp_138.b37.excluding_sites_after_129.ch20.1m-1m1k.vcf";
+        final String HiSeqBam_chr20 = getResourceDir() + "CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam";
 
+        //FIXME - this file is definitely not the right one
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: Is there a ticket for this `FIXME`? (otherwise it will never get fixed)

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java [hunk 34]
```diff
@@ -148,21 +152,22 @@ public void testBQSRBucket(BQSRTest params) throws IOException {
     public void testPlottingWorkflow() throws IOException {
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: This test is disabled -- why can't we re-enable it now as part of this update to the BQSR tests?

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkOptimizedIntegrationTest.java [hunk 35]
```diff
@@ -91,18 +94,18 @@ private String getCloudInputs() {
...
                 // input in cloud, computation local.
-                {new BQSRTest(GRCh37Ref, HiSeqBamCloud, dbSNPb37, "", localResources + "expected.CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.recal.txt")},
+                {new BQSRTest(GRCh37Ref, HiSeqBamCloud_chr20, dbSNPb37_chr20, "", localResources + "expected.CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.recal.txt")},
         };
     }
 
 
     // "local", but we're still getting the reference from the cloud.
-    @Test(dataProvider = "BQSRTest", groups = {"cloud"})
+    @Test(dataProvider = "BQSRTest", groups = {"cloud"}, enabled = false)
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkOptimizedIntegrationTest.java]: Please add a comment here explaining why this test is disabled, and file a new bug against `BaseRecalibratorSparkOptimized` explaining the problem and how to reproduce.

File: src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTest.java [hunk 36]
```diff
@@ -314,4 +316,122 @@ public void testLogLog10conversions(){
...
+        Assert.assertEquals(roundToNDecimalPlaces(in, n), out);
+    }
+
+    @Test(expectedExceptions = IllegalArgumentException.class)
+    public void testRoundingError() {
+        roundToNDecimalPlaces(1.1234, -1);
+    }
+
+    @Test
+    public void testAddDoubles() throws Exception {
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTest.java]: This test really needs an explanatory comment explaining what it's testing.

**Comment by droazen** [comment]
Second-pass review complete -- back to @akiezun. Please rebase/merge after addressing remaining comments, and be sure to file a bug against `BaseRecalibratorSparkOptimized`

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java (hunk 26 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java]: fixed

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java (hunk 27 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/BQSRPipelineSpark.java]: good catch. fixed throughout and remove the option of running without DBDNBP (`run_without_dbsnp_potentially_ruining_quality`)

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java (hunk 28 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java]: fixed

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java (hunk 29 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/ReadsPipelineSpark.java]: yes, thanks

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java (hunk 30 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: i like them because they remove clutter and makes code easier to read,  but i dont care that much

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java (hunk 31 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java]: ok

File: src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationReport.java (hunk 32 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/utils/recalibration/RecalibrationReport.java]: meh, until things show up on the profiler, i'm reluctant to complicate code

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java (hunk 33 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: https://github.com/broadinstitute/gatk/issues/1118

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java (hunk 34 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkIntegrationTest.java]: i think @jean-philippe-martin switched to a different input file for the cloud because of the reference. but the expected output was not updated. #1118 will fix that

File: src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkOptimizedIntegrationTest.java (hunk 35 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkOptimizedIntegrationTest.java]: done. added a reference to https://github.com/broadinstitute/gatk/issues/1119

File: src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTest.java (hunk 36 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/utils/MathUtilsUnitTest.java]: ok, done
