### PR TITLE
Removed instances of String.format to help funcotator performance

### LINKED ISSUE #6574: Funcotator Speed Regression
When originally released, Funcotator had blistering speed.  In the latest tests, this speed has dropped off to be a very small fraction of that original data processing rate.

We need to profile Funcotator to determine the source of the slowdown, and then we must remedy it.

In particular the hg38 acceptance testing dataset (`hg38_trio.vcf`) has slowed significantly.

### PR DESCRIPTION
**Pull request by haileypfox**
resolves #6574

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java [hunk 1]
```diff
@@ -13,6 +13,7 @@
 import java.util.LinkedHashSet;
 import java.util.List;
 import java.util.stream.Collectors;
+import org.apache.commons.lang3.StringUtils;
```
Comment (jonn-smith) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotation.java:16]: Looks like this import was added but isn't needed.  Can you remove it?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 2]
```diff
@@ -2153,9 +2153,15 @@ static String sanitizeFuncotationFieldForVcf(final String individualFuncotationF
         final List<String> badLetters = Arrays.asList(",", ";", "=", "\t", VcfOutputRenderer.HEADER_LISTED_FIELD_DELIMITER, " ", "\n", VcfOutputRenderer.ALL_TRANSCRIPT_DELIMITER);
 
         // Encoded version:
-        final List<String> cleanLetters = badLetters.stream().map(
-                s -> "_%" + String.format("%02X", s.getBytes(StandardCharsets.US_ASCII)[0]) + "_")
-                .collect(Collectors.toList());
+        final List<String> cleanLetters = new ArrayList<>();
+        for(String s: badLetters) {
+            String hex = Integer.toHexString(s.getBytes(StandardCharsets.US_ASCII)[0] & 0xFF).toUpperCase();
```
Comment (jonn-smith) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java:2158]: This is great, but I think you can simplify it into an if statement with one assignment in each branch:

```
if (s.getBytes(StandardCharsets.US_ASCII)[0] < 16) {
    // Need to add leading zero
}
else {
    // straight conversion
}
```

Then you can do one assignment (with a couple of `+` operations) in each of those conditions.

**Review by jonn-smith — CHANGES_REQUESTED** [review]
Looks great - just a couple minor things.

**Review by jonn-smith — APPROVED** [review]
