### PR TITLE
fix 4648

### LINKED ISSUE #4648: Error in StructuralVariationDiscoveryPipelineSpark: invalid interval in CpxVariantInterpreter
Several of our HGSV snapshot samples are failing with current master due to an exception in `CpxVariantInterpreter`. For example, sample HG00732 fails with this stacktrace:

```
18/04/11 14:30:28 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 2.0 in stage 42.0 (TID 60116, cwhelan-hg00732-cram-samtools-bam-feature-w-5.c.broad-dsde-methods.internal, executor 27): java.lang.IllegalArgumentException: Invalid interval. Contig:chr19 start:33757506 end:33757488
        at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:687)
        at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:61)
        at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:37)
        at org.broadinstitute.hellbender.tools.spark.sv.discovery.alignment.ContigAlignmentsModifier.computeNewRefSpanAndCigar(ContigAlignmentsModifier.java:159)
        at org.broadinstitute.hellbender.tools.spark.sv.discovery.alignment.ContigAlignmentsModifier.clipAlignmentInterval(ContigAlignmentsModifier.java:42)
        at org.broadinstitute.hellbender.tools.spark.sv.discovery.inference.CpxVariantInterpreter.removeOverlap(CpxVariantInterpreter.java:179)
        at org.broadinstitute.hellbender.tools.spark.sv.discovery.inference.CpxVariantInterpreter.deOverlapAlignments(CpxVariantInterpreter.java:122)
        at org.broadinstitute.hellbender.tools.spark.sv.discovery.inference.CpxVariantInterpreter.furtherPreprocess(CpxVariantInterpreter.java:79)
        at org.broadinstitute.hellbender.tools.spark.sv.discovery.inference.CpxVariantInterpreter.lambda$inferCpxVariant$bdd686a3$1(CpxVariantInterpreter.java:51)
        at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1040)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:149)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by SHuang-Broad**
fix #4648 

The problems are in clipping the alignments when de-overlapping the alignments, particularly computing the new ref and read spans.

Also adds a check on arguments used for constructing alignments, which helped finding errors in test data (now corrected)

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/ContigAlignmentsModifier.java [hunk 1]
```diff
@@ -39,17 +40,30 @@ public static AlignmentInterval clipAlignmentInterval(final AlignmentInterval in
...
+
+    private static Tuple2<Integer, Integer> computeNewReadSpan(final int originalContigStart, final int originalContigEnd,
+                                                               final Cigar newCigarAlong5to3DirectionOfContig,
+                                                               final int clipLengthOnRead, final boolean clipFrom3PrimeEnd) {
         final int newTigStart, newTigEnd;
         if (clipFrom3PrimeEnd) {
-            newTigStart = input.startInAssembledContig;
-            newTigEnd   = input.endInAssembledContig - clipLengthOnRead;
+            newTigStart = originalContigStart;
+            newTigEnd   = Math.min(originalContigEnd - clipLengthOnRead,
```
Comment (cwhelan) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/alignment/ContigAlignmentsModifier.java]: As discussed in person maybe add a couple of notes in comments to highlight why this is necessary?
