### PR TITLE
Fix bug making HaplotypeCaller fail for non-diploid samples.  Closes #2214.

### LINKED ISSUE #2214: HaplotypeCaller failing or ploidy != 2
This is due to`GATKVAriantContextUtils::makeGenotypeCall` using `GenotypeLikelihoods.getAlleles`, which throws an error because you have to explicitly tell `GenotypeLikelihoods` to initialize ploidies != 2.  We can fix this by explicitly initializing but it seems that `GenotypeLikelihoodCalculators` has the same functionality but more robust.

### PR DESCRIPTION
**Pull request by davidbenjamin**
@takutosato can you review this fix of the bug we were discussing with @droazen?  For comparison, `AlleleSubsettingUtils` uses `GenotypeLikelihoodCalculators` in a similar way.

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java [hunk 1]
```diff
@@ -274,9 +279,10 @@ public static void makeGenotypeCall(final int ploidy,
                 gb.alleles(noCallAlleles(ploidy)).noGQ();
             } else {
                 final int maxLikelihoodIndex = MathUtils.maxElementIndex(genotypeLikelihoods);
-                final List<Allele> maxLikelihoodAlleles = GenotypeLikelihoods.getAlleles(maxLikelihoodIndex, ploidy).stream()
-                        .map(allelesToUse::get).collect(Collectors.toList());
-                gb.alleles(maxLikelihoodAlleles);
+                final GenotypeLikelihoodCalculator glCalc = GL_CALCS.getInstance(ploidy, allelesToUse.size());
+                final GenotypeAlleleCounts alleleCounts = glCalc.genotypeAlleleCountsAt(maxLikelihoodIndex);
+
+                gb.alleles(alleleCounts.asAlleleList(allelesToUse));
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java]: Can you add a unit test that calls `makeGenotypeCall()` with various ploidies != 2 that fails before the fix and passes after the fix?

Comment (davidbenjamin) [inline src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java]: @droazen Done.  The unit test was already testing ploidy !=2, but was calling the initializer explicitly.  All I had to do was remove that.

**Comment by takutosato** [comment]
Yup I will review

**Comment by takutosato** [comment]
👍 Looks good!

**Comment by davidbenjamin** [comment]
@droazen do you approve?

File: src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java [hunk 2]
```diff
@@ -1364,8 +1362,6 @@ public void testUpdateGenotypeAfterSubsetting(final int ploidy,
                                                   final List<Allele> allelesToUse,
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java]: Might want to rename this test method to reflect the new method name -- eg., `testMakeGenotypeCall`

File: src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java [hunk 3]
```diff
@@ -274,9 +279,10 @@ public static void makeGenotypeCall(final int ploidy,
                 gb.alleles(noCallAlleles(ploidy)).noGQ();
             } else {
                 final int maxLikelihoodIndex = MathUtils.maxElementIndex(genotypeLikelihoods);
-                final List<Allele> maxLikelihoodAlleles = GenotypeLikelihoods.getAlleles(maxLikelihoodIndex, ploidy).stream()
-                        .map(allelesToUse::get).collect(Collectors.toList());
-                gb.alleles(maxLikelihoodAlleles);
+                final GenotypeLikelihoodCalculator glCalc = GL_CALCS.getInstance(ploidy, allelesToUse.size());
+                final GenotypeAlleleCounts alleleCounts = glCalc.genotypeAlleleCountsAt(maxLikelihoodIndex);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java]: Have you confirmed that the performance of this method is roughly the same as before?

**Comment by droazen** [comment]
@davidbenjamin A few last comments -- merge after addressing

File: src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java (hunk 2 above)
Comment (davidbenjamin) [inline src/test/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtilsUnitTest.java]: done

File: src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java (hunk 3 above)
Comment (davidbenjamin) [inline src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java]: Yes, confirmed.  Also, it appears to fix a bug because the htsjdk code had a hard-wired assumption that diploid == biallelic.

File: src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java [hunk 4]
```diff
@@ -37,6 +40,8 @@
 
     public static final int DEFAULT_PLOIDY = HomoSapiensConstants.DEFAULT_PLOIDY;
 
+    private static final GenotypeLikelihoodCalculators GL_CALCS = new GenotypeLikelihoodCalculators();
```
Comment (davidbenjamin) [inline src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVariantContextUtils.java]: Yes, there is a shared cache but this cache is filled completely in the constructor of `GL_CALCS` and afterwards never mutates.  Thus there is no danger in sharing it between threads.
