### PR TITLE
Fixed SplitNCigarReads ArrayIndexOutOfBounds error for short reads with deletions

### LINKED ISSUE #5230: Exception in SplitNCigarReads
@jamesemery, researcher has uploaded data to </humgen/gsa-scr1/pub/incoming/Exception_in_SplitNCigarReads.tgz> and has clarified a few other details within the forum thread, e.g. running ValidateSamFile `IGNORE=MISSING_TAG_NM IGNORE=MATE_NOT_FOUND` allows for validation.

Thanks for looking into this.

---

Hello,

I am getting the following exception when running SplitNCigarReads on RNA-Seq data using GATK 4.0.8.1:
```
java.lang.ArrayIndexOutOfBoundsException: 100
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.overhangingBasesMismatch(OverhangFixingManager.java:313)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.fixSplit(OverhangFixingManager.java:252)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.OverhangFixingManager.addReadGroup(OverhangFixingManager.java:209)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads.splitNCigarRead(SplitNCigarReads.java:270)
	at org.broadinstitute.hellbender.tools.walkers.rnaseq.SplitNCigarReads.firstPassApply(SplitNCigarReads.java:180)
	at org.broadinstitute.hellbender.engine.TwoPassReadWalker.lambda$traverseReads$0(TwoPassReadWalker.java:62)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.TwoPassReadWalker.traverseReads(TwoPassReadWalker.java:60)
	at org.broadinstitute.hellbender.engine.TwoPassReadWalker.traverse(TwoPassReadWalker.java:42)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:979)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:137)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:182)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:201)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

Command:
```
./gatk/gatk \
   SplitNCigarReads \
   --reference $REF \
   --input test3.bam \
   --output output.bam \
   --verbosity DEBUG \
    > split.log 2>&1
```
Running ValidateSamFile does not reveal anything suspicious and visual inspection of the reads also appears to be fine.

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/12801/exception-in-splitncigarreads/p1

### PR DESCRIPTION
**Pull request by jamesemery**
Before we were limiting the edge fixing from trimming to large a percentage of the reads, but we computed this percentage based on the reference length of the read, not the number of bases. This resulted in cases where we might check more than the number of bases in the read for mismatches. 

Fixes #5230

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java [hunk 1]
```diff
@@ -140,15 +141,15 @@ public OverhangFixingManager(final SAMFileHeader header,
      * @param start   the start of the split, inclusive
      * @param end     the end of the split, inclusive
      */
-    public void addSplicePosition(final String contig, final int start, final int end) {
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java]: Update the doc to explain what it returns.    I assume this is just to make the testing simpler?

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java [hunk 2]
```diff
@@ -457,6 +463,12 @@ public int compare(final List<SplitRead> readgroup1, final List<SplitRead> readg
         }
     }
 
+    public SplitRead getSplitRead(final GATKRead read){
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java]: Why did you pull these out into class methods?  It seems more readable to just call the constructors like you were before.  Maybe I'm missing some use of them.  Can you at least make them static if you need them?

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManagerUnitTest.java [hunk 3]
```diff
@@ -271,4 +273,12 @@ public void testUnalignedReadNotClearingReads() {
         Assert.assertEquals(manager.getReadsInQueueForTesting().size(), 1);
     }
 
+    @Test
+    public void testReadWithDeletionsWindowSpanning() {
+        final OverhangFixingManager manager = new OverhangFixingManager(getHG19Header(), null, hg19GenomeLocParser, hg19ReferenceReader, 100, 100, 30, false, true);
+        OverhangFixingManager.Splice splice = manager.addSplicePosition("1",6816, 11247);
+        GATKRead read = ArtificialReadUtils.createArtificialRead(hg19Header,"read1",0,11244, new byte[100], new byte[100],"97S2M18D1M");
```
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManagerUnitTest.java]: I hate to make this particular nitpick, but could you fix the spaces in this list of parameters, they're really atrociously inconsistent.

Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManagerUnitTest.java]: Maybe add a line of documentation to this test explaining it a bit better, I'm not going to have any idea what it's for in the future.  There's lots of very specific looking numbers, and it's not clear which ones are important.

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java [hunk 4]
```diff
@@ -246,18 +249,21 @@ void fixSplit(final SplitRead splitRead, final Splice splice) {
 
         GenomeLoc readLoc = splitRead.unclippedLoc;
         GATKRead read = splitRead.read;
-        final int readReferenceLength = read.getEnd() - read.getStart() + 1;
-
+        // Compute the number of non-clipped bases consumed according to the cigar
+        final int readBasesLength = Utils.stream(read.getCigar().getCigarElements())
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java]: neat

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java (hunk 2 above)
Comment (jamesemery) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java]: Again I needed them for testing, and I cant actually make them static unfortunately, because they rely on the inner classes which cant be made static because they use the managers dictionary

**Comment by jamesemery** [comment]
thank you for the review @lbergelson, back to you

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java (hunk 2 above)
Comment (lbergelson) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/OverhangFixingManager.java]: Oh, gross, I didn't see that.
