### PR TITLE
Fixed a NPE when null ReadNameRegex provided to MDSpark

### LINKED ISSUE #7001: java.lang.NullPointerException when running MarkDuplicatesSpark with "--read-name-regex null"
Hi,
  I run the code below to to skip optical duplicate detection during marking duplicate.
`java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=trueDsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gatk-4.1.8.0/gatk-package-4.1.8.0-local.jar MarkDuplicatesSpark --spark-master local[28] --conf spark.local.dir=/datatmp/ -I ./A.sort.bam -O ./A.sort.bam.Mdup.bam -M ./A.sort.bam.Md.metrics.txt  --tmp-dir /datatmp/ --conf spark.network.timeout=200h --conf spark.executor.heartbeatInterval=100h --read-name-regex null`
It reports the error below.
`20/12/15 11:43:00 ERROR Executor: Exception in task 15.0 in stage 7.0 (TID 12538)
java.lang.NullPointerException
        at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSparkUtils.lambda$handleFragments$12(MarkDuplicatesSparkUtils.java:395)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
        at java.util.stream.ReferencePipeline.max(ReferencePipeline.java:515)
        at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSparkUtils.handleFragments(MarkDuplicatesSparkUtils.java:396)
        at org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSparkUtils.lambda$markDuplicateRecords$fa45b352$1(MarkDuplicatesSparkUtils.java:304)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$3$1.apply(JavaRDDLike.scala:143)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$3$1.apply(JavaRDDLike.scala:143)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:187)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
`

Can you give me some advice?
Thanks,
sun

### PR DESCRIPTION
**Pull request by jamesemery**
Fixes #7001

### CODE REVIEW

File: src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java [hunk 1]
```diff
@@ -495,6 +496,33 @@ public void testAssertCorrectSortOrderMultipleBamsOverriding() {
...
     }
 
+    @Test
+    public void testNullOpticalDuplicates() {
+        final File output = createTempFile("supplementaryReadUnmappedMate", "bam");
+        final ArgumentsBuilder args = new ArgumentsBuilder();
+        args.addOutput(output);
+        args.addInput(new File(TEST_DATA_DIR,"optical_dupes.bam"));
+        args.addFlag(MarkDuplicatesSpark.ALLOW_MULTIPLE_SORT_ORDERS_IN_INPUT_ARG);
+        args.add(OpticalDuplicatesArgumentCollection.READ_NAME_REGEX_LONG_NAME, "null");
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java:506]: Is this really testing with an actual null pointer in the `READ_NAME_REGEX` field, or just the literal String "null"?

Can you add in a unit test showing that `OpticalDuplicateFinder` can be constructed from a null READ_NAME_REGEX, and that methods like `addLocationInformation()` can still function?

**Review by droazen — CHANGES_REQUESTED** [review]
@jamesemery Back to you with a question about your tests

File: src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java (hunk 1 above)
Comment (jamesemery) [reply src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java:506]: Yes it is an actual `null` reference that gets passed. I believe the argument parser interprets "null" as `null` which is expected behavior in the picard MarkDuplicates documentation for disabling the OpticalDuplicates finder. In GATK4 we ported the same method but we accidentally encased it in a ternary that nulled out the Finder object (which should not have happened) and caused the exception.

Comment (jamesemery) [reply src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java:506]: This test does actually assert that the optical dupes finder works as intended when "null" is provided. It is intended to count NOTHING as an optical duplicate and this test asserts that reads that normally would count as optical duplicates are treated as such. I'm somewhat remiss to add that test since the OpticalDuplicatesFinder object is a picard class that we call into in GATK.

**Comment by jamesemery** [comment]
@droazen

File: src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java (hunk 1 above)
Comment (jamesemery) [reply src/test/java/org/broadinstitute/hellbender/tools/spark/pipelines/MarkDuplicatesSparkIntegrationTest.java:506]: In picard `OpticalDuplicatesFinder` there is the following exit case for a null regex that is the intended target here: 
```
if (this.readNameRegex == null || length < 2 || length > maxDuplicateSetSize) {
            return opticalDuplicateFlags;
        }
````

**Review by droazen — APPROVED** [review]
:+1:
