### PR TITLE
fix for IAE in BAQ

### LINKED ISSUE #1234: ReadsPipelineSpark fails with IllegalArgumentException
```
spark-submit --class org.broadinstitute.hellbender.Main \
--deploy-mode client \
--master yarn-client \
--driver-memory 8G \
--conf spark.driver.maxResultSize=0 \
--conf spark.driver.userClassPathFirst=true \
--conf spark.executor.userClassPathFirst=true \
--conf spark.io.compression.codec=lzf \
--conf spark.yarn.executor.memoryOverhead=600 \
--executor-memory ${execMem}g \
--num-executors $execs \
--executor-cores $cores \
bin/cleanHellbender/gatk/build/libs/gatk-all-*-spark.jar \
ReadsPipelineSpark \
--sparkMaster yarn-client \
-I hdfs:///user/akiezun/CEUTrio.HiSeq.WEx.b37.NA12892.bam \
-R hdfs:///user/droazen/bqsr/human_g1k_v37.2bit \
--programName ${name} \
-O $bamout \
--knownSites hdfs:////user/akiezun/dbsnp_138.b37.excluding_sites_after_129.vcf \
--emit_original_quals \
--duplicates_scoring_strategy SUM_OF_BASE_QUALITIES
```
exec=24
cores=5
execMem=25

fails with 

```
java.lang.IllegalArgumentException: SimpleInterval is 1 based, so start must be >= 1, start: 0
	at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:58)
	at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:33)
	at org.broadinstitute.hellbender.utils.baq.BAQ.getReferenceWindowForRead(BAQ.java:525)
	at org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine$BQSRReferenceWindowFunction.apply(BaseRecalibrationEngine.java:46)
	at org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine$BQSRReferenceWindowFunction.apply(BaseRecalibrationEngine.java:41)
	at org.broadinstitute.hellbender.engine.spark.BroadcastJoinReadsWithRefBases.lambda$addBases$c54addeb$1(BroadcastJoinReadsWithRefBases.java:52)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1030)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1030)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.convert.Wrappers$IteratorWrapper.next(Wrappers.scala:30)
	at org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn.lambda$apply$26a6df3e$1(BaseRecalibratorSparkFn.java:30)

```

### PR DESCRIPTION
**Pull request by akiezun**
fixes #1234 
i checked that the original error goes away

@droazen can you have a quick look?

### CODE REVIEW

File: src/test/java/org/broadinstitute/hellbender/utils/baq/BAQUnitTest.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+import org.broadinstitute.hellbender.utils.read.ArtificialReadUtils;
+import org.broadinstitute.hellbender.utils.read.GATKRead;
+import org.broadinstitute.hellbender.utils.test.BaseTest;
+import org.testng.Assert;
+import org.testng.annotations.Test;
+
+public final class BAQUnitTest extends BaseTest{
+
+    @Test //regression test for https://github.com/broadinstitute/gatk/issues/1234
+    public void testGetReferenceWindowForRead() throws Exception {
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/baq/BAQUnitTest.java]: Test case needs a more specific name, since it's not testing `BAQ.getReferenceWindowForRead()` comprehensively, it's just testing truncation at contig start. How about `testGetReferenceWindowForReadStopsAtContigStart`

**Comment by droazen** [comment]
Looks good -- one comment to address, then go ahead and merge. Back to @akiezun

File: src/test/java/org/broadinstitute/hellbender/utils/baq/BAQUnitTest.java (hunk 1 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/utils/baq/BAQUnitTest.java]: fixed
