### PR TITLE
fixing IndexOutOfBoundsException in GenotypingEngine

### LINKED ISSUE #2530: IndexOutOfBounds due to change in #2528
The change in #2528 introduced an IndexOutOfBounds exception because we don't check for empty list.  

I'm not sure why this isn't a problem in the analogous code in gatk3.  

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:270)
	at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:204)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.regenotypeVC(GenotypeGVCFs.java:174)
	at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:157)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:104)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:102)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:664)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:116)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
```

### PR DESCRIPTION
**Pull request by lbergelson**
* changes to GenotypingEngine.calculateGenotypes in #2528 introduced a regression that caused IndexOutOfBoundsException
* fixes #2530 by preventing the exception and adding tests

@davidbenjamin Note that I also changed the condition from "first alt allele is NON_REF" to "any alt allele is NON_REF".  This more accurately matches what the comment says, but let me know if you think it's not the right thing.

### CODE REVIEW

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java [hunk 1]
```diff
@@ -89,4 +93,18 @@ public void testCalculateGenotypes() {
         final VariantContext vcOut1 = genotypingEngine.calculateGenotypes(vcSpanDel, GenotypeLikelihoodsCalculationModel.INDEL, null);
         Assert.assertFalse(vcOut1.getAlleles().contains(Allele.SPAN_DEL));
     }
+
+    @Test //test for https://github.com/broadinstitute/gatk/issues/2530
+    public void testNoIndexOutOfBoundsExceptionWhenSubsettingToNoAlleles(){
+        final VariantContext vc = new VariantContextBuilder(null, "1", 100, 100, Arrays.asList(refA, altT))
+                .genotypes(GenotypeBuilder.create(SAMPLES.getSample(0), Arrays.asList(refA, altT))).make();
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java]: This looks like a het genotype, but the test case is named "no alleles"?

Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java]: Either the test case is not legit or we need an explanatory comment here.

**Comment by droazen** [comment]
:+1: Merge after addressing the issue with your test case (show that the test case fails before the fix and passes after it)

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java (hunk 1 above)
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypingEngineUnitTest.java]: it works either way since the alt allele gets filtered out without any pl, but I've switch to a hom ref to be cleaer
