### PR TITLE
Fixed a bug where force calling alleles were lost upon trimming by placing allele injection after trimming

### LINKED ISSUE #7672: Mutect2 mitoochondria mode force-calling misses some alleles
This request was created from a contribution made by Rahul Gupta on February 03, 2022 19:42 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/4417613488411-In-Mutect2-force-calling-allele-via-alleles-does-not-force-call-the-allele](https://gatk.broadinstitute.org/hc/en-us/community/posts/4417613488411-In-Mutect2-force-calling-allele-via-alleles-does-not-force-call-the-allele)

\--

If not an error, choose a category for your question(REQUIRED):  
  
c) Why do I see (......)?

GATK version: 4.2.4.1

Hi all,

I'm running Mutect2 over samples for which I have provided a VCF of alleles that I would like force-called. In 99% of cases this works great, but in a few instances a couple of alleles that I have included for force-calling do not actually make it into the output calls VCF.

My command is:

gatk --java-options -Xmx3000m Mutect2 \\  
  
\-R /data\_in/MY1776/MY1776.self.ref.shifted\_by\_8000\_bases.fasta \\  
  
\-I /data\_in/MY1776/self\_realigned\_shifted.bam \\  
  
\--read-filter MateOnSameContigOrNoMappedMateReadFilter \\  
  
\--read-filter MateUnmappedAndUnmappedReadFilter \\  
  
\-O /out\_default.vcf \\  
  
\--alleles /data\_in/MY1776/MY1776.self.ref.reversed.selfRef.shifted.homoplasmies.vcf.bgz \\  
  
\--annotation StrandBiasBySample \\  
  
\--mitochondria-mode \\  
  
\--max-reads-per-alignment-start 75 \\  
  
\--max-mnp-distance 0 \\  
  
\-L chrM:8023-9140 \\  
  
\--genotype-filtered-alleles \\  
  
\--debug-assembly-variants-out /rej.vcf \\  
  
\--bam-output bamout.bam

In this instance the variant in question is listed in the rej.vcf file obtained via `--debug-assembly-variants-out`. I have examined `bamout.bam` as well as the input bam and there appears to be ample coverage at the site of interest (the T at position 8316 is the position of interest, highlighted):

I have tried running this with some of the additional parameters in \[[https://gatk.broadinstitute.org/hc/en-us/articles/360043491652-When-HaplotypeCaller-and-Mutect2-do-not-call-an-expected-variant\](/hc/en-us/articles/360043491652-When-HaplotypeCaller-and-Mutect2-do-not-call-an-expected-variant)](https://gatk.broadinstitute.org/hc/en-us/articles/360043491652-When-HaplotypeCaller-and-Mutect2-do-not-call-an-expected-variant](/hc/en-us/articles/360043491652-When-HaplotypeCaller-and-Mutect2-do-not-call-an-expected-variant)) (namely `--linked-de-bruijn-graph` and `--recover-all-dangling-branches`) to no avail. Coverage is very deep at this position (>2000x). Notably if I edit the input to `--alleles` and change the allele of interest (8316:T>A) to anything else (8316:T>C or T>G) it appropriately shows up in the output VCF.

What am I missing here? Let me know if you have any solutions or if you need any additional files.

UPDATE: Adding `--disable-adaptive-pruning` now produces the variant of interest specified in --alleles, but also adds several other new calls, in case that is helpful in isolating where this force-call variant is being lost.<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/270138'>Zendesk ticket #270138</a>)<br> gz#270138</i>

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #7672.

@ldgauthier This is the bug fix for Sarah Calvo.  The allele was lost when trimming caused its haplotype to start with a deletion.  The solution is to inject force-calling alleles after trimming.  Are you able to review?

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java [hunk 1]
```diff
@@ -599,6 +599,11 @@ public ActivityProfileState isActive( final AlignmentContext context, final Refe
         }
 
         final SortedSet<VariantContext> allVariationEvents = untrimmedAssemblyResult.getVariationEvents(hcArgs.maxMnpDistance);
+        for (final VariantContext given : givenAlleles) {
+            if (allVariationEvents.stream().noneMatch(vc -> vc.getStart() == given.getStart() && vc.getAlternateAllele(0).basesMatch(given.getAlternateAllele(0)))) {
```
Comment (ldgauthier) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java:603]: These will always be trimmed right?  (And always biallelic?) Because they're each for a single haplotype?  If you agree, then let's add a comment for posterity.

**Review by ldgauthier — APPROVED** [review]
Thanks for the fix and great cleanup!  I'd like you to add one comment for clarity, but otherwise LGTM!
