### PR TITLE
Fix non-determinism in KbestHaplotypeFinding/SeqGraphZippingCode

### LINKED ISSUE #6003: Nondeterministic behaviour in graph processing
----

### Affected tool(s) or class(es)
Mutect2, Haplotypecaller

### Affected version(s)
4.1.0

### Description 
It is not an actual accuracy bug but I wanted to share it with you in case you are not aware of it. If you look at BaseGraph.java. There are 4 places that you use "Collectors.toSet()". This converts a stream to an unordered set. The final order is dependant on the memory address that each element occupies so the order of result unordered set is not deterministic and can differ from run to run. 

This behavior is not problematic as long as we do not traverse the set in order. But let's look at MergeDiamonds.java as an example
`        final Set<SeqVertex> middles = getGraph().outgoingVerticesOf(top);
`
`        for ( final SeqVertex mi : middles ) {
`
First, we make unordered set "middles" and then traverse it. Merging diamonds is actually really sensitive which diamond you merge first and can result in different graphs if you change the order. This was not that important before but it seems that with the new chain pruning functionality that you put in mutect2. Sensitivity went up. and now we can actually see different results every time we run the mutect2.

I was wondering if it makes sense to change this? The way that we fixed it for ourselves was to change it to linkedHashSet to preserve the order.

_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

### PR DESCRIPTION
**Pull request by jamesemery**
After some painstaking debug work with @tlangs we managed to isolate it to the graphing code and furthermore find what methods in our part of the graph code produce non-determinisitc output. This doesn't address the underlying issue which was that the order in the graph zipping can make a significant difference in the weights of edges in the graph code which effects the found haplotypes. This does however apparently make the haplotype caller outputs more deterministic though this still doesn't quite explain the apparent connection to NIO.

Fixes #6003

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java [hunk 1]
```diff
@@ -267,20 +267,20 @@ private void printDebugGraphTransform(final BaseGraph<?,?> graph, final String f
         }
     }
 
-    private AssemblyResult cleanupSeqGraph(final SeqGraph seqGraph) {
-        printDebugGraphTransform(seqGraph, "sequenceGraph.1.dot");
+    private AssemblyResult cleanupSeqGraph(final SeqGraph seqGraph, final Haplotype refHaplotype) {
+        printDebugGraphTransform(seqGraph, refHaplotype.getLocation() + "-sequenceGraph."+seqGraph.getKmerSize()+".1.0.non_ref_removed.dot");
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java]: Can you refactor so that we don't construct these Strings at all if we're not in debugging mode?

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/BaseGraph.java [hunk 2]
```diff
@@ -79,15 +79,15 @@ public final boolean isSink( final V v ) {
...
+        return vertexSet().stream().filter(v -> isSource(v)).collect(Collectors.toCollection(LinkedHashSet::new));
     }
 
     /**
      * Get the set of sink vertices of this graph
      * @return a non-null set
      */
     public final Set<V> getSinks() {
-        return vertexSet().stream().filter(v -> isSink(v)).collect(Collectors.toSet());
+        return vertexSet().stream().filter(v -> isSink(v)).collect(Collectors.toCollection(LinkedHashSet::new));
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/graphs/BaseGraph.java]: Add a comment here (and at similar lines below) about why this is important.

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java (hunk 1 above)
Comment (jamesemery) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java]: I added guarding if statements to the outside of every call to this method.

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java [hunk 3]
```diff
@@ -159,6 +162,13 @@ public HaplotypeCallerEngine( final HaplotypeCallerArgumentCollection hcArgs, bo
         this.aligner = SmithWatermanAligner.getAligner(hcArgs.smithWatermanImplementation);
         forceCallingAllelesPresent = hcArgs.alleles != null;
         initialize(createBamOutIndex, createBamOutMD5);
+        if (hcArgs.assemblyStateOutput != null) {
+            try {
+                assemblyDebugOutStream = new PrintStream(Files.newOutputStream(IOUtils.getPath(hcArgs.assemblyStateOutput)));
+            } catch (IOException e) {
+                e.printStackTrace();
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java]: Throw a `UserException.CouldNotCreateOutputFile` here instead of printing the stack trace.

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java [hunk 4]
```diff
@@ -258,29 +258,35 @@ private static boolean pathIsTooDivergentFromReference(final Cigar c) {
      */
     private void printDebugGraphTransform(final BaseGraph<?,?> graph, final String fileName) {
         File outputFile = new File(debugGraphOutputPath, fileName);
-        if ( debugGraphTransformations ) {
-            if ( PRINT_FULL_GRAPH_FOR_DEBUGGING ) {
-                graph.printGraph(outputFile, pruneFactor);
-            } else {
-                graph.subsetToRefSource(10).printGraph(outputFile, pruneFactor);
-            }
+        if ( PRINT_FULL_GRAPH_FOR_DEBUGGING ) {
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java]: Since you removed the `if ( debugGraphTransformations ) {` guard from this method, did you check all usages of it to ensure that the callsites are all now checking the `debugGraphTransformations` flag?

Comment (jamesemery) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/readthreading/ReadThreadingAssembler.java]: Yes. Every usage. I will add a comment to be doubly sure that its someone elses fault if that causes problems in the future.

**Comment by jamesemery** [comment]
@droazen responded to your comments. Added a better exception and commented the method that lost its defensive check to shift the blame to others when mistakes are made in the future.

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java [hunk 5]
```diff
@@ -130,6 +130,12 @@ protected ReadThreadingAssemblerArgumentCollection getReadThreadingAssemblerArgu
     @Argument(fullName = "just-determine-active-regions", doc = "Just determine ActiveRegions, don't perform assembly or calling", optional = true)
     public boolean justDetermineActiveRegions = false;
 
+
+    @Hidden
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java]: I dislike hidden options, but /shrug

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java [hunk 6]
```diff
@@ -130,6 +130,12 @@ protected ReadThreadingAssemblerArgumentCollection getReadThreadingAssemblerArgu
...
+    @Advanced
+    @Argument(fullName="debug-assembly-region-state", doc="Write output files for assembled regions with read summaries and called haplotypes", optional = true)
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerArgumentCollection.java]: The doc should explain what the the value is supposed to be, it sounds like it should be a boolean.

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java [hunk 7]
```diff
@@ -71,6 +73,8 @@
 
     private AssemblyRegionTrimmer trimmer = new AssemblyRegionTrimmer();
 
+    private PrintStream assemblyDebugOutStream;
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerEngine.java]: final?

**Comment by jamesemery** [comment]
@lbergelson @droazen and here i was thinking this simple fix would for whatever reason be easy and painless to get in...
