### PR TITLE
fix code duplication in ReadPosRankSumTest and its allele-specific version

### LINKED ISSUE #1882: remove code redundancy AS_ReadPosRankSumTest vs ReadPosRankSumTest
there's some highly redundant code in those classes

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #1882.

Normally I assign the author of the issue for this kind of stuff, but Adam is no longer with us.  @ldgauthier would you mind looking and/or suggesting anything else on your wish list for the annotations code?

### CODE REVIEW

**Comment by ldgauthier** [comment]
I'll do the review. This is a great opportunity for me to get my feet wet
in Gatk4.

On May 4, 2017 12:18 AM, "David Benjamin" <notifications@github.com> wrote:

Closes #1882 <https://github.com/broadinstitute/gatk/issues/1882>.

Normally I assign the author of the issue for this kind of stuff, but Adam
is no longer with us. @ldgauthier <https://github.com/ldgauthier> would you
mind looking and/or suggesting anything else on your wish list for the
annotations code?
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/broadinstitute/gatk/pull/2657
Commit Summary

   - code duplication in read pos rank sum and its allele-specific version

File Changes

   - *M* src/main/java/org/broadinstitute/hellbender/
   tools/walkers/annotator/ReadPosRankSumTest.java
   <https://github.com/broadinstitute/gatk/pull/2657/files#diff-0> (4)
   - *M* src/main/java/org/broadinstitute/hellbender/
   tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java
   <https://github.com/broadinstitute/gatk/pull/2657/files#diff-1> (27)

Patch Links:

   - https://github.com/broadinstitute/gatk/pull/2657.patch
   - https://github.com/broadinstitute/gatk/pull/2657.diff

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/broadinstitute/gatk/pull/2657>, or mute the thread

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java [hunk 1]
```diff
@@ -37,9 +38,10 @@
  * </ul>
  *
  */
-//FIXME - this whole class is essentially code duplicated from ReadPosRankSumTest
 public class AS_ReadPosRankSumTest extends AS_RankSumTest implements AS_StandardAnnotation {
 
+    final ReadPosRankSumTest readPosRankSumTest = new ReadPosRankSumTest();
```
Comment (ldgauthier) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java]: I really wanted this class to inherit from AS_RankSumTest _and_ ReadPosRankSumTest, so I picked one and copied the code from the other.  This is far more elegant.

**Comment by ldgauthier** [comment]
Ha, this PR was much tinier than I expected -- feet are barely damp.

My "wishlist" would include a much bigger refactor because I made a mess in Java7 and didn't have the time to clean up (especially with generics) after we switched in Java8.  I'm still tinkering with the rank sum tests though, so it's not worth tackling the refactor until those are good to go.

:+1:

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java (hunk 1 above)
Comment (davidbenjamin) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java]: I feel like the *real* way to do this is via a decorator that makes some annotation allele-specific, but I have no idea how to do that in Java.

Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java]: It looks to me like `getElementForRead()`, at least, could be made static. I suspect that `isUsableRead()` could be refactored to be static as well. Then you wouldn't have to instantiate `ReadPosRankSumTest` like this here.

Comment (davidbenjamin) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/AS_ReadPosRankSumTest.java]: @droazen I couldn't figure out a way to beat code duplication for `isUsableRead` -- since you can't override `static` methods, every option was a lot more fuss than it was worth.  I made `getElementForRead` delegate to a static method in order to avoid instantiating a `ReadPosRankSumTest`.

**Comment by davidbenjamin** [comment]
@droazen am I waiting for your approval?

**Comment by davidbenjamin** [comment]
@droazen waiting for your thumbs to be directed toward the stars.

**Comment by davidbenjamin** [comment]
@droazen Is it okay to merge this PR?

**Comment by droazen** [comment]
@davidbenjamin I'll have a look at this one later today.

**Comment by davidbenjamin** [comment]
Rebased -- should still pass tests.

**Comment by ldgauthier** [comment]
I think this is good to go, @droazen .

**Comment by davidbenjamin** [comment]
@lbergelson do you think you could approve this while David is away?

**Comment by lbergelson** [comment]
@davidbenjamin Sorry to get in your way, I see that this has been sitting forever.   I know that @jamesemery is working on this same code right now.  I'm going to pass this one to him so he can have a heads up about this change.

**Comment by lbergelson** [comment]
@jamesemery Could you take a look at this change.
