### PR TITLE
dont-use-soft-clips actually works in Mutect2

### LINKED ISSUE #6686: -dont-use-soft-clipped-bases doesn't work
Prior to assembly (in `AssemblyBasedCallerUtils.assembleReads`, we transform reads in several ways that are meant to be permanent (that is, we want to use them in both assembly and genotyping) within `finalizeRegion`.  (Additionally, we error reads within `ReadThreadingAssembler.runLocalAssembly`, but this is done on temporary copies of reads that are used for kmers and discarded).  These transformations include hard clipping low-quality ends, adaptor sequences, and, optionally, soft-clipped bases, as well as correcting the base qualities of overlapping mates.

According to the git history, these transformations have been accidentally temporary for quite a while.  Let's look at the relevant code.  First, in `Mutect2Engine.callRegion` we have (comments added and code simplified for clarity)

```
final AssemblyRegion assemblyActiveRegion = AssemblyBasedCallerUtils.assemblyRegionWithWellMappedReads(originalAssemblyRegion . . .);

// assembleReads finalizes region, modifying reads as a side effect
final AssemblyResultSet untrimmedAssemblyResult = AssemblyBasedCallerUtils.assembleReads(assemblyActiveRegion. . .);

final SortedSet<VariantContext> allVariationEvents = untrimmedAssemblyResult.getVariationEvents(MTAC.maxMnpDistance);

// when we trim on the originalAssemblyRegion, the trimmingResult takes its un-modified reads!
 final AssemblyRegionTrimmer.Result trimmingResult = trimmer.trim(originalAssemblyRegion, allVariationEvents, referenceContext);

// now the assemblyResult gets the unmodified reads of the trimmingResult!
final AssemblyResultSet assemblyResult = untrimmedAssemblyResult.trimTo(trimmingResult.getVariantRegion());
```

If we want things like `-dont-use-soft-clipped-bases` to work, we should call `trimmer.trim` on `untrimmedAssemblyResult`.  I think that change alone may be all we need.

Let's look at the corresponding code in `HaplotypeCallerEngine`:

```
final AssemblyResultSet untrimmedAssemblyResult =  AssemblyBasedCallerUtils.assembleReads(region. . .);

final SortedSet<VariantContext> allVariationEvents = untrimmedAssemblyResult.getVariationEvents(hcArgs.maxMnpDistance);

// same things as Mutect2 — we trim on the unmodified region
final AssemblyRegionTrimmer.Result trimmingResult = trimmer.trim(region, allVariationEvents, referenceContext);

// same as Mutect2
final AssemblyResultSet assemblyResult = untrimmedAssemblyResult.trimTo(trimmingResult.getVariantRegion());
```

In addition to the proposed simple fix, this brings up a few code smells:

* One would expect assembly not to modify its input reads, but it does through the side effect of `finalizeRegion`.
* Assembly has both the permanent changes of finalize region and the temporary changes of read error correction.
* `AssemblyResultSet` stores the reads but so does `AssemblyRegion`.

Without doing any serious refactoring, perhaps `finalizeRegion` could at least be split off from assembly so that the latter does not stealthily modify reads.

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #6686

@fleharty This option did nothing because a copy of the original reads was modified.  By deleting the unnecessary mapping quality filtering (this is totally redundant with the M2 read filter), we finalize (and thereby discard soft clips if requested) an assembly region made from the original reads, not a copy.

### CODE REVIEW

**Comment by droazen** [comment]
@davidbenjamin What's the state of this argument for the `HaplotypeCaller`?

**Comment by davidbenjamin** [comment]
@droazen It already works for HaplotypeCaller.

**Comment by davidbenjamin** [comment]
@fleharty Can we get this in for Friday's release?

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java [hunk 1]
```diff
@@ -373,6 +375,28 @@ public void testForceCalling() {
...
+        runMutect2(tumor, calls1, interval.toString(), b37Reference, Optional.of(GNOMAD));
+
+        final File calls2 = createTempFile("unfiltered", ".vcf");
+        runMutect2(tumor, calls2, interval.toString(), b37Reference, Optional.of(GNOMAD),
+                args -> args.addFlag(AssemblyBasedCallerArgumentCollection.DONT_USE_SOFT_CLIPPED_BASES_LONG_NAME));
+
+        final List<VariantContext> indelsWithSoftClips = VariantContextTestUtils.streamVcf(calls1).filter(VariantContext::isIndel).collect(Collectors.toList());
+        final List<VariantContext> indelsWithoutSoftClips = VariantContextTestUtils.streamVcf(calls2).filter(VariantContext::isIndel).collect(Collectors.toList());
+
+        Assert.assertTrue(indelsWithoutSoftClips.size() < indelsWithSoftClips.size());
```
Comment (fleharty) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java:397]: Can we be more specific about which variants are called/not called when the option is set/unset?
I'd hate for this to pass by chance, which is almost has a 50/50 chance of, even if it's not doing what we expect.

**Review by fleharty — CHANGES_REQUESTED** [review]
@davidbenjamin Looks almost ready, but could we be a bit stricter on the test?

**Comment by fleharty** [comment]
@davidbenjamin back to you

**Comment by fleharty** [comment]
@davidbenjamin Do you have a moment to push this along?

**Comment by davidbenjamin** [comment]
I will try to finish this today.

**Comment by davidbenjamin** [comment]
@fleharty back to you

**Review by fleharty — APPROVED** [review]
Looks good!  Merge away!
