### PR TITLE
HaplotypeCaller: omnibus updates and fixes for 4.0

### LINKED ISSUE #1950: Port GATK3 PR https://github.com/broadinstitute/gsa-unstable/pull/1389 "Changes to use the median rather than the second best likelihood for the NON_REF allele"
Create a PR in gatk to port the change once it has been merged into GATK3.
https://github.com/broadinstitute/gsa-unstable/pull/1389

### LINKED ISSUE #2848: HaplotypeCaller missing GVCF block for interval with no coverage
@akiezun commented on [Wed Apr 27 2016](https://github.com/broadinstitute/gatk-protected/issues/463)

using commit 39c988c2dc7f669306d246a2191d16af50496640

(using our test resources)

```
./gatk-launch HaplotypeCaller -I ~/IdeaProjects/gatk/src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -L 20:1-11000000 -R ~/IdeaProjects/gatk/src/test/resources/large/human_g1k_v37.20.21.fasta  -O testa.g.vcf -ERC GVCF --bamOutput testa.outHC.bam
```

compare to gatk3.4.46

```
java -jar /Users/akiezun/projects/GATK3.4-46/GenomeAnalysisTK.jar -T HaplotypeCaller -I ~/IdeaProjects/gatk/src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -L 20:1-11000000 -R ~/IdeaProjects/gatk/src/test/resources/large/human_g1k_v37.20.21.fasta -ERC GVCF --bamOutput testa.gatk3.outHC.bam --out testa.gatk3.g.vcf
```

see the first line in the output:

```
20      1       .       N       <NON_REF>       .       .       END=9999901     GT:DP:GQ:MIN_DP:PL      0/0:0:0:0:0,0,0
```

it's missing from GATK4 output

---

@droazen commented on [Wed Apr 27 2016](https://github.com/broadinstitute/gatk-protected/issues/463#issuecomment-215182886)

This is probably because there is no coverage at all in the interval 1-9999901

---

@akiezun commented on [Wed Apr 27 2016](https://github.com/broadinstitute/gatk-protected/issues/463#issuecomment-215183626)

why is it different and is it OK?

---

@droazen commented on [Wed Apr 27 2016](https://github.com/broadinstitute/gatk-protected/issues/463#issuecomment-215184942)

I'll need to have a look at `GenotypeGVCFs` to determine whether it's ok, but certainly we are not losing any information by leaving out this block (since it's backed by zero reads).

### LINKED ISSUE #3233: Hand HaplotypeCaller snapshot with first-pass validation issues addressed off to palantir for second-pass validation

### LINKED ISSUE #3516: AssemblyRegion traversal loads too many reads at once
It loads all reads for each shard at a time, but it could be lazier and load only 1-2 assembly regions' worth of reads.

### LINKED ISSUE #3517: Add a mode to AssemblyRegion traversal that creates one shard per user interval

### LINKED ISSUE #3518: AssemblyRegion traversal needs to serve up empty pileup objects to the activity profile for uncovered loci
To mimic GATK 3.x behavior

### PR DESCRIPTION
**Pull request by droazen**
-Reduce memory usage of AssemblyRegion traversal by an order of magnitude
 by loading the reads for each shard more lazily.

-Add a sharding mode that creates one shard per user interval (or per contig,
 if there are no explicit intervals), and make it the default for both HaplotypeCaller
 and Mutect2

-When determining active regions, only consider loci within the user's intervals (but
 still include surrounding reads in the final region). This mimics GATK3.x behavior.

-Serve up empty pileup objects for uncovered loci (this also mimics GATK3.x behavior).
 The fact that we weren't doing this before was responsible for much of the remaining
 difference vs. the GATK 3.x HaplotypeCaller.

-Ported GATK 3 PR 1389 (use median rather than the second-best likelihood for the
 NON_REF allele)

-Ported a change to the ReferenceConfidenceModel from GATK3

-Fixed a bug in ReadLikelihoods that was causing ArrayIndexOutOfBoundsException

-Added special handling of RawMQ to HaplotypeCaller (mirrors the handling of RawMQ
 from GenotypeGVCFs)

-Added updated concordance test data generated with HaplotypeCaller 3.8-4-g7b0250253f

Resolves #1950
Resolves #3516
Resolves #3517
Resolves #3518
Resolves #3233
Resolves #2848

### CODE REVIEW

**Comment by droazen** [comment]
@jamesemery please review

File: src/test/java/org/broadinstitute/hellbender/utils/iterators/AllLocusIteratorUnitTest.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+import java.util.Arrays;
+import java.util.Iterator;
+import java.util.List;
+
+import static org.mockito.Mockito.*;
+
+public class AllLocusIteratorUnitTest extends BaseTest {
+
+    @Test
+    public void testIteratorReturnsPileupsForAllLoci() {
```
Comment (jamesemery) [inline src/test/java/org/broadinstitute/hellbender/utils/iterators/AllLocusIteratorUnitTest.java]: Add tests for intervals that lie before and after the interval

Comment (jamesemery) [reply src/test/java/org/broadinstitute/hellbender/utils/iterators/AllLocusIteratorUnitTest.java]: Also tests for the sanity checks in the constructor (like having the wrong contig)

File: src/test/java/org/broadinstitute/hellbender/utils/iterators/AllLocusIteratorUnitTest.java [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+                        when(mock(ReadPileup.class).size()).thenReturn(10).getMock()));
+        final List<Integer> providedLoci = Arrays.asList(5, 15, 19, 22);
+
+        final Iterator<AlignmentContext> locusIterator = new AllLocusIterator(providedInterval, providedPileups.iterator());
+
+        final List<AlignmentContext> returnedPileups = new ArrayList<>();
+        locusIterator.forEachRemaining(pileup -> returnedPileups.add(pileup));
+
+        Assert.assertEquals(returnedPileups.size(), providedInterval.size(), "Wrong number of pileup objects returned");
+
```
Comment (jamesemery) [inline src/test/java/org/broadinstitute/hellbender/utils/iterators/AllLocusIteratorUnitTest.java]: Add an assertion here that specifies that this is inclusive of the staring position for the provided interval

File: src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java [hunk 3]
```diff
@@ -0,0 +1,226 @@
...
+    private AssemblyRegion loadNextAssemblyRegion() {
+        AssemblyRegion nextRegion = null;
+
+        while ( locusIterator.hasNext() && nextRegion == null ) {
+            final AlignmentContext pileup = locusIterator.next();
+
+            // Ignore sites that are not contained within this shard's interval
+            if ( ! readShard.getInterval().contains(pileup) ) {
+                continue;
+            }
```
Comment (jamesemery) [inline src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java]: Theoretically unnecessary because the AllLocusIterator already asserts this.

File: src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java [hunk 4]
```diff
@@ -0,0 +1,226 @@
...
+            // until we've traversed all the reads that belong in them.
+            //
+            // Ordering matters here: need to check for forceConversion before adding current pileup to the activity profile
+            if ( ! activityProfile.isEmpty() ) {
+                final boolean forceConversion = pileup.getLocation().getStart() != activityProfile.getEnd() + 1;
+                pendingRegions.addAll(activityProfile.popReadyAssemblyRegions(assemblyRegionPadding, minRegionSize, maxRegionSize, forceConversion));
+            }
+
+            // Add the current pileup to the activity profile
+            if ( readShard.getPaddedInterval().contains(pileup.getLocation()) ) {
```
Comment (jamesemery) [inline src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java]: Second layer of redundancy which has already been asserted above on line 137

File: src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java [hunk 5]
```diff
@@ -0,0 +1,226 @@
...
+
+        // When we run out of loci, close out the activity profile, and close out any remaining pending regions one at a time
+        if ( ! locusIterator.hasNext() ) {
+            if ( ! activityProfile.isEmpty() ) {
+                // Pop the activity profile a final time with forceConversion == true
+                pendingRegions.addAll(activityProfile.popReadyAssemblyRegions(assemblyRegionPadding, minRegionSize, maxRegionSize, true));
+            }
+
+            if ( ! pendingRegions.isEmpty() ) {
+                nextRegion = pendingRegions.poll();
```
Comment (jamesemery) [inline src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java]: Could overwrite the nextRegion if it was specified by the first loop.

File: src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java [hunk 6]
```diff
@@ -0,0 +1,226 @@
...
+            fillNextAssemblyRegionWithReads(nextRegion);
+        }
+
+        return nextRegion;
+    }
+
+    private void fillNextAssemblyRegionWithReads( final AssemblyRegion region ) {
+        // First we need to check the previous region for reads that also belong in this region
+        if ( previousRegion != null ) {
+            for ( final GATKRead previousRegionRead : previousRegion.getReads() ) {
```
Comment (jamesemery) [inline src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java]: Are you entirely sure that previousRegion.getReads() is safe in this case? Is it possible that the reads might have been removed or filtered before the next region reaches into it?

File: src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java [hunk 7]
```diff
@@ -0,0 +1,226 @@
...
+
+import java.util.*;
+
+/**
+ * Given a {@link Shard} of {@link GATKRead}, iterates over each {@link AssemblyRegion} within that shard, using the
+ * provided {@link AssemblyRegionEvaluator} to determine the boundaries between assembly regions.
+ *
+ * Loads the reads from the shard as lazily as possible to minimize memory usage.
+ *
+ * This iterator represents the core of the {@link AssemblyRegionWalker} traversal.
```
Comment (jamesemery) [inline src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java]: Perhaps add to the contract of this method a warning about the needed unmapped reads filters to have been applied to the shard.

File: src/test/java/org/broadinstitute/hellbender/engine/AssemblyRegionIteratorUnitTest.java [hunk 8]
```diff
@@ -0,0 +1,115 @@
...
+
+            final AssemblyRegionIterator iter = new AssemblyRegionIterator(readShard, readsSource.getHeader(), refSource, null, evaluator, minRegionSize, maxRegionSize, assemblyRegionPadding, 0.002, 50);
+
+            AssemblyRegion previousRegion = null;
+            while ( iter.hasNext() ) {
+                final AssemblyRegion region = iter.next();
+
+                Assert.assertTrue(region.getSpan().size() <= maxRegionSize, "region size " + region.getSpan().size() + " exceeds the configured maximum: " + maxRegionSize);
+
+                final int regionContigLength = readsDictionary.getSequence(region.getSpan().getContig()).getSequenceLength();
```
Comment (jamesemery) [inline src/test/java/org/broadinstitute/hellbender/engine/AssemblyRegionIteratorUnitTest.java]: Do you ever assert that there are no gaps between regions? I see that you assert their ordering and their overhangs, but what if they overlap/have gaps.

File: src/main/java/org/broadinstitute/hellbender/utils/iterators/ReadCachingIterator.java [hunk 9]
```diff
@@ -0,0 +1,57 @@
...
+
+import java.util.ArrayList;
+import java.util.Iterator;
+import java.util.List;
+import java.util.NoSuchElementException;
+
+/**
+ * Trivial wrapper around a GATKRead iterator that saves all reads returned in a cache,
+ * which can be periodically returned and emptied by the client.
+ */
```
[the remark this answers is not in the document]
Comment (droazen) [reply src/main/java/org/broadinstitute/hellbender/utils/iterators/ReadCachingIterator.java]: Done

File: src/test/java/org/broadinstitute/hellbender/utils/iterators/AllLocusIteratorUnitTest.java (hunk 1 above)
Comment (droazen) [reply src/test/java/org/broadinstitute/hellbender/utils/iterators/AllLocusIteratorUnitTest.java]: Done!

File: src/test/java/org/broadinstitute/hellbender/utils/iterators/AllLocusIteratorUnitTest.java (hunk 2 above)
Comment (droazen) [reply src/test/java/org/broadinstitute/hellbender/utils/iterators/AllLocusIteratorUnitTest.java]: Done

File: src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java (hunk 7 above)
Comment (droazen) [reply src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java]: Done

File: src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java (hunk 3 above)
Comment (droazen) [reply src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java]: True, but it doesn't hurt.

File: src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java (hunk 4 above)
Comment (droazen) [reply src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java]: Removed

File: src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java (hunk 5 above)
Comment (droazen) [reply src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java]: Added in a guard

File: src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java (hunk 6 above)
Comment (droazen) [reply src/main/java/org/broadinstitute/hellbender/engine/AssemblyRegionIterator.java]: You're right, it might not be safe. Switching to storing the previous region's reads directly instead.

File: src/test/java/org/broadinstitute/hellbender/engine/AssemblyRegionIteratorUnitTest.java (hunk 8 above)
Comment (droazen) [reply src/test/java/org/broadinstitute/hellbender/engine/AssemblyRegionIteratorUnitTest.java]: Added

**Comment by droazen** [comment]
All comments addressed -- will merge after tests pass.
