### PR TITLE
Making ENSEMBL GTF Codec more permissive

### LINKED ISSUE #6488: ENSEMBL GTF files have variable formats which Funcotator does not expect
Some of the GTF files from ENSEMBL do not follow the format that the current `EnsemblGtfCodec` expects.  This will cause Funcotator to fail on those files.

A complete description (courtesy of ENSEMBL themselves) of their GTF format is as follows (and it differs from what is expected in the code):

```
#### README ####

--------
GTF DUMP
--------

This directory includes a summary of the gene annotation information 
and GTF format.

Ensembl provides an automatic gene annotation for Aedes aegypti.
For some species ( human, mouse, zebrafish, pig and rat), the
annotation provided through Ensembl also includes manual annotation
from HAVANA.
In the case of human and mouse, the GTF files found here are equivalent
to the GENCODE gene set.

GTF provides access to all annotated transcripts which make
up an Ensembl gene set. Annotation is based on alignments of
biological evidence (eg. proteins, cDNAs, RNA-seq) to a genome assembly.
The annotation dumped here is transcribed and translated from the 
genome assembly and is not the original input sequence data that 
we used for alignment. Therefore, the sequences provided by Ensembl 
may differ from the original input sequence data where the genome 
assembly is different to the aligned sequence. 

Additionally, we provide a GTF file containing the predicted gene set
as generated by Genscan and other abinitio prediction tools.
This file is identified by the abinitio extension.


-----------
FILE NAMES
------------
The files are consistently named following this pattern:
   <species>.<assembly>.<version>.gtf.gz

<species>:       The systematic name of the species.
<assembly>:      The assembly build name.
<version>:       The version of Ensembl from which the data was exported.
gtf : All files in these directories are in GTF format
gz : All files are compacted with GNU Zip for storage efficiency.

e.g.
Homo_sapiens.GRCh38.81.gtf.gz

For the predicted gene set, an additional abinitio flag is added to the name file.
<species>.<assembly>.<version>.abinitio.gtf.gz

e.g.
Homo_sapiens.GRCh38.81.abinitio.gtf.gz

--------------------------------
Definition and supported options
--------------------------------

The GTF (General Transfer Format) is an extension of GFF version 2 
and used to represent transcription models. GFF (General Feature Format) 
consists of one line per feature, each containing 9 columns of data. 

Fields

Fields are tab-separated. Also, all but the final field in each 
feature line must contain a value; "empty" columns are denoted 
with a '.'

    seqname   - name of the chromosome or scaffold; chromosome names 
                without a 'chr' 
    source    - name of the program that generated this feature, or 
                the data source (database or project name)
    feature   - feature type name. Current allowed features are
                {gene, transcript, exon, CDS, Selenocysteine, start_codon,
                stop_codon and UTR}
    start     - start position of the feature, with sequence numbering 
                starting at 1.
    end       - end position of the feature, with sequence numbering 
                starting at 1.
    score     - a floating point value indiciating the score of a feature
    strand    - defined as + (forward) or - (reverse).
    frame     - one of '0', '1' or '2'. Frame indicates the number of base pairs
                before you encounter a full codon. '0' indicates the feature 
                begins with a whole codon. '1' indicates there is an extra
                base (the 3rd base of the prior codon) at the start of this feature.
                '2' indicates there are two extra bases (2nd and 3rd base of the 
                prior exon) before the first codon. All values are given with
                relation to the 5' end.
    attribute - a semicolon-separated list of tag-value pairs (separated by a space), 
                providing additional information about each feature. A key can be
                repeated multiple times.

Attributes

The following attributes are available. All attributes are semi-colon
separated pairs of keys and values.

- gene_id: The stable identifier for the gene
- gene_version: The stable identifier version for the gene
- gene_name: The official symbol of this gene
- gene_source: The annotation source for this gene
- gene_biotype: The biotype of this gene
- transcript_id: The stable identifier for this transcript
- transcript_version: The stable identifier version for this transcript
- transcript_name: The symbold for this transcript derived from the gene name
- transcript_source: The annotation source for this transcript
- transcript_biotype: The biotype for this transcript
- exon_id: The stable identifier for this exon
- exon_version: The stable identifier version for this exon
- exon_number: Position of this exon in the transcript
- ccds_id: CCDS identifier linked to this transcript
- protein_id: Stable identifier for this transcript's protein
- protein_version: Stable identifier version for this transcript's protein
- tag: A collection of additional key value tags
- transcript_support_level: Ranking to assess how well a transcript is supported (from 1 to 5)

Tags

Tags are additional flags used to indicate attibutes of the transcript.

- CCDS: Flags this transcript as one linked to a CCDS record
- seleno: Flags this transcript has a Selenocysteine edit. Look for the Selenocysteine
feature for the position of this on the genome
- cds_end_NF: the coding region end could not be confirmed
- cds_start_NF: the coding region start could not be confirmed
- mRNA_end_NF: the mRNA end could not be confirmed
- mRNA_start_NF: the mRNA start could not be confirmed.
- basic: the transcript is part of the gencode basic geneset

Comments

Lines may be commented out by the addition of a single # character at the start. These
lines should be ignored by your parser.

Pragmas/Metadata

GTF files can contain meta-data. In the case of experimental meta-data these are 
noted by a #!. Those which are stable are noted by a ##. Meta data is a single key,
a space and then the value. Current meta data keys are:

* genome-build -  Build identifier of the assembly e.g. GRCh37.p11
* genome-version - Version of this assembly e.g. GRCh37
* genome-date - The date of this assembly's release e.g. 2009-02
* genome-build-accession - The accession and source of this accession e.g. NCBI:GCA_000001405.14
* genebuild-last-updated - The date of the last genebuild update e.g. 2013-09

------------------
Example GTF output
------------------

#!genome-build GRCh38
11      ensembl_havana  gene    5422111 5423206 .       +       .       gene_id "ENSG00000167360"; gene_version "4"; gene_name "OR51Q1"; gene_source "ensembl_havana"; gene_biotype "protein_coding";
11      ensembl_havana  transcript      5422111 5423206 .       +       .       gene_id "ENSG00000167360"; gene_version "4"; transcript_id "ENST00000300778"; transcript_version "4"; gene_name "OR51Q1"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "OR51Q1-001"; transcript_source "ensembl_havana"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS31381";
11      ensembl_havana  exon    5422111 5423206 .       +       .       gene_id "ENSG00000167360"; gene_version "4"; transcript_id "ENST00000300778"; transcript_version "4"; exon_number "1"; gene_name "OR51Q1"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "OR51Q1-001"; transcript_source "ensembl_havana"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS31381"; exon_id "ENSE00001276439"; exon_version "4";
11      ensembl_havana  CDS     5422201 5423151 .       +       0       gene_id "ENSG00000167360"; gene_version "4"; transcript_id "ENST00000300778"; transcript_version "4"; exon_number "1"; gene_name "OR51Q1"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "OR51Q1-001"; transcript_source "ensembl_havana"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS31381"; protein_id "ENSP00000300778"; protein_version "4";
11      ensembl_havana  start_codon     5422201 5422203 .       +       0       gene_id "ENSG00000167360"; gene_version "4"; transcript_id "ENST00000300778"; transcript_version "4"; exon_number "1"; gene_name "OR51Q1"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "OR51Q1-001"; transcript_source "ensembl_havana"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS31381";
11      ensembl_havana  stop_codon      5423152 5423154 .       +       0       gene_id "ENSG00000167360"; gene_version "4"; transcript_id "ENST00000300778"; transcript_version "4"; exon_number "1"; gene_name "OR51Q1"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "OR51Q1-001"; transcript_source "ensembl_havana"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS31381";
11      ensembl_havana  UTR     5422111 5422200 .       +       .       gene_id "ENSG00000167360"; gene_version "4"; transcript_id "ENST00000300778"; transcript_version "4"; gene_name "OR51Q1"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "OR51Q1-001"; transcript_source "ensembl_havana"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS31381";
11      ensembl_havana  UTR     5423155 5423206 .       +       .       gene_id "ENSG00000167360"; gene_version "4"; transcript_id "ENST00000300778"; transcript_version "4"; gene_name "OR51Q1"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "OR51Q1-001"; transcript_source "ensembl_havana"; transcript_biotype "protein_coding"; tag "CCDS"; ccds_id "CCDS31381";
```

### PR DESCRIPTION
**Pull request by jonn-smith**
This will allow the ENSEMBL GTF codec to decode any ENSEMBL GTF file that they host.

Fixes #6488

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/AbstractGtfCodec.java [hunk 1]
```diff
@@ -474,26 +474,53 @@ boolean checkHeaderLineStartsWith(final List<String> header, final int lineNum,
...
      * @param header A {@link List<String>} containing a header to validate.
      * @param lineNum Line number in the header to check.
      * @param startingText {@link String} containing text that the line should start with
      * @param throwIfInvalid If {@code true} will throw a {@link UserException} instead of returning false.
      * @return {@code true} IFF the header line number {@code lineNum} starts with {@code startingText}; {@code false} otherwise.
      */
     boolean checkHeaderLineStartsWith(final List<String> header, final int lineNum, final String startingText, final boolean throwIfInvalid ) {
-        if ( !header.get(lineNum).startsWith(getLineComment() + startingText) ) {
+        boolean foundGoodLine = false;
+        for ( final String commentPrefix : getAllLineComments() ) {
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/AbstractGtfCodec.java]: Seems like some duplicated code with isLineCommented but maybe complexity of sharing it makes it not worthwhile to refactor.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java [hunk 2]
```diff
@@ -29,12 +28,16 @@
...
     //==================================================================================================================
     // Private Members:
 
-    private final List<String> header         = new ArrayList<>();
-    private       int          currentLineNum = 1;
-    private       String       version        = "";
+    private final        List<String> header          = new ArrayList<>();
+    private              int          currentLineNum  = 1;
+    private              String       version         = null;
+    private static final Set<String>  commentPrefixes = Collections.unmodifiableSet(new LinkedHashSet<>(Arrays.asList("#!", "##")));
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java]: COMMENT_PREFIXES and group it with the other statics

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java [hunk 3]
```diff
@@ -120,7 +121,28 @@ void incrementLineNumber() {
...
     String getUcscVersionNumber() {
-        return getVersionFromHeader();
+        return version;
+    }
+
+    @Override
+    /**
+     * {@inheritDoc}
+     *
+     * Because ENSEMBL GTF files are strictly a superset of GENCODE GTF files, we need to do some extra checks here to
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java]: Oh, I didn't realize that.  Does that imply that the ensemble codec should extend GencodecodeGtfCodec instead of being a parallel class to it?  Maybe something to think about in the future.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java [hunk 4]
```diff
@@ -162,23 +203,27 @@ static boolean validateEnsemblGtfFeature(final GencodeGtfFeature feature) {
...
-        if ( header.size() != HEADER_NUM_LINES) {
-            if ( throwIfInvalid ) {
-                throw new UserException.MalformedFile(
-                        "ENSEMBL GTF Header is of unexpected length: " +
-                                header.size() + " != " + HEADER_NUM_LINES);
-            }
-            else {
-                return false;
+        // As it turns out, the ENSEMBL GTF header is pretty loosy-goosy.
+        // No fields are required, and therefore it could actually be empty.
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java]: disgusting

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java [hunk 5]
```diff
@@ -162,23 +203,27 @@ static boolean validateEnsemblGtfFeature(final GencodeGtfFeature feature) {
...
+
+        // Rather than attempting to validate the file, here we just
+        // assert that all header lines begin with a comment (they should already).
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java]: Are there fields that YOU require even if ENSEMBLE doesn't?  It might be a good idea to warn if things like the version are missing.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/GencodeGtfFeature.java [hunk 6]
```diff
@@ -44,6 +44,15 @@
 
     private static final Logger logger = LogManager.getLogger(GencodeGtfFeature.class);
 
+    // ===========================================================================
+
+
+    public static final String ANNOTATION_SOURCE_ENSEMBL = "ENSEMBL";
+    public static final String ANNOTATION_SOURCE_HAVANA = "HAVANA";
+    public static String ANNOTATION_SOURCE_ENA = "ena";
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/GencodeGtfFeature.java]: static

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/AbstractGtfCodec.java (hunk 1 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/AbstractGtfCodec.java]: Yeah - I was thinking about this as I was implementing it.  I can refactor it.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java (hunk 2 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java]: rgr.  Fixed!

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java (hunk 3 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java]: Yeah - I didn't realize it until doing the work for this issue.

It's probably worth looking into doing that - it would be nice to have a single point of control for this.  I also need to change the name of some other classes in response to having multiple kinds of GTF files, but I wanted to leave that out of this PR for simplicity.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java (hunk 4 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java]: Yeah - according to the spec, you can get the version from the file names.

I plan on implementing this after the `NameAwareCodec` PR goes in.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java (hunk 5 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java]: I would love to make it more restrictive, but I don't want to require users to modify the files after downloading them.  If we end up writing a downloader tool that could create these metadata entries.

I'm not sure adding in warnings will be productive - users should never be creating these files, they should just be downloading them directly from ENSEMBL.  So it's really an ENSEMBL issue.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/GencodeGtfFeature.java (hunk 6 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/GencodeGtfFeature.java]: `final`?

:P

Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/GencodeGtfFeature.java]: Fixed.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java (hunk 3 above)
Comment (lbergelson) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java]: I agree, that's a different pr.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java (hunk 5 above)
Comment (lbergelson) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/EnsemblGtfCodec.java]: That seems reasonable.

File: src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/AbstractGtfCodec.java [hunk 7]
```diff
@@ -521,6 +515,25 @@ boolean isLineCommented(final String line) {
         return isCommented;
     }
 
+    /**
+     * Checks whether the given line is commented out or not and if the content of the line begins with the given
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/AbstractGtfCodec.java]: shouldn't the other other implementation make use of this one now?

Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/AbstractGtfCodec.java]: Oops.  Yes it should!

Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/utils/codecs/gtf/AbstractGtfCodec.java]: Fixed.

**Comment by lbergelson** [comment]
@jonn-smith Looks good, merge when tests pass.

**Comment by jonn-smith** [comment]
No worries!  Thanks for merging it in!
