### PR TITLE
fix 3874 by using the correct predicate

### LINKED ISSUE #3874: SV pipeline tries to create illegal interval
running wgs1 with current code in master, we get the following stack trace:

Caused by: java.lang.IllegalArgumentException: Invalid interval. Contig:chrUn_JTFH01001938v1_decoy start:0 end:0
	at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:686)
	at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:60)
	at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:36)
	at org.broadinstitute.hellbender.tools.spark.sv.discovery.NovelAdjacencyReferenceLocations$BreakpointsInference.getLeftJustifiedBreakpoints(NovelAdjacencyReferenceLocations.java:78)
	at org.broadinstitute.hellbender.tools.spark.sv.discovery.NovelAdjacencyReferenceLocations.leftJustifyBreakpoints(NovelAdjacencyReferenceLocations.java:293)
	at org.broadinstitute.hellbender.tools.spark.sv.discovery.NovelAdjacencyReferenceLocations.<init>(NovelAdjacencyReferenceLocations.java:42)
	at org.broadinstitute.hellbender.tools.spark.sv.discovery.DiscoverVariantsFromContigAlignmentsSAMSpark.lambda$discoverNovelAdjacencyFromChimericAlignments$7(DiscoverVariantsFromContigAlignmentsSAMSpark.java:409)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:147)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by SHuang-Broad**
This fixes #3874 .

The detail is explained in the ticket and the self-review comments in code change below.

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakpointComplications.java [hunk 1]
```diff
@@ -176,12 +176,12 @@ boolean hasDupSeqButNoStrandSwitch() {
...
 
         // if-else testing order matters here:
-        // if the two segments in the input chimeric alignment suggests simple translocation {@see ChimericAlignment#isNotSimpleTranslocation()}, then
+        // if the two segments in the input chimeric alignment suggests simple translocation {@see ChimericAlignment#isLikelySimpleTranslocation()}, then
         //  we need other types of evidence to fully resolve type of event, until then we can only say a novel adjacency (BND) is detected;
         // if the two segments in the input chimeric alignment map to the same chromosome, then
         //  the segment with lower coordinate on the locally-assembled contig could map to a higher reference coordinate region
         //  under two basic types of SV's: inversion (strand switch necessary) and "translocation" (no strand switch necessary)
-        final boolean suggestsSimpleTranslocation = !chimericAlignment.isNotSimpleTranslocation();
+        final boolean suggestsSimpleTranslocation = chimericAlignment.isLikelySimpleTranslocation();
```
Comment (SHuang-Broad) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/BreakpointComplications.java]: logically, isNotSimpleTranslocation is not the same as the negation of isLikelySimpleTranslocation, so we are using the wrong criterion here to resolve complications.

File: src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignment.java [hunk 2]
```diff
@@ -319,8 +319,66 @@ public static boolean isLikelySimpleTranslocation(final AlignmentInterval region
...
+     *     <li>
+     *         todo: this obsoletes the actual use of {@link #isLikelyInvertedDuplication()} and related inverted duplication call code we have now, but those could be used to figure out how to annotate which known ref regions are invert duplicated
+     *         first and second alignment involve strand switch, but their reference span overlap;
+     *     </li>
+     *     <li>
+     *         first and second alignment have reference order switch but their reference span overlaps;
+     *     </li>
+     * </ul>
+     */
+    public static boolean hasIncompletePictureFromTwoAlignments(final AlignmentInterval one, final AlignmentInterval two) {
```
Comment (SHuang-Broad) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignment.java]: refactored from prototyping class `AssemblyContigWithFineTunedAlignments`

File: src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignment.java [hunk 3]
```diff
@@ -175,7 +175,7 @@ public ChimericAlignment(final AlignmentInterval intervalWithLowerCoordOnContig,
             final ChimericAlignment chimericAlignment = new ChimericAlignment(current, next, insertionMappings,
                     alignedContig.contigName, referenceDictionary);
             // the following check/filter is due to the fact that simple translocations are to be handled in a different code path
-            if (chimericAlignment.isNotSimpleTranslocation())
+            if (chimericAlignment.isNeitherSimpleTranslocationNorIncompletePicture())
```
Comment (SHuang-Broad) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignment.java]: using correct filtering predicate now, not being simple translocation could mean not having a complete picture (see logic below). This is the reason the 1st line of defense is not working.

File: src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignmentUnitTest.java [hunk 4]
```diff
@@ -175,32 +175,36 @@ public void testFilterByNextAlignmentMayBeInsertion() {
...
-        data.add(new Object[]{intervalOne, intervalTwo, StrandSwitch.NO_SWITCH, true, true, false, true});
+        data.add(new Object[]{intervalOne, intervalTwo, StrandSwitch.NO_SWITCH, true, true, false, false, true});
 
         // diff-chr translocation suspect with SS
         intervalOne = new AlignmentInterval(new SimpleInterval("chr21", 5374092, 5374748), 1, 656, TextCigarCodec.decode("656M322S"), true, 60, 14, 586, AlnModType.NONE);
         intervalTwo = new AlignmentInterval(new SimpleInterval("chr20", 28764673, 28765145), 506, 978, TextCigarCodec.decode("473M505H"), false, 60, 16, 393, AlnModType.NONE);
-        data.add(new Object[]{intervalOne, intervalTwo, StrandSwitch.FORWARD_TO_REVERSE, false, true, false, true});
+        data.add(new Object[]{intervalOne, intervalTwo, StrandSwitch.FORWARD_TO_REVERSE, false, true, false, false, true});
 
+        // same-chr reference order switch, but overlaps (hence incomplete picture)
```
Comment (SHuang-Broad) [inline src/test/java/org/broadinstitute/hellbender/tools/spark/sv/discovery/ChimericAlignmentUnitTest.java]: test case thanks to @cwhelan and @tedsharpe  from ticket #3874

**Comment by tedsharpe** [comment]
I'm merging on Steve's behalf, since he's on the other side of the earth.
