### PR TITLE
fixed error in RealignmentEngine due to inclusive vs exclusive ends

### LINKED ISSUE #6344: FilterAlignmentArtifacts Invalid Intervals and Segmentation Faults
### Affected tool(s) or class(es)
_FilterAlignmentArtifacts_

### Affected version(s)
- [x] Latest public release version [4.1.4.1]

### Description 
FilterAlignmentArtifacts consistently errors out with segmentation faults or IllegalArgumentExceptions. I've attached the log files for each of these errors below.
[invalid_interval.log](https://github.com/broadinstitute/gatk/files/4017907/invalid_interval.log)
[seg_fault.log](https://github.com/broadinstitute/gatk/files/4017908/seg_fault.log)

#### Steps to reproduce
The command to reproduce both errors is the same, and I have attached it below.
[realignment_filter.txt](https://github.com/broadinstitute/gatk/files/4017918/realignment_filter.txt)
The BWA mem index I'm using is hg38, however the BAM that I am realigning from is hg19; thus, the reference argument is the hg19 fasta. I am happy to transfer zip files containing the other files need to reproduce this. Just let me know where to send them.

#### Expected behavior
_FilterAlignmentArtifacts_

#### Actual behavior
_Errors_

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #6344, I think.  @takutosato can you review this?

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java [hunk 1]
```diff
@@ -132,8 +132,9 @@ private final static boolean mightSupportInsertion(final CigarElement cigarEleme
         return new ArrayList<>(commonAlignments);
     }
 
+    // note the conversion from exclusive end (BWAMemAlignment) to inclusive end (SimpleInterval)
     private static SimpleInterval convertToInterval(final BwaMemAlignment alignment) {
-        return new SimpleInterval(Integer.toString(alignment.getRefId()), alignment.getRefStart(), alignment.getRefEnd());
+        return new SimpleInterval(Integer.toString(alignment.getRefId()), alignment.getRefStart(), alignment.getRefEnd() - 1);
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java]: I think we need to go the other way don't we?  Increase the start and leave the end alone?

Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java]: Suppose the last included position is 5.

1) Account for exclusive --> inclusive stop.
BWA mem alignment is exclusive, hence its end is 6.  SimpleInterval is inclusive, so its end should be 5, which is BWA's end - 1.

2) account for 0-based --> 1-based contig
Add 1 to everything, so that adding 1 to the end cancels subtracting 1, while the start is incremented by 1.

@lbergelson You're right.  Thank you!

Comment (takutosato) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java]: Sounds good to me!

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java [hunk 2]
```diff
@@ -132,8 +132,11 @@ private final static boolean mightSupportInsertion(final CigarElement cigarEleme
         return new ArrayList<>(commonAlignments);
     }
 
+    // note the conversion from exclusive end (BWAMemAlignment) to inclusive end (SimpleInterval) (subtract 1 from the end)
+    // combined with the conversion from 0-based to 1-based contigs (add 1 to start and end)
+    // which has the net result of adding 1 to the start and leaving the end alone
     private static SimpleInterval convertToInterval(final BwaMemAlignment alignment) {
-        return new SimpleInterval(Integer.toString(alignment.getRefId()), alignment.getRefStart(), alignment.getRefEnd());
+        return new SimpleInterval(Integer.toString(alignment.getRefId()), alignment.getRefStart() + 1, alignment.getRefEnd());
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java]: @davidbenjamin Are we sure that the contig is correct?  I think alignment.getRefId() is likely to be 0 indexed, which means that you'll start with contig 0 when you want contig 1.  And obviously it doesn't work for non-numbered contigs.  I think what you need to be doing here is looking it up from bwaMemIndex.getReferenceContigNames().

Comment (lbergelson) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/realignmentfilter/RealignmentEngine.java]: Oh.  I see, it's using the same method to generate the overlap detectors, so that's ok.
