### PR TITLE
Updated install_R_packages.R to fix broken ggplot2 dependency in gatkbase Docker image.

### LINKED ISSUE #5022: Restore reshape R dependency and add test.
See https://gatkforums.broadinstitute.org/gatk/discussion/12078/gatk-4-4-docker-image-missing-dependancies

Looks like I inadvertently removed this in the great purge of #3935.  We should add a test to AnalyzeCovariates to cover plotting as well.

### PR DESCRIPTION
**Pull request by samuelklee**
The ggplot2 R dependency was not installed correctly in the gatkbase-2.0.0 Docker image.  It appears that this resulted from a recent ggplot2 update that has broken dependencies (perhaps for the version of R that we use).  This missing ggplot2 dependency was the root cause of #5022.

I updated the install_R_packages.R script, which should now fail if any package fails to install, and pushed an updated gatkbase-2.0.1 image.  The second commit addresses #5022.

This should be considered a temporary fix until #5026 is in.

Closes #5022.

### CODE REVIEW

**Comment by samuelklee** [comment]
@cmnbroad Just saw your email about releasing---I think this definitely needs to go in before then.  Can you review?

File: scripts/docker/gatkbase/install_R_packages.R [hunk 1]
```diff
@@ -6,34 +6,27 @@
...
+
+InstallPackageFromArchive = function(packageName, packageURL) {
+    # make sure to use http not https as this will give an "unsupported URL scheme" error
+    if (!(packageName %in% rownames(installed.packages()))) {
+        install.packages(packageURL, repos = NULL, type = "source", clean = TRUE)
+    }
 }
 
+dependencies = c("gplots",
+                 "digest", "gtable", "MASS", "plyr", "reshape2", "scales", "tibble", "lazyeval")    # ggplot2
```
Comment (samuelklee) [inline scripts/docker/gatkbase/install_R_packages.R]: Just realized the comment might not be very helpful.  I'll change it from "ggplot2" to "for ggplot2".

**Comment by samuelklee** [comment]
Thanks, @cmnbroad!

- You're right about gatkbase-2.1.0, that image is coming from #5026, which needs some more work.  We can delete it for the time being if you think it'll cause confusion.
- Correct, I think the import statement for `reshape` in BQSR.R was always incorrect/extraneous.  `reshape2` is the correct dependency for `ggplot2` (which is itself imported), and `reshape` is not explicitly used in BQSR.R.  So to recap: I removed the installation of this unnecessary package, but failed to remove an unnecessary import statement since it was in an untested code path, which was then caught when users tried to run the tool.  Investigation of this issue then revealed that `ggplot2` was not installed correctly in the current base image, due to a completely unrelated dependency issue.
- Good call on clearing the Travis cache.  Not actually sure how to do that, do I just delete the cache at https://travis-ci.org/broadinstitute/gatk/caches for this particular branch?

**Comment by samuelklee** [comment]
OK, done, thanks!  Fingers crossed that everything is fixed now...!
