### PR TITLE
Fix HC OOB -- Assumed ploidy two in a dumb spot -- no calls were always diploid

### LINKED ISSUE #6552: GATK 4.1.6.0 haplotypecaller ArrayIndexOutOfBoundsException
Dear GATK team,

I am getting errors with haplotyper of GATK 4.1.6.0 when i run gatk-variant pipeline from bcbio on one WGS sample. I am getting same error when i run using same version of GATK installed on my machine.

### Error log

[April 15, 2020 8:14:35 AM GMT] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.80 minutes.
Runtime.totalMemory()=4151902208
java.lang.ArrayIndexOutOfBoundsException: 6
        at org.broadinstitute.hellbender.utils.GenotypeUtils.computeDiploidGenotypeCounts(GenotypeUtils.java:70)
        at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.calculateEH(ExcessHet.java:86)
        at org.broadinstitute.hellbender.tools.walkers.annotator.ExcessHet.annotate(ExcessHet.java:74)
        at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.annotateContext(VariantAnnotatorEngine.java:293)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.makeAnnotatedCall(HaplotypeCallerGenotypingEngine.java:365)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.assignGenotypeLikelihoods(HaplotypeCallerGenotypingEngine.java:189)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:608)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:212)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)
Using GATK jar BCBIO/v1.2.0_updated/anaconda/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms4g -Xmx13g -XX:+UseSerialGC -Djava.io.tmpdir=test-bcbio-1.2.0-wgs-hapmap/scratch/bcbiotx/tmpnhcoi74c -jar BCBIO/v1.2.0_updated/anaconda/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar HaplotypeCaller -R BCBIO/v1.2.0_updated/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I test-bcbio-1.2.0-wgs-hapmap/scratch/align/HAPMAP_S5_L005/HAPMAP_S5_L005-sort-recal.bam -L test-bcbio-1.2.0-wgs-hapmap/scratch/gatk-haplotype/chrY/HAPMAP_S5_L005-joint-chrY_0_16134738-regions.bed --interval-set-rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 -ploidy 1 --output test-bcbio-1.2.0-wgs-hapmap/scratch/bcbiotx/tmpnhcoi74c/HAPMAP_S5_L005-joint-chrY_0_16134738.vcf.gz

#### Command i used

gatk --java-options '-Xms4g -Xmx13g -XX:+UseSerialGC -Djava.io.tmpdir=test-bcbio-1.2.0-wgs-hapmap/scratch/bcbiotx/tmpv1ztgr87' HaplotypeCaller -R BCBIO/v1.2.0_updated/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I test-bcbio-1.2.0-wgs-hapmap/scratch/align/HAPMAP_S5_L005/HAPMAP_S5_L005-sort-recal.bam -L chrUn_KI270583v1:1-340 --interval-set-rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 -ploidy 2 --output test-bcbio-1.2.0-wgs-hapmap/scratch/bcbiotx/tmpv1ztgr87/HAPMAP_S5_L005-joint-chrUn_KI270583v1_0_340.vcf.gz

Please help me to resolve this issue.

Thanks In Advance
Fazulur Rehaman

### PR DESCRIPTION
**Pull request by ldgauthier**
Fixes #6552

### CODE REVIEW

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java [hunk 1]
```diff
@@ -1341,6 +1341,27 @@ public void testLeadingDeletionInAltHaplotype() {
...
+                .addInput(bam)
+                .addReference(hg38Reference)
+                .addInterval("chrY:11315390")
+                .add(AssemblyBasedCallerArgumentCollection.EMIT_REF_CONFIDENCE_LONG_NAME, ReferenceConfidenceMode.GVCF.toString())
+                .add(GenotypeCalculationArgumentCollection.SAMPLE_PLOIDY_SHORT_NAME, 1)
+                .addOutput(output);
+        runCommandLine(args);
+
+        final boolean hasGQ0call = VariantContextTestUtils.streamVcf(output)
+                .anyMatch(vc -> vc.getStart() == 11315390 && vc.getGenotype(0).hasGQ() && vc.getGenotype(0).getGQ() == 0);
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java:1360]: Don't you want to assert that the ploidy of the call is haploid here?
