### PR TITLE
Extend somatic support in GenotypeGVCFs to use DRAGEN SQ

### LINKED ISSUE #7840: GenotypeGVCFs can't handle somatic GVCFs from DRAGEN 3.8.4
### Affected tool(s) or class(es)
GenotypeGVCFs

### Affected version(s)
- [x] Latest public release version [version?]
- [x] Latest master branch as of [date of test?]

### Description 
GenotypeGVCFs won't joint call DRAGEN mitochondrial data because of the DRAGEN somatic output format.

We should be able to use the DRAGEN SQ in place of Mutect2's TLOD (see line 279 in GenotypeGVCFsEngine)
Note that DRAGEN SQ is a Phred-scaled double

#### Steps to reproduce
DRAGEN somatic GVCF entries from version 3.8.4 look like:
chrM 1 . G <NON_REF> . weak_evidence END=1 GT:AD:DP:SQ:MIN_DP 0/0:112,1579:1691:0:1691

Run GenotypeGVCFs with -V to a file like that (reference GenotypeGVCFsIntegrationTest::testGenotypingForSomaticGVCFs() for more details)
Must include `--input-is-somatic` as of now

#### Expected behavior
The task should run to completion, calculating a site quality store using the DRAGEN SQ value

#### Actual behavior
Error from AlleleFrequencyCalculator about not having PLs or GQ.

### PR DESCRIPTION
**Pull request by ldgauthier**
DRAGEN 3.8 introduced "somatic quality" for mitochondrial variants: https://support-docs.illumina.com/SW/DRAGEN_v40/Content/SW/DRAGEN/MitochondrialCalling.htm (those are v4 docs, but same principles apply). GenotypeGVCFs supported Mutect2-style mitochondrial GVCFs, but expected GQs to determine variant quality. This PR extends the Mutect2 joint genotyping logic to handle variants with SQs, as output by DRAGEN >= 3.8

Fixes #7840

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsEngine.java [hunk 1]
```diff
@@ -273,22 +273,32 @@ private VariantContext regenotypeSomaticVC(final VariantContext originalVC, fina
...
+    private VariantContext callSomaticGenotypes(final VariantContext vc, double tlodThreshold, double sqThreshold, double afTolerance) {
         final List<Genotype> newGenotypes = new ArrayList<>();
         final GenotypesContext genotypes = vc.getGenotypes();
         final double[] perAlleleLikelihoodSums = new double[vc.getAlleles().size()];  //needs the ref for the subsetting utils
 
         for(final Genotype g : genotypes) {
             GenotypeBuilder gb = new GenotypeBuilder(g);
-            final double[] tlodArray = VariantContextGetters.getAttributeAsDoubleArray(g, GATKVCFConstants.TUMOR_LOG_10_ODDS_KEY, () -> null, 0.0);
+            // First try to get SQ (Somatic Quality) values, if not available fall back to TLOD
+            double[] likelihoodArray;
```
Comment (davidbenjamin) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/GenotypeGVCFsEngine.java:284]: I would like to see something like:
```
final boolean has SQ = g.hasExtendedAttribute(GATKVCFConstants.SOMATIC_QUALITY_KEY);
final String likelihoodKey = hasSQ ? GATKVCFConstants.SOMATIC_QUALITY_KEY : GATKVCFConstants.TUMOR_LOG_10_ODDS_KEY;
final double[] likelihoodArray = VariantContextGetters.getAttributeAsDoubleArray(g, likelihoodKey, () -> null, 0.0);
```

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtils.java [hunk 2]
```diff
@@ -472,11 +472,22 @@ public static int[] getIndexesOfRelevantAllelesForGVCF(final List<Allele> remapp
         // create the index mapping, using the <NON-REF> allele whenever such a mapping doesn't exist
         for ( int i = 1; i < targetAlleles.size(); i++ ) {
             // if there's more than 1 spanning deletion (*) allele then we need to use the best one
-            if (targetAlleles.get(i) == Allele.SPAN_DEL && !doSomaticMerge && g.hasPL()) {
+            if (targetAlleles.get(i) == Allele.SPAN_DEL) {
                 final int occurrences = Collections.frequency(remappedAlleles, Allele.SPAN_DEL);
                 if (occurrences > 1) {
-                    final int indexOfBestDel = indexOfBestDel(remappedAlleles, g.getPL(), g.getPloidy());
-                    indexMapping[i] = (indexOfBestDel == -1 ? indexOfNonRef : indexOfBestDel);
+                    // If we have PLs and it's not a somatic merge, use the best spanning deletion based on PLs
```
Comment (davidbenjamin) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/genotyper/AlleleSubsettingUtils.java:478]: Instead of splitting the single vs multiple `SPAN_DEL` cases, can this all be reduced to a stream one-liner of finding the maximum?

**Review by davidbenjamin — APPROVED** [review]
A couple of minor comments; merge when you are satisfied with what you decide to do with them!
