### PR TITLE
Changed the build_docker.sh to run git LFS dependent tests

### LINKED ISSUE #3191: build_docker.sh needs to download and mount the large files when running unit tests
Currently the script fails when configured to run tests, since it doesn't have access to the large files in the docker image. These need to be downloaded and mounted for the tests to pass, as we do in the docker tests on travis.

### PR DESCRIPTION
**Pull request by jamesemery**
Also deletes the staging directory when finished.

fixes #3191

### CODE REVIEW

File: build_docker.sh [hunk 1]
```diff
@@ -89,7 +91,9 @@ if [ -n "$STAGING_DIR" ]; then
     set -e
     GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/${REPO}/${PROJECT}.git ${STAGING_DIR}/${STAGING_CLONE_DIR}
     cd ${STAGING_DIR}/${STAGING_CLONE_DIR}
-    echo "Now in ${PWD}"
+    STAGING_ABSOLUTE_PATH=$(pwd)
+
+    echo "Now in $(pwd)"
         if [ ${PULL_REQUEST_NUMBER} ]; then
```
Comment (lbergelson) [inline build_docker.sh]: the indentation here is funny although it looks like it was like that before you got here...
