### PR TITLE
Refining handling of transcripts with missing sequence info and other fixes.

### LINKED ISSUE #4739: missing transcript in hg19 gencode
The hg19 gencode is missing the transcript `ENST00000515683.1`.   It appears in the gtf, but not in the fasta.  Using `funcotator_dataSources.v1.2.20180329`

```
A USER ERROR has occurred: Bad input: Unable to find the given Transcript ID in our transcript list (not in given transcript FASTA file): ENST00000515683.1
```
```
 gatk Funcotator --output-file-format VCF \
--ref-version hg19 --data-sources-path ~/data/funcotator/funcotator_dataSources.v1.2.20180329/ \
-R ~/data/Homo_sapiens_assembly19.fasta -V 0816201804HC0_R01C01.vcf.gz \
-O 0816201804HC0_R01C01.funcotated.vcf
```

The error is triggered somewhere near the position`4:60143686`

### PR DESCRIPTION
**Pull request by jonn-smith**
Fixes #4739
Refactored UTR VariantClassification handling.
Added warning statement when a transcript in the UTR has no sequence info (now is the same behavior as in protein coding regions).
Added tests to prevent regression on data source date comparison bug.
Now can run on large data.
Fixed DNA Repair Genes getter script.
Fixed an issue in COSMIC to make it robust to bad COSMIC data.
Gencode no longer crashes when given an indel that starts just before an exon.
Fixed the SimpleKeyXsvFuncotationFactory to allow any characters to work as delimiters (including characters used in regular expressions, such as pipes).
Modified several methods to allow for negative start positions in
preparation for allowing indels that start outside exons.

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java [hunk 1]
```diff
@@ -346,10 +351,21 @@ public static int getAlignedPosition(final int position) {
      */
     public static boolean isInFrameWithEndOfRegion(final int startPosition, final int regionLength) {
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorUtils.java]: The javadoc is no longer correct for the start position.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/cosmic/CosmicFuncotationFactory.java [hunk 2]
```diff
@@ -332,7 +335,15 @@ private final SimpleInterval getGenomePositionFromResults(final ResultSet result
                 final int start = Integer.valueOf(matcher.group(2));
                 final int end = Integer.valueOf(matcher.group(3));
 
-                return new SimpleInterval(contig, start, end);
+                try {
+                    return new SimpleInterval(contig, start, end);
+                }
+                catch (final IllegalArgumentException ex) {
+                    // If we have poorly bounded genomic positions, we need to warn the user and move on.
+                    // These may occur occasionally in the data.
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/cosmic/CosmicFuncotationFactory.java]: Do you see this warning come up much on real data?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/cosmic/CosmicFuncotationFactory.java [hunk 3]
```diff
@@ -369,18 +380,51 @@ private final SimpleInterval parseProteinString(final String proteinPositionStri
...
+                logger.warn("Warning - unable to parse protein string due to invalid position information.  Ignoring potential COSMIC match with protein sequence: " + proteinPositionString);
+                return null;
             }
         }
         return null;
     }
 
+    /**
+     * Print the given {@link ResultSet} to stdout.
+     * @param resultSet The {@link ResultSet} to print.
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/cosmic/CosmicFuncotationFactory.java]: Why do we need this method?  Typically, we should log it (as a debug if necessary)

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 4]
```diff
@@ -597,16 +597,27 @@ private GencodeFuncotation createGencodeFuncotationOnTranscript(final VariantCon
         // Find the sub-feature of transcript that contains our variant:
         final GencodeGtfFeature containingSubfeature = getContainingGtfSubfeature(variant, transcript);
 
-        // Make sure the start and end of the variant are both in the transcript:
+        // Make sure the sub-regions in the transcript actually contain the variant:
+        // TODO: this is slow, and repeats work that is done later in the process (we call getSortedCdsAndStartStopPositions when creating the sequence comparison)
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Can you file an issue for this `TODO`?

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 5]
```diff
@@ -597,16 +597,27 @@ private GencodeFuncotation createGencodeFuncotationOnTranscript(final VariantCon
...
             gencodeFuncotation = createIgrFuncotation(variant, altAllele, reference);
         }
         else if ( GencodeGtfExonFeature.class.isAssignableFrom(containingSubfeature.getClass()) ) {
-            // We have a coding region variant
-            gencodeFuncotation = createExonFuncotation(variant, altAllele, gtfFeature, reference, transcript, (GencodeGtfExonFeature) containingSubfeature);
+
+            if ( startPosInTranscript == -1 ) {
+                // we overlap an exon but we don't start in one.  Right now this case cannot be handled.
+                // Bubble up an exception and let the caller handle this case.
+                // TODO: fix this case, issue #4804 (https://github.com/broadinstitute/gatk/issues/4804)
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Glad that #4804 is a beta blocker.  No further action needed for this PR.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 6]
```diff
@@ -1077,47 +1086,53 @@ private GencodeFuncotation createUtrFuncotation(final VariantContext variant,
...
+                    }
+                    else {
+                        gencodeFuncotationBuilder.setVariantClassification(GencodeFuncotation.VariantClassification.DE_NOVO_START_OUT_FRAME);
+                    }
                 }
             }
-            // Just a normal 5' variant:
             else {
-                gencodeFuncotationBuilder.setVariantClassification(GencodeFuncotation.VariantClassification.FIVE_PRIME_UTR);
+                logger.warn("Attempted to process transcript information for transcript WITHOUT sequence data.  Ignoring sequence information for Gencode Transcript ID: " + transcript.getTranscriptId());
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: When would this happen?  Not sure if any action is needed.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 7]
```diff
@@ -1441,8 +1456,9 @@ static SequenceComparison createSequenceComparison(final VariantContext variant,
         if ( processSequenceInformation ) {
             if ( transcriptIdMap.containsKey(transcript.getTranscriptId()) ) {
 
+                final String transcriptSequence;
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Why can't these two lines be merged back into one?

File: scripts/funcotator/data_sources/getDnaRepairGenes.py [hunk 8]
```diff
@@ -53,23 +53,35 @@
         writer = csv.writer(f, delimiter='|', lineterminator="\n")
 
         isFirstRow = True
```
[the remark this answers is not in the document]
Comment (jonn-smith) [reply scripts/funcotator/data_sources/getDnaRepairGenes.py]: No prob.

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 6 above)
Comment (jonn-smith) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: This would happen when the Gencode data source does not have a sequence for a given transcript.  The information in the resulting funcotation will be correct, but it will be a subset of what a user may expect.  This does happen in practice, so I wanted to make sure it was logged as a warning.
