### PR TITLE
Truncate queries in ReferenceTwoBitSource at contig ends when necessary

### LINKED ISSUE #1214: assertion fail with TwoBit reference (query past end of contig)
command 
```
spark-submit \
  --master $SPARK_MASTER \
  --driver-memory 8G \
  --num-executors ${1} \
  --executor-cores 4 \
  --executor-memory 20G \
  --conf spark.driver.maxResultSize=0 \
  --conf spark.driver.userClassPathFirst=true \
  --conf spark.executor.userClassPathFirst=true \
  --conf spark.io.compression.codec=lzf \
  --conf spark.yarn.executor.memoryOverhead=600 \
      $JAR BaseRecalibratorSpark \
        --input hdfs:///user/akiezun/CEUTrio.HiSeq.WEx.b37.NA12892.bam \
        --output bqsr_out_${1}.bam \
        -R hdfs:///user/droazen/bqsr/human_g1k_v37.2bit \
        --knownSites hdfs:////user/akiezun/dbsnp_138.b37.excluding_sites_after_129.vcf \
        --joinStrategy BROADCAST \
        --apiKey $API_KEY \
        --sparkMaster $SPARK_MASTER
```

fails with
```
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:165)
	at org.bdgenomics.adam.util.TwoBitFile.extract(TwoBitFile.scala:112)
	at org.bdgenomics.adam.util.TwoBitFile.extract(TwoBitFile.scala:170)
	at org.broadinstitute.hellbender.engine.spark.datasources.ReferenceTwoBitSource.getReferenceBases(ReferenceTwoBitSource.java:48)
	at org.broadinstitute.hellbender.engine.datasources.ReferenceMultiSource.getReferenceBases(ReferenceMultiSource.java:99)
	at org.broadinstitute.hellbender.engine.spark.BroadcastJoinReadsWithRefBases.lambda$addBases$c54addeb$1(BroadcastJoinReadsWithRefBases.java:53)
...
```

### PR DESCRIPTION
**Pull request by droazen**
The TwoBit API can't handle queries beyond the ends of contigs (we get
an assertion failure). This changes ReferenceTwoBitSource to truncate query
intervals at contig ends as necessary.

Resolves #1214

### CODE REVIEW

**Comment by droazen** [comment]
For @akiezun to review, please.

File: src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceTwoBitSource.java [hunk 1]
```diff
@@ -32,6 +32,7 @@
 
     private String referenceURL;
     private TwoBitFile twoBitFile;
+    private Map<String, TwoBitRecord> twoBitSeqEntries;
```
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/engine/spark/datasources/ReferenceTwoBitSource.java]: all three fields should be final

**Comment by akiezun** [comment]
i confirm that this fixed the error i saw (now i get the IAE but that's #1234 )

back to @droazen - trivial tweak and then good to merge
