### PR TITLE
Changed twoPassReadsWalker to reinitialize the reads to ensure equivalent behavior across SAM formats

### LINKED ISSUE #2117: Make the TwoPassReadsWalker accept all types of input files
The twoPassReadsWalker currently only iterates twice through the reads as intended for BAM files. If given a text SAM file as input it will fail to iterate through the file a second time. This has to do with the SAMTextReader not using a seekable stream for the SAM file in htsjdk, which proves to be complicated to fix given the current api implementation there. A workaround for this is to reinitialize ReadsDataSource between passes through the input for twoPassReadsWalker and test that it works for all types of read files.

### PR DESCRIPTION
**Pull request by jamesemery**
resolves #2117

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/engine/TwoPassReadWalker.java [hunk 1]
```diff
@@ -34,6 +34,11 @@ public void traverse() {
         traverseReads(countedFilter, this::firstPassApply);
         logger.info("Finished First Pass");
         afterFirstPass();
+        // Need to reinitilize the reads and intervals so they are guarinteed to pass over a file
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/engine/TwoPassReadWalker.java]: typos:  reinitialize and guaranteed

File: src/main/java/org/broadinstitute/hellbender/engine/TwoPassReadWalker.java [hunk 2]
```diff
@@ -34,6 +34,11 @@ public void traverse() {
...
+        initializeReads();
+        if ( hasIntervals() ) {
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/engine/TwoPassReadWalker.java]: could you extract this as a package private function `setReadTraversalBounds()` in ReadWalker since it's just a copy from their?

File: src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+    }
+
+    @Test(dataProvider = "extensions")
+    public void testDifferentFormatEquivalentBehavior(String ext) throws IOException {
+        final TwoPassReadsWalkerUnitTest.dummyTwoPassReadsWalker tool = new TwoPassReadsWalkerUnitTest.dummyTwoPassReadsWalker();
+        final CommandLineParser clp = new CommandLineParser(tool);
+
+        final String[] args = {
+                "-I", getTestDataDir()+ "/count_reads" + ext,
+                "-R", getTestDataDir()+ "/count_reads.fasta"
```
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java]: do you need a reference for this?

File: src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+        };
+
+
+        clp.parseArguments(System.out, args);
+        tool.onStartup();
+        tool.doWork();
+        tool.onShutdown();
+
+        Assert.assertTrue(tool.everythingWorked());
```
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java]: instead of asserting tool.everythingWorked(), could you check the individual values instead? .

i.e. `Assert.assertEquals(firstPassCount, 8)` etc... I think that would be a little clearer.

Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java]: It also solves the problem that in the current situation you might accidentally be reading 0 in both passes and not noticing.

File: src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+        public boolean everythingWorked() {
+            if (firstPass != secondPass || !betweenTraversals) {
+                return false;
+            }
+            return true;
+        }
+    }
+
+    @Override
+    public String getTestedClassName() {
```
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java]: Not actually using this since you're not using runCommandLine.

File: src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+        tool.onStartup();
+        tool.doWork();
+        tool.onShutdown();
+
+        Assert.assertTrue(tool.everythingWorked());
+    }
+
+    @DataProvider(name = "extensions")
+    public Object[][] makeExtensions() {
+        return new Object[][] {{".bam"}, {".sam"}, {".cram"}};
```
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java]: Could you switch this to just specifying the whole file name instead of the extension, it makes it easier to search for where files are used if they whole name is in one piece.

**Comment by lbergelson** [comment]
@jamesemery Looks good.  I had a few very minor comments.  

Could you also add a test that does the same thing but uses a -L interval since you had to do some extra stuff to get that working and it tends to be a bit touchy?
Thank you!

File: src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java (hunk 3 above)
Comment (jamesemery) [inline src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java]: Yes, apparently cram files can't be read without a reference so it was easier to include it despite it not being relevant to my test.

**Comment by jamesemery** [comment]
@lbergelson Alright, I have responded to all of your comments on the branch and added an explicit interval test (I could not check the same test for .sam files because they are unindexed and don't support interval traversals)

File: src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java (hunk 3 above)
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/engine/TwoPassReadsWalkerUnitTest.java]: Ah, yes, of course.  Makes sense.

**Comment by lbergelson** [comment]
👍
