### PR TITLE
Fixed alt-allele count in AllelicCountCollector and changed unspecified alleles in AllelicCount to N.

### LINKED ISSUE #3548: AllelicCountCollector infers the wrong alternate allele from the pileups
If you run this on position 20:10022820 in `src/test/resources/large/mutect/dream_synthetic_bams/tumor.bam` you will get the wrong alt (you get C, but should be T).  

Proposed solution:  Use findLast() (or reverse b1 and b2 in the compare statement to get this to sort in descending order).

```
    private static Nucleotide inferAltFromPileupBaseCounts(final Nucleotide.Counter baseCounts,
                                                           final Nucleotide refNucleotide) {
        return BASES.stream()
                .filter(b -> b != refNucleotide)
                .sorted((b1, b2) -> Long.compare(baseCounts.get(b1), baseCounts.get(b2)))
                .findFirst().get();
    }
```

### PR DESCRIPTION
**Pull request by samuelklee**
Closes #3548.

### CODE REVIEW

**Comment by samuelklee** [comment]
The code-coverage report was way off...not sure why?

**Comment by lbergelson** [comment]
@samuelklee Code cov reports are usually off for one of two reasons: 1. something went horribly wrong and codecov reported coverage before all the travis jobs finished.  2.  something went horribly wrong and a large chunk of tests are silently failing to execute.  Good to check that it's 1 and not 2.  Usually rerunning should fix case 1.

**Comment by samuelklee** [comment]
@LeeTL1220 please review.  Sorry for the delay, there was some funkiness with travis and the code-coverage report.

**Comment by samuelklee** [comment]
@LeeTL1220 can you review?

**Comment by LeeTL1220** [comment]
Yes, somehow this fell through.  I'll take a look.

File: src/main/java/org/broadinstitute/hellbender/tools/copynumber/allelic/alleliccount/AllelicCount.java [hunk 1]
```diff
@@ -18,30 +18,29 @@
...
-        /* these can be null */
-        this.refNucleotide = refNucleotide;
-        this.altNucleotide = altNucleotide;
+        this.refNucleotide = Utils.nonNull(refNucleotide);
+        this.altNucleotide = Utils.nonNull(altNucleotide);
     }
 
     public AllelicCount(final SimpleInterval interval, final int refReadCount, final int altReadCount) {
-        this(interval, refReadCount, altReadCount, null, null);
+        this(interval, refReadCount, altReadCount, Nucleotide.N, Nucleotide.N);
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/copynumber/allelic/alleliccount/AllelicCount.java]: Do we ever need this constructor?

**Comment by LeeTL1220** [comment]
@samuelklee Just one comment.  Whether we need a constructor or can it be deleted?

**Comment by LeeTL1220** [comment]
@samuelklee Feel free to merge regardless of your decision.  This PR is actually blocking a validation.

File: src/main/java/org/broadinstitute/hellbender/tools/copynumber/allelic/alleliccount/AllelicCount.java (hunk 1 above)
Comment (samuelklee) [reply src/main/java/org/broadinstitute/hellbender/tools/copynumber/allelic/alleliccount/AllelicCount.java]: Originally, `AllelicCount` didn't even store the nucleotides, since the allele-fraction only needs the count information.  @mbabadi added the nucleotides for GetBayesianHetCoverage.  So once we port over a v1.5 allele-fraction model to the new copynumber package, I expect that this constructor could come in handy.
