### PR TITLE
usage page fixes

### LINKED ISSUE #1150: CLI usage page bogosities
- [x] `Exome Analysis: Tools to analyze exome data. ` should be renamed to something about CNVs or removed altogether. Most of our tools can be used to analyze exome data and so this group designation is bogus
- [x] `ExampleIntervalWalker                        Print intervals with optional contextual data` I'd add something about 'it's a example'
- [x] top of the page says `USAGE: Main <program name> [-h]` - there's no Main
- [x] `Miscellaneous Tools:` has only 1 tool 'NormalizeFasta`. I'd fold this tool to another group and remove the misc
- [x] all mentions of `a SAM or BAM` should be changed to SAM/BAM/CRAM
- [x] all metrics that have names matching  `Collect*Metrics` should have the same form of a doc. Now it's all messy, eg `Produces from a SAM or BAM a file containing summary alignment metrics` vs `Writes insert size distribution metrics for a SAM or BAM file` vs `Produces jumping library metrics for the provided SAM/BAMs`
- [x] note, normally, we'd rename all metrics to have the same form of name but let's  wait until picard is sync'd up
- [x] note, normally we'd rename all commands that mention 'Sam` to something more accurate but we're waiting for picard sync up
- [x] ApplyBQSR can also work on SAM and CRAM but doc says `Applies the BQSR table to the input BAM`
- [x] some entries has periods at the end, some don't. Make them the same (no periods)
- [x] add works BQSR to doc of `BaseRecalibrator` and `AnalyzeCovariates`
- [x] CountBases should say more than `Count bases`
- [x] CountReads should say more than `Count reads`
- [x] PrintReads  should say more than `Print reads`
- [x] LeftAlignIndels should capitalize `bam` in doc
- [x] `Spark tests:                                     Programs to test out Apache Spark` should  be less about tests and more about 'spark-enabled implementation of tools'. Somethng like that
- [x] `ApplyBQSRSpark                               apply BQSR on spark` -> `ApplyBQSR on Spark`
- [x] `BQSRPipelineSpark                            Both steps of BQSR` - what steps?
- [x]  both BaseRecalibratorSpark and  BaseRecalibratorSparkOptimized say `Generates recalibration table`
- [x] I think all Spark tools can just have doc saying `TOOLNAMe on Spark` if it's all they are
- [x] `CountVariants                                Count variants` - counts them where?
- [x] ExampleReadWalkerWithVariants should be in the BAM/CRAM/SAM group'
- [x] ExampleVariantWalker add 'example' to its doc
- [x] IndexFeatureFile `Creates indices for Feature-containing files` is too cryptic
- [x] LiftoverVcf - all tools for liftover should use the same language. Now each one describes it differently
- [x] i think we should remove all mentions of BCF. We're not supporting BCF 2.1 and so it's kind of bogus to mention BCF until we do
- [x] it's very confusing to have VariantFiltration vs FilterVcf vs SelectVariants.

### PR DESCRIPTION
**Pull request by akiezun**
fixes #1150 

for @lbergelson

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgramProperties.java [hunk 1]
```diff
@@ -29,6 +29,6 @@
      * @return an example command line for this program
      */
     String usageExample() default "The author of this program hasn't included any example usage, please complain to them.";
-    Class<? extends CommandLineProgramGroup> programGroup() default MiscProgramGroup.class;
+    Class<? extends CommandLineProgramGroup> programGroup() default FastaProgramGroup.class;
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgramProperties.java]: Why did you make FastaProgramGroup the default?  Surely Misc is more appropriate?

Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgramProperties.java]: misc is no more

File: src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java [hunk 2]
```diff
@@ -31,7 +31,7 @@
  */
 @CommandLineProgramProperties(
         summary = "Creates indices for Feature-containing files, such as VCF, BCF, and BED files",
-        oneLineSummary = "Creates indices for Feature-containing files",
+        oneLineSummary = "Creates indices for Feature-containing files (eg VCF, BCF, and BED files)",
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java]: No BCF

File: src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/AlignmentSummaryMetricsCollector.java [hunk 3]
```diff
@@ -34,7 +34,7 @@
     private final int maxInsertSize;
 
 
-    //Whether the SAM or BAM file consists of bisulfite sequenced reads.
+    //Whether the SAM/BAM file consists of bisulfite sequenced reads.
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/AlignmentSummaryMetricsCollector.java]: should this include cram?

File: src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectBaseDistributionByCycle.java [hunk 4]
```diff
@@ -19,8 +19,8 @@
 import java.util.*;
 
 @CommandLineProgramProperties(
-        summary = "Program to chart the nucleotide distribution per cycle in a SAM or BAM file.",
-        oneLineSummary = "Program to chart the nucleotide distribution per cycle in a SAM or BAM file.",
+        summary = "Program to chart the nucleotide distribution per cycle in a SAM/BAM/CRAM file",
+        oneLineSummary = "Produced metrics about nucleotide distribution per cycle in a SAM/BAM/CRAM file",
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectBaseDistributionByCycle.java]: Produce*s*

File: src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/CollectTargetedPcrMetrics.java [hunk 5]
```diff
@@ -16,8 +16,8 @@
  * more information
  */
 @CommandLineProgramProperties(
-        summary = "Calculates a set of metrics to Illumina Truseq Custom Amplicon sequencing from an aligned SAM" +
-                "or BAM file. If a reference sequence is provided, AT/GC dropout metrics will " +
+        summary = "Calculates a set of metrics to Illumina Truseq Custom Amplicon sequencing from an aligned SAM/BAM" +
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/CollectTargetedPcrMetrics.java]: cram?

File: src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/TargetMetrics.java [hunk 6]
```diff
@@ -19,13 +19,13 @@
     /** The number of bases in the reference genome used for alignment. */
     public long GENOME_SIZE;
 
-    /** The total number of reads in the SAM or BAM file examined. */
+    /** The total number of reads in the SAM/BAM file examined. */
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/TargetMetrics.java]: Cram?

File: src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/TargetMetrics.java [hunk 7]
```diff
@@ -19,13 +19,13 @@
...
     public long TOTAL_READS;
 
     /** The number of reads that pass the vendor's filter. */
     public long PF_READS;
 
-    /** The number of bases in the SAM or BAM file to be examined */
+    /** The number of bases in the SAM/BAM file to be examined */
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/TargetMetrics.java]: cram?

File: src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/TargetedPcrMetrics.java [hunk 8]
```diff
@@ -17,13 +17,13 @@
     /** The number of unique bases covered by the intervals of all targets that should be covered */
     public long TARGET_TERRITORY;
 
-    /** The total number of reads in the SAM or BAM file examine. */
+    /** The total number of reads in the SAM/BAM file examine. */
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/TargetedPcrMetrics.java]: cram?

File: src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/TargetedPcrMetricsCollector.java [hunk 9]
```diff
@@ -9,7 +9,7 @@
 import java.util.*;
 
 /**
- * Calculates HS metrics for a given SAM or BAM file. Requires the input of a list of
+ * Calculates HS metrics for a given SAM/BAM file. Requires the input of a list of
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/TargetedPcrMetricsCollector.java]: cram

File: src/main/java/org/broadinstitute/hellbender/tools/picard/sam/FastqToSam.java [hunk 10]
```diff
@@ -23,9 +23,9 @@
  * Input files can be in GZip format (end in .gz).
  */
 @CommandLineProgramProperties(
-        summary = "Extracts read sequences and qualities from the input fastq file and writes them into the output file in unaligned BAM format."
+        summary = "Extracts read sequences and qualities from the input fastq file and writes them into the output file in unaligned SAM/BAM format."
                 + " Input files can be in GZip format (end in .gz).\n",
-        oneLineSummary = "Converts a fastq file to an unaligned BAM or SAM file",
+        oneLineSummary = "Converts a fastq file to an unaligned SAM/BAM file",
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/sam/FastqToSam.java]: Cram?

File: src/main/java/org/broadinstitute/hellbender/tools/picard/sam/FastqToSam.java [hunk 11]
```diff
@@ -23,9 +23,9 @@
  * Input files can be in GZip format (end in .gz).
  */
 @CommandLineProgramProperties(
-        summary = "Extracts read sequences and qualities from the input fastq file and writes them into the output file in unaligned BAM format."
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/sam/FastqToSam.java]: cram?

File: src/main/java/org/broadinstitute/hellbender/tools/picard/sam/MergeSamFiles.java [hunk 12]
```diff
@@ -3,30 +3,33 @@
...
 /**
- * Reads a SAM or BAM file and combines the output to one file
+ * Reads a SAM/BAM/CRAM file and combines the output to one file
  *
  * @author Tim Fennell
  */
 @CommandLineProgramProperties(
         summary = "Merges multiple SAM/BAM files into one file.",
-        oneLineSummary = "Merges multiple SAM or BAM files into one file",
+        oneLineSummary = "Merges multiple SAM/BAM files into one file",
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/sam/MergeSamFiles.java]: cram?

File: src/main/java/org/broadinstitute/hellbender/tools/picard/sam/MergeSamFiles.java [hunk 13]
```diff
@@ -3,30 +3,33 @@
...
         programGroup = ReadProgramGroup.class
 )
 public final class MergeSamFiles extends PicardCommandLineProgram {
 
-    @Argument(shortName = "I", doc = "SAM or BAM input file", optional=false)
+    @Argument(shortName = "I", doc = "SAM/BAM input file", optional=false)
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/sam/MergeSamFiles.java]: cram?

File: src/main/java/org/broadinstitute/hellbender/tools/picard/sam/MergeSamFiles.java [hunk 14]
```diff
@@ -3,30 +3,33 @@
...
     public List<File> INPUT = new ArrayList<>();
 
-    @Argument(shortName = "O", doc = "SAM or BAM file to write merged result to")
+    @Argument(shortName = "O", doc = "SAM/BAM file to write merged result to")
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/sam/MergeSamFiles.java]: cram

File: src/main/java/org/broadinstitute/hellbender/tools/picard/sam/ReorderSam.java [hunk 15]
```diff
@@ -21,19 +23,19 @@
  * @author mdepristo
  */
 @CommandLineProgramProperties(
-        summary = "Not to be confused with SortSam which sorts a SAM or BAM file with a valid sequence dictionary, " +
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/sam/ReorderSam.java]: cram?

File: src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java [hunk 16]
```diff
@@ -35,7 +34,7 @@
 
 @CommandLineProgramProperties(
         summary = "Base Quality Score Recalibration (BQSR) -- Generates recalibration table based on various user-specified covariates (such as read group, reported quality score, machine cycle, and nucleotide context).",
-        oneLineSummary = "Generates recalibration table",
+        oneLineSummary = "BaseRecalibratorSpark on Spark",
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java]: shouldn't this be `BaseRecalibrator on Spark`?

File: src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkSharded.java [hunk 17]
```diff
@@ -49,7 +43,7 @@
 
 @CommandLineProgramProperties(
         summary = "Base Quality Score Recalibration (BQSR) -- Generates recalibration table based on various user-specified covariates (such as read group, reported quality score, machine cycle, and nucleotide context).",
-        oneLineSummary = "Generates recalibration table",
+        oneLineSummary = "BaseRecalibratoron on Spark (experimental sharded implementation)",
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkSharded.java]: typo BaseRecalibra**toron**

File: src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSpark.java [hunk 18]
```diff
@@ -16,7 +16,9 @@
 import java.io.OutputStream;
 import java.io.PrintStream;
 
-@CommandLineProgramProperties(summary = "Counts bases in the input BAM", oneLineSummary = "Counts bases in a BAM file", programGroup = SparkProgramGroup.class)
+@CommandLineProgramProperties(summary = "Counts bases in the input SAM/BAM",
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/CountBasesSpark.java]: cram for spark?  what's the status

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java [hunk 19]
```diff
@@ -40,7 +42,7 @@
 )
 public final class SplitNCigarReads extends CommandLineProgram {
 
-    @Argument(fullName = INPUT_LONG_NAME, shortName= INPUT_SHORT_NAME, doc="The SAM/BAM/CRAM file to read from.")
+    @Argument(fullName = INPUT_LONG_NAME, shortName= INPUT_SHORT_NAME, doc="The SAM/BAM file to read from.")
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java]: This doesn't support cram?

File: src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgramProperties.java (hunk 1 above)
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgramProperties.java]: Should we have no default then?  Fasta just seems wrong as a default.

File: src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/CollectWgsMetrics.java [hunk 20]
```diff
@@ -33,12 +34,12 @@
 @CommandLineProgramProperties(
         summary = "Computes a number of metrics that are useful for evaluating coverage and performance of " +
                 "whole genome sequencing experiments.",
-        oneLineSummary = "Writes whole genome sequencing-related metrics for a SAM or BAM file",
+        oneLineSummary = "Produces metrics related to whole genome sequencing for a SAM/BAM file",
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/directed/CollectWgsMetrics.java]: cram?

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java [hunk 21]
```diff
@@ -40,7 +42,7 @@
 )
 public final class SplitNCigarReads extends CommandLineProgram {
```
Comment (lbergelson) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java]: Should this move out of the walkers packages since it isn't actually a walker?

**Comment by lbergelson** [comment]
@akiezun Back to you with typos and such.

File: src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgramProperties.java (hunk 1 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgramProperties.java]: ok removed default

File: src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java (hunk 2 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/IndexFeatureFile.java]: ok

File: src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectBaseDistributionByCycle.java (hunk 4 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/picard/analysis/CollectBaseDistributionByCycle.java]: fixed

File: src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java (hunk 16 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSpark.java]: fixed

File: src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkSharded.java (hunk 17 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/spark/BaseRecalibratorSparkSharded.java]: fixed

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java (hunk 21 above)
Comment (akiezun) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/rnaseq/SplitNCigarReads.java]: ok
