### PR TITLE
ReadClipper: when reverting soft-clipped bases of a read at the start of a contig, don't explode if you end up with an empty read

### LINKED ISSUE #3845: HaplotypeCaller exception: contig must be non-null and not equal to *, and start must be >= 1
I'm using HaplotypeCaller (`gatk-package-4.beta.5`) to analyse the control medulloblastoma sample from the ICGC benchmark https://www.nature.com/articles/ncomms10001. Reads are aligned to `GRCh37` (from the Broad bundle, without decoy sequences) using `bwa mem`. Analysis is performed within the [bcbio-nextgen](https://github.com/chapmanb/bcbio-nextgen), which splits input into chunks by chromosome for parallelisation. For some reason, the chunk corresponding to the chromosome `GL000216.1` makes HaplotypeCaller crash with the error `IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1`.

I isolated the `gatk-launch` command, and narrowed down the reproducible example to these 2 reads:
```
H239:179:C1K3VACXX:8:2116:11771:72429   161     GL000216.1      19      23      70S31M  4       49141708        0       ATTCCCTTACATTCGGATTGATACTATTAAAATCACTTACTCTTCCTTACATTCCATTCCATCCGGGCTGTTCCATTTCATTCTATTACACTCCACTCAAT   ?1:=D>?B?CC:?A,<C;:AEGC<+AC+++2+:3*1:*11999*:099?<?0?99BBG*9?D*?#####################################   NM:i:2  MD:Z:25T2C2     AS:i:25 XS:i:20 RG:Z:MB_normal_50x      MQ:i:0  ms:i:1911       mc:i:49141802       MC:Z:11S30M5D60M
HWI-7001436:66:C3FYFACXX:5:1216:4411:82080      65      GL000216.1      27      57      101M    9       72653232        0       CATTCTATTACACTCCATTCCATTTCTATCCATTCCATTCCATTCTATTCCATTCCACTTGGGTCGATTCAATTCCATTCCATTCTATCCCTTCCATTCCA   CCCFFFFFHHHHHJJJJJIJJJJJJIJJJJHIJJJJJJJJJJJJJJJJJJJJJJJJJIJIJIJGGIJIJJJJJJJJJJJJJJJJJJGJHHHHHHFFFFFFD   NM:i:7  MD:Z:24C2T14A16C1T21C4T12       AS:i:66 XS:i:36 RG:Z:MB_normal_50x      MQ:i:0  ms:i:3858   mc:i:72653218   MC:Z:14S45M1D33M9
```
And one nucleotide target region:
```
GL000216.1      87      88
```

These BAM and BED files are attached here: [GL000216.1_87_gatk_debug.zip](https://github.com/broadinstitute/gatk/files/1477532/GL000216.1_87_gatk_debug.zip)

Running command below:
```
gatk-launch HaplotypeCaller \
 -R /data/projects/punim0010/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa \ 
 -I GL000216.1_start_49__read_84_88.bam \
 -L GL000216.1_87-88.bed \
 --output out.vcf.gz
```

Gives the following output: 
```
Using GATK jar /home/vlad/bcbio/anaconda/share/gatk4-4.0b5-0/gatk-package-4.beta.5-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Dsnappy.disable=true -jar /home/vlad/bcbio/anaconda/share/gatk4-4.0b5-0/gatk-package-4.beta.5-local.jar HaplotypeCaller -R /data/projects/punim0010/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --output bad.vcf.gz -I GL000216.1_49-49__84-88__play.bam -L
 bad_87-88.bed
16:51:50.560 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/vlad/bcbio/anaconda/share/gatk4-4.0b5-0/gatk-package-4.beta.5-local.jar!/com/intel/gkl/native/libgkl_compression.so
[16 November 2017 4:51:50 PM] HaplotypeCaller  --output bad.vcf.gz --intervals bad_87-88.bed --input GL000216.1_49-49__84-88__play.bam --reference /data/projects/punim0010/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa  --group StandardAnnotation --group StandardHCAnnotation --GVCFGQBands 1 --GVCFGQBands 2 --GVCFGQBands 3 --GVCFGQBands 4 --GVCFGQBands 5 --GVCFGQBands 6 --GVCFGQBands 7 --GVCFGQBands 8 --GVCFGQBands 9
 --GVCFGQBands 10 --GVCFGQBands 11 --GVCFGQBands 12 --GVCFGQBands 13 --GVCFGQBands 14 --GVCFGQBands 15 --GVCFGQBands 16 --GVCFGQBands 17 --GVCFGQBands 18 --GVCFGQBands 19 --GVCFGQBands 20 --GVCFGQBands 21 --GVCFGQBands 22 --GVCFGQBands 23 --GVCFGQBands 24 --GVCFGQBands 25 --GVCFGQBands 26 --GVCFGQBands 27 --GVCFGQBands 28 --GVCFGQBands 29 --GVCFGQBands 30 --GVCFGQBands 31 --GVCFGQBands 32 --GVCFGQBands 33 --GVCFGQBands 34 --
GVCFGQBands 35 --GVCFGQBands 36 --GVCFGQBands 37 --GVCFGQBands 38 --GVCFGQBands 39 --GVCFGQBands 40 --GVCFGQBands 41 --GVCFGQBands 42 --GVCFGQBands 43 --GVCFGQBands 44 --GVCFGQBands 45 --GVCFGQBands 46 --GVCFGQBands 47 --GVCFGQBands 48 --GVCFGQBands 49 --GVCFGQBands 50 --GVCFGQBands 51 --GVCFGQBands 52 --GVCFGQBands 53 --GVCFGQBands 54 --GVCFGQBands 55 --GVCFGQBands 56 --GVCFGQBands 57 --GVCFGQBands 58 --GVCFGQBands 59 --GVC
FGQBands 60 --GVCFGQBands 70 --GVCFGQBands 80 --GVCFGQBands 90 --GVCFGQBands 99 --indelSizeToEliminateInRefModel 10 --useAllelesTrigger false --dontTrimActiveRegions false --maxDiscARExtension 25 --maxGGAARExtension 300 --paddingAroundIndels 150 --paddingAroundSNPs 20 --kmerSize 10 --kmerSize 25 --dontIncreaseKmerSizesForCycles false --allowNonUniqueKmersInRef false --numPruningSamples 1 --recoverDanglingHeads false --doNotR
ecoverDanglingBranches false --minDanglingBranchLength 4 --consensus false --maxNumHaplotypesInPopulation 128 --errorCorrectKmers false --minPruning 2 --debugGraphTransformations false --kmerLengthForReadErrorCorrection 25 --minObservationsForKmerToBeSolid 20 --likelihoodCalculationEngine PairHMM --base_quality_score_threshold 18 --gcpHMM 10 --pair_hmm_implementation FASTEST_AVAILABLE --pcr_indel_model CONSERVATIVE --phredSc
aledGlobalReadMismappingRate 45 --nativePairHmmThreads 4 --useDoublePrecision false --debug false --useFilteredReadsForAnnotations false --emitRefConfidence NONE --bamWriterType CALLED_HAPLOTYPES --disableOptimizations false --justDetermineActiveRegions false --dontGenotype false --dontUseSoftClippedBases false --captureAssemblyFailureBAM false --errorCorrectReads false --doNotRunPhysicalPhasing false --min_base_quality_scor
e 10 --useNewAFCalculator false --annotateNDA false --heterozygosity 0.001 --indel_heterozygosity 1.25E-4 --heterozygosity_stdev 0.01 --standard_min_confidence_threshold_for_calling 10.0 --max_alternate_alleles 6 --max_genotype_count 1024 --sample_ploidy 2 --genotyping_mode DISCOVERY --contamination_fraction_to_filter 0.0 --output_mode EMIT_VARIANTS_ONLY --allSitePLs false --readShardSize -1 --readShardPadding 100 --minAssem
blyRegionSize 50 --maxAssemblyRegionSize 300 --assemblyRegionPadding 100 --maxReadsPerAlignmentStart 50 --activeProbabilityThreshold 0.002 --maxProbPropagationDistance 50 --interval_set_rule UNION --interval_padding 0 --interval_exclusion_padding 0 --interval_merging_rule ALL --readValidationStringency SILENT --secondsBetweenProgressUpdates 10.0 --disableSequenceDictionaryValidation false --createOutputBamIndex true --create
OutputBamMD5 false --createOutputVariantIndex true --createOutputVariantMD5 false --lenient false --addOutputSAMProgramRecord true --addOutputVCFCommandLine true --cloudPrefetchBuffer 40 --cloudIndexPrefetchBuffer -1 --disableBamIndexCaching false --help false --version false --showHidden false --verbosity INFO --QUIET false --use_jdk_deflater false --use_jdk_inflater false --gcs_max_retries 20 --disableToolDefaultReadFilter
s false --minimumMappingQuality 20
[16 November 2017 4:51:50 PM] Executing as vlad@spartan.hpc.unimelb.edu.au on Linux 4.13.12-1.el7.elrepo.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Version: 4.beta.5
16:51:50.648 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 1
16:51:50.648 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
16:51:50.649 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
16:51:50.649 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
16:51:50.649 INFO  HaplotypeCaller - Deflater: IntelDeflater
16:51:50.649 INFO  HaplotypeCaller - Inflater: IntelInflater
16:51:50.649 INFO  HaplotypeCaller - GCS max retries/reopens: 20
16:51:50.649 INFO  HaplotypeCaller - Using google-cloud-java patch c035098b5e62cb4fe9155eff07ce88449a361f5d from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
16:51:50.649 INFO  HaplotypeCaller - Initializing engine
16:51:51.056 INFO  FeatureManager - Using codec BEDCodec to read file file:///home/vlad/tmp/debug_gatk/bad_87-88.bed
16:51:51.063 INFO  IntervalArgumentCollection - Processing 1 bp from intervals
16:51:51.068 INFO  HaplotypeCaller - Done initializing engine
16:51:51.075 INFO  HaplotypeCallerEngine - Disabling physical phasing, which is supported only for reference-model confidence output
16:51:51.293 WARN  PossibleDeNovo - Annotation will not be calculated, must provide a valid PED file (-ped) from the command line.
16:51:51.509 WARN  PossibleDeNovo - Annotation will not be calculated, must provide a valid PED file (-ped) from the command line.
16:51:51.762 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/home/vlad/bcbio/anaconda/share/gatk4-4.0b5-0/gatk-package-4.beta.5-local.jar!/com/intel/gkl/native/libgkl_utils.so
16:51:51.764 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/home/vlad/bcbio/anaconda/share/gatk4-4.0b5-0/gatk-package-4.beta.5-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
16:51:51.795 WARN  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
16:51:51.796 INFO  IntelPairHmm - Available threads: 32
16:51:51.796 INFO  IntelPairHmm - Requested threads: 4
16:51:51.796 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
16:51:51.815 INFO  ProgressMeter - Starting traversal
16:51:51.815 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
16:51:51.881 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 0.0
16:51:51.881 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 0.0
16:51:51.881 INFO  HaplotypeCaller - Shutting down engine
[16 November 2017 4:51:51 PM] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=1640497152
java.lang.IllegalArgumentException: contig must be non-null and not equal to *, and start must be >= 1
        at org.broadinstitute.hellbender.utils.read.SAMRecordToGATKReadAdapter.setPosition(SAMRecordToGATKReadAdapter.java:92)
        at org.broadinstitute.hellbender.utils.clipping.ClippingOp.applyHARDCLIP_BASES(ClippingOp.java:381)
        at org.broadinstitute.hellbender.utils.clipping.ClippingOp.apply(ClippingOp.java:73)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:145)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.clipRead(ReadClipper.java:126)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipSoftClippedBases(ReadClipper.java:330)
        at org.broadinstitute.hellbender.utils.clipping.ReadClipper.hardClipSoftClippedBases(ReadClipper.java:333)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.finalizeRegion(AssemblyBasedCallerUtils.java:82)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:242)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:496)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:221)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:254)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:231)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:838)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:119)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:176)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:195)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:137)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:158)
        at org.broadinstitute.hellbender.Main.main(Main.java:239)
```

Attempts with different regions (e.g. neighbouring positions 86 or 88 at this chromosome, or other sets of reads, or taking one of the culprit reads alone) didn't give me the error.

Can you suggest what I'm doing wrong?

### PR DESCRIPTION
**Pull request by droazen**
We had another edge-case bug in our clipping code: when calling ReadClipper.revertSoftClippedBases()
on a read at the start of a contig (position == 1), we could end up with an empty read if the cigar
was something like "41S59H", since the reverted soft-clipped bases would just get hard-clipped away.
The method did not correctly handle this case, and blew up with an exception.

Added a unit test for ReadClipper that fails before the fix and passes after it, as well as an
integration test for HaplotypeCaller that also fails before the fix and passes after it.

Resolves #3845

### CODE REVIEW

File: src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java [hunk 1]
```diff
@@ -458,7 +458,9 @@ public void testReadsThatConsumeZeroReferenceReads() throws Exception {
         runCommandLine(args);
     }
 
-    // test fix for https://github.com/broadinstitute/gatk/issues/3466
+    // Test fix for https://github.com/broadinstitute/gatk/issues/3466
```
Comment (jamesemery) [inline src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java]: Thank you

File: src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java [hunk 2]
```diff
@@ -174,7 +172,13 @@ private GATKRead applyREVERT_SOFTCLIPPED_BASES(final GATKRead read) {
             // that cache these values, such as SAMRecord), and again after the hard clip.
             unclipped.setPosition(unclipped.getContig(), 1);
             unclipped = applyHARDCLIP_BASES(unclipped, 0, - newStart);
-            unclipped.setPosition(unclipped.getContig(), 1);
```
Comment (jamesemery) [inline src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java]: Minor thing I have noticed, You should probably add comments in the method contracts warning that these methods COULD return empty/unmapped reads

Comment (droazen) [reply src/main/java/org/broadinstitute/hellbender/utils/clipping/ClippingOp.java]: We'll do this as part of https://github.com/broadinstitute/gatk/issues/4204
