### PR TITLE
GetPileupSummaries streams output rather than storing it in memory

### LINKED ISSUE #7606: GetPileupSummaries Extraordinary Resource Usage and Lack of ProgressMeter Messages
I am trying version 4.2.3.0. I set `--java-options "-Xmx128g"` and it gradually increased to consume all of the RAM.

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
3286969 dario     20   0  136.7g 133.2g  27012 S  1478  26.4 725:33.44 java
```

The input is a modest whole genome sequencing BAM file.

```
$ ls -lh CSCC_0163-B1.final*
-r-------- 1 dario stgrad 9.2M Dec 15 10:22 CSCC_0163-B1.final.bai
-r-------- 1 dario stgrad  86G Dec 15 10:21 CSCC_0163-B1.final.bam
```

After about one hour without any progress messages, the process shuts down due to running out of heap space.

```
12:03:07.666 INFO  ProgressMeter - Starting traversal
12:03:07.666 INFO  ProgressMeter -        Current Locus  Elapsed Minutes        Loci Processed      Loci/Minute
13:08:22.336 INFO  GetPileupSummaries - Shutting down engine
[December 15, 2021 at 1:08:22 PM AEDT] org.broadinstitute.hellbender.tools.walkers.contamination.GetPileupSummaries done. Elapsed time: 84.45 minutes.
Runtime.totalMemory()=30333206528
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
```

The two other key parameters were `-L af-only-gnomad.hg38.vcf.gz -V af-only-gnomad.hg38.vcf.gz`. I think this module is far too inefficient to be in production, if this is how it typically works.

### PR DESCRIPTION
**Pull request by davidbenjamin**
Closes #7606.

@lbergelson This addresses the excessive memory issue that you triaged recently.  Would you mind reviewing it?

### CODE REVIEW

**Comment by davidbenjamin** [comment]
@takutosato Would you mind reviewing this PR?

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java [hunk 1]
```diff
@@ -208,7 +224,12 @@ public Object onTraversalSuccess() {
             throw new UserException.BadInput("No variants in population vcf had an allele frequency (AF) field.");
         }
         final String sampleName = ReadUtils.getSamplesFromHeader(getHeaderForReads()).stream().findFirst().get();
-        PileupSummary.writeToFile(sampleName, pileupSummaries, outputTable);
+
+        try {
```
Comment (takutosato) [inline src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java:228]: I think this belongs in closeTool rather than onTraversalSuccess (in case the traversal fails)

**Review by takutosato — APPROVED** [review]
One change request but looks good otherwise. Feel free to merge when ready.

File: src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java (hunk 1 above)
Comment (davidbenjamin) [reply src/main/java/org/broadinstitute/hellbender/tools/walkers/contamination/GetPileupSummaries.java:232]: good point

**Comment by nh13** [comment]
Thank-you, this will be super helpful!
