### PR TITLE
Fixing error when spanning deletions overlap coding regions

### LINKED ISSUE #4880: Spanning deletion (?) causes crash in Funcotator
### Affected tool(s) or class(es)
Funcotator

### Affected version(s)
- [x] Latest master branch as of June 11, 2018

### Description 
Getting a stacktrace (from a spanning deletion)
```
[June 11, 2018 2:18:29 PM EDT] org.broadinstitute.hellbender.tools.funcotator.Funcotator done. Elapsed time: 0.20 minutes.
Runtime.totalMemory()=1144520704
java.lang.IllegalArgumentException: base must be A, C, G or T. * is not a valid base.
	at org.broadinstitute.hellbender.utils.BaseUtils.getComplement(BaseUtils.java:268)
	at org.broadinstitute.hellbender.utils.read.ReadUtils.getBasesReverseComplement(ReadUtils.java:909)
	at org.broadinstitute.hellbender.tools.funcotator.FuncotatorUtils.getStrandCorrectedAllele(FuncotatorUtils.java:1841)

```
#### Steps to reproduce
```
GATK_CMD="java -jar /home/lichtens/IdeaProjects/gatk/build/libs/gatk.jar"
${GATK_CMD} Funcotator --output-file-format VCF \
--ref-version hg38 --data-sources-path /home/lichtens/broad_oncotator_configs/test_funcotator/funcotator_dataSources.v1.2_trim/ \
-R /home/lichtens/broad_oncotator_configs/ref/hg38/Homo_sapiens_assembly38.fasta -V hg38_trio.vcf.gz \
-O hg38_trio.funcotated.vcf \

```
I can provide input files, but since I am both reporting and fixing this issue, I already have them.

This is high priority since it could affect a group using Funcotator for their work on a tight deadline.

#### Expected behavior
No crash

#### Actual behavior
Crash with above stack trace

### PR DESCRIPTION
**Pull request by LeeTL1220**
- Fixes #4880 
- Adds test to catch this if it happens again.

Offline I ran it against a large hg38 file and it succeeded.

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java [hunk 1]
```diff
@@ -1875,6 +1880,55 @@ private GencodeFuncotation createIgrFuncotation(final VariantContext variant,
...
+        // Get GC Content:
+        funcotationBuilder.setGcContent( calculateGcContent( variant.getReference(), Allele.SPAN_DEL, reference, gcContentWindowSizeBases ) );
+
+        funcotationBuilder.setVariantClassification( GencodeFuncotation.VariantClassification.COULD_NOT_DETERMINE )
+                .setRefAllele( variant.getReference() )
+                .setStrand(Strand.POSITIVE)
+                .setTumorSeqAllele2( Allele.SPAN_DEL_STRING )
+                .setStart(variant.getStart())
+                .setEnd(variant.getEnd())
+                .setVariantType(getVariantType(variant.getReference(), Allele.SPAN_DEL))
```
Comment (jonn-smith) [inline src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: `getVariantType` right now doesn't know about spanning deletions.  Can you add a case to that method that will correctly identify this as a deletion?

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 2]
```diff
@@ -597,5 +599,53 @@ public void testVcfDatasourceAccountsForAltAlleles() {
...
+        Assert.assertTrue(variantContexts.size() > 0);
+        final VCFHeader vcfHeader = vcfInfo.getLeft();
+        final VCFInfoHeaderLine funcotationHeaderLine = vcfHeader.getInfoHeaderLine(VcfOutputRenderer.FUNCOTATOR_VCF_FIELD_NAME);
+        final String[] funcotationKeys = extractFuncotatorKeysFromHeaderDescription(funcotationHeaderLine.getDescription());
+
+        final int NUM_VARIANTS = 10;
+        Assert.assertEquals(variantContexts.size(), NUM_VARIANTS);
+        Assert.assertEquals(variantContexts.stream().filter(v -> v.hasAllele(Allele.SPAN_DEL)).count(), NUM_VARIANTS);
+
+        for (int i = 0; i < variantContexts.size(); i++) {
```
Comment (jonn-smith) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: `for ( final VariantContext vc : variantContexts )`

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 3]
```diff
@@ -597,5 +599,53 @@ public void testVcfDatasourceAccountsForAltAlleles() {
...
+            final Map<Allele, FuncotationMap> alleleToFuncotationMap = FuncotatorUtils.createAlleleToFuncotationMapFromFuncotationVcfAttribute(funcotationKeys,
+                    variantContexts.get(i), "Gencode_28_annotationTranscript", "TEST");
+
+            // Make sure that all spanning deletions are funcotated with could not determine and that the others are something else.
+            for (final Allele allele : alleleToFuncotationMap.keySet()) {
+                if (allele.equals(Allele.SPAN_DEL)) {
+                    final List<String> txIds = alleleToFuncotationMap.get(allele).getTranscriptList();
+                    for (String txId : txIds) {
```
Comment (jonn-smith) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: `final String txId : txIds`

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 4]
```diff
@@ -597,5 +599,53 @@ public void testVcfDatasourceAccountsForAltAlleles() {
...
+                        if (allele.equals(Allele.SPAN_DEL)) {
+                            Assert.assertEquals(alleleToFuncotationMap.get(allele).get(txId).get(0).getField("Gencode_28_variantClassification"), GencodeFuncotation.VariantClassification.COULD_NOT_DETERMINE.toString());
```
Comment (jonn-smith) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: FYI, the `COULD_NOT_DETERMINE` classification was something I added for this kind of thing.  It's not an official value for `VariantClassification` according to the spec. 

I'm fine with using it, but it may warrant further discussion.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 5]
```diff
@@ -597,5 +599,53 @@ public void testVcfDatasourceAccountsForAltAlleles() {
...
+        for (int i = 0; i < variantContexts.size(); i++) {
+            final Map<Allele, FuncotationMap> alleleToFuncotationMap = FuncotatorUtils.createAlleleToFuncotationMapFromFuncotationVcfAttribute(funcotationKeys,
+                    variantContexts.get(i), "Gencode_28_annotationTranscript", "TEST");
+
+            // Make sure that all spanning deletions are funcotated with could not determine and that the others are something else.
+            for (final Allele allele : alleleToFuncotationMap.keySet()) {
+                if (allele.equals(Allele.SPAN_DEL)) {
+                    final List<String> txIds = alleleToFuncotationMap.get(allele).getTranscriptList();
+                    for (String txId : txIds) {
+                        if (allele.equals(Allele.SPAN_DEL)) {
```
Comment (jonn-smith) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: You seem to check if allele is a spanning deletion twice in here.  You can get rid of this if statement.

**Comment by jonn-smith** [comment]
@LeeTL1220 back to you

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 3 above)
Comment (LeeTL1220) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Done

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 5 above)
Comment (LeeTL1220) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Yup... that was an error.  I removed the one at line 636

Done

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 1 above)
Comment (LeeTL1220) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: I created a variant type of NA.  This variant spans a deletion, but is not a deletion itself.

Also, adding test to MAF rendering to make sure spanking deletions do not cause trouble.

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java (hunk 4 above)
Comment (LeeTL1220) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: I think it is fine to use. 

Done

Comment (LeeTL1220) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: No action

File: src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java (hunk 1 above)
Comment (LeeTL1220) [reply src/main/java/org/broadinstitute/hellbender/tools/funcotator/dataSources/gencode/GencodeFuncotationFactory.java]: Done

File: src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java [hunk 6]
```diff
@@ -627,25 +627,44 @@ public void testCanAnnotateSpanningDeletions() {
...
+        arguments.addOutput(outputFile);
+        arguments.addReference(new File(hg38Chr3Ref));
+        arguments.addArgument(FuncotatorArgumentDefinitions.DATA_SOURCES_PATH_LONG_NAME, DS_PIK3CA_DIR);
+        arguments.addArgument(FuncotatorArgumentDefinitions.REFERENCE_VERSION_LONG_NAME, FuncotatorTestConstants.REFERENCE_VERSION_HG38);
+        arguments.addArgument(FuncotatorArgumentDefinitions.OUTPUT_FORMAT_LONG_NAME, outputFormatType.toString());
+
+        runCommandLine(arguments);
+
+        // There should only be one variant in the MAF, not two
+        final AnnotatedIntervalCollection annotatedIntervalCollection = AnnotatedIntervalCollection.create(outputFile.toPath(), null);
```
Comment (jonn-smith) [inline src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: In the other test I think you check to see that the variants are all spanning deletions.  Can you do that here as well just to make sure?

Comment (LeeTL1220) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: I cannot, since MAFs should drop spanning deletions, always.

@jonn-smith

Comment (LeeTL1220) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Can I merge now?  @jonn-smith

Comment (jonn-smith) [reply src/test/java/org/broadinstitute/hellbender/tools/funcotator/FuncotatorIntegrationTest.java]: Yeah - if it passes go for it.
